/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_CG-COT-Sharing-r16.h"

static int
memb_ASN_RRC_duration_r16_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 39)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_offset_r16_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 39)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_channelAccessPriority_r16_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ASN_RRC_duration_r16_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  1,  39 }	/* (1..39) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_offset_r16_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  1,  39 }	/* (1..39) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_channelAccessPriority_r16_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (1..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_ASN_RRC_CG_COT_Sharing_r16_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_cot_Sharing_r16_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CG_COT_Sharing_r16__cot_Sharing_r16, duration_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_duration_r16_constr_4,  memb_ASN_RRC_duration_r16_constraint_3 },
		0, 0, /* No default value */
		"duration-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CG_COT_Sharing_r16__cot_Sharing_r16, offset_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_offset_r16_constr_5,  memb_ASN_RRC_offset_r16_constraint_3 },
		0, 0, /* No default value */
		"offset-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CG_COT_Sharing_r16__cot_Sharing_r16, channelAccessPriority_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_channelAccessPriority_r16_constr_6,  memb_ASN_RRC_channelAccessPriority_r16_constraint_3 },
		0, 0, /* No default value */
		"channelAccessPriority-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_cot_Sharing_r16_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_cot_Sharing_r16_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* duration-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* offset-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* channelAccessPriority-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_cot_Sharing_r16_specs_3 = {
	sizeof(struct ASN_RRC_CG_COT_Sharing_r16__cot_Sharing_r16),
	offsetof(struct ASN_RRC_CG_COT_Sharing_r16__cot_Sharing_r16, _asn_ctx),
	asn_MAP_ASN_RRC_cot_Sharing_r16_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_cot_Sharing_r16_3 = {
	"cot-Sharing-r16",
	"cot-Sharing-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_cot_Sharing_r16_tags_3,
	sizeof(asn_DEF_ASN_RRC_cot_Sharing_r16_tags_3)
		/sizeof(asn_DEF_ASN_RRC_cot_Sharing_r16_tags_3[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_cot_Sharing_r16_tags_3,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_cot_Sharing_r16_tags_3)
		/sizeof(asn_DEF_ASN_RRC_cot_Sharing_r16_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_cot_Sharing_r16_3,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_cot_Sharing_r16_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_CG_COT_Sharing_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CG_COT_Sharing_r16, choice.noCOT_Sharing_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"noCOT-Sharing-r16"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CG_COT_Sharing_r16, choice.cot_Sharing_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ASN_RRC_cot_Sharing_r16_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cot-Sharing-r16"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_CG_COT_Sharing_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* noCOT-Sharing-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cot-Sharing-r16 */
};
asn_CHOICE_specifics_t asn_SPC_ASN_RRC_CG_COT_Sharing_r16_specs_1 = {
	sizeof(struct ASN_RRC_CG_COT_Sharing_r16),
	offsetof(struct ASN_RRC_CG_COT_Sharing_r16, _asn_ctx),
	offsetof(struct ASN_RRC_CG_COT_Sharing_r16, present),
	sizeof(((struct ASN_RRC_CG_COT_Sharing_r16 *)0)->present),
	asn_MAP_ASN_RRC_CG_COT_Sharing_r16_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_CG_COT_Sharing_r16 = {
	"CG-COT-Sharing-r16",
	"CG-COT-Sharing-r16",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_CG_COT_Sharing_r16_constr_1, CHOICE_constraint },
	asn_MBR_ASN_RRC_CG_COT_Sharing_r16_1,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_CG_COT_Sharing_r16_specs_1	/* Additional specs */
};

