/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_TA-Info-r17.h"

static int
memb_ASN_RRC_ta_Common_r17_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 66485757)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_ta_CommonDrift_r17_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -257303 && value <= 257303)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_ta_CommonDriftVariant_r17_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 28949)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ASN_RRC_ta_Common_r17_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 26, -1,  0,  66485757 }	/* (0..66485757) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_ta_CommonDrift_r17_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 19, -1, -257303,  257303 }	/* (-257303..257303) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_ta_CommonDriftVariant_r17_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 15,  15,  0,  28949 }	/* (0..28949) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ASN_RRC_TA_Info_r17_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_TA_Info_r17, ta_Common_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_ta_Common_r17_constr_2,  memb_ASN_RRC_ta_Common_r17_constraint_1 },
		0, 0, /* No default value */
		"ta-Common-r17"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_TA_Info_r17, ta_CommonDrift_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_ta_CommonDrift_r17_constr_3,  memb_ASN_RRC_ta_CommonDrift_r17_constraint_1 },
		0, 0, /* No default value */
		"ta-CommonDrift-r17"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_TA_Info_r17, ta_CommonDriftVariant_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_ta_CommonDriftVariant_r17_constr_4,  memb_ASN_RRC_ta_CommonDriftVariant_r17_constraint_1 },
		0, 0, /* No default value */
		"ta-CommonDriftVariant-r17"
		},
};
static const int asn_MAP_ASN_RRC_TA_Info_r17_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_TA_Info_r17_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_TA_Info_r17_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ta-Common-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ta-CommonDrift-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ta-CommonDriftVariant-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_TA_Info_r17_specs_1 = {
	sizeof(struct ASN_RRC_TA_Info_r17),
	offsetof(struct ASN_RRC_TA_Info_r17, _asn_ctx),
	asn_MAP_ASN_RRC_TA_Info_r17_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_TA_Info_r17_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_TA_Info_r17 = {
	"TA-Info-r17",
	"TA-Info-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_TA_Info_r17_tags_1,
	sizeof(asn_DEF_ASN_RRC_TA_Info_r17_tags_1)
		/sizeof(asn_DEF_ASN_RRC_TA_Info_r17_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_TA_Info_r17_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_TA_Info_r17_tags_1)
		/sizeof(asn_DEF_ASN_RRC_TA_Info_r17_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_TA_Info_r17_1,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_TA_Info_r17_specs_1	/* Additional specs */
};

