/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_SL-PRS-ResourceSharedSL-PRS-RP-r18.h"

static int
memb_ASN_RRC_n2_r18_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_n4_r18_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_dummy1_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl_PRS_ResourceID_r18_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_mNumberOfSymbols_r18_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ASN_RRC_n2_r18_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_n4_r18_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_dummy1_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl_PRS_ResourceID_r18_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  16 }	/* (0..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_mNumberOfSymbols_r18_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (1..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18__sl_PRS_CombSizeN_AndReOffset_r18, choice.n2_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_n2_r18_constr_5,  memb_ASN_RRC_n2_r18_constraint_4 },
		0, 0, /* No default value */
		"n2-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18__sl_PRS_CombSizeN_AndReOffset_r18, choice.n4_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_n4_r18_constr_6,  memb_ASN_RRC_n4_r18_constraint_4 },
		0, 0, /* No default value */
		"n4-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18__sl_PRS_CombSizeN_AndReOffset_r18, choice.dummy1),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_dummy1_constr_7,  memb_ASN_RRC_dummy1_constraint_4 },
		0, 0, /* No default value */
		"dummy1"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* n2-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* n4-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* dummy1 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_specs_4 = {
	sizeof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18__sl_PRS_CombSizeN_AndReOffset_r18),
	offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18__sl_PRS_CombSizeN_AndReOffset_r18, _asn_ctx),
	offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18__sl_PRS_CombSizeN_AndReOffset_r18, present),
	sizeof(((struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18__sl_PRS_CombSizeN_AndReOffset_r18 *)0)->present),
	asn_MAP_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_tag2el_4,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_4 = {
	"sl-PRS-CombSizeN-AndReOffset-r18",
	"sl-PRS-CombSizeN-AndReOffset-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_constr_4, CHOICE_constraint },
	asn_MBR_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_4,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18, sl_PRS_ResourceID_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl_PRS_ResourceID_r18_constr_2,  memb_ASN_RRC_sl_PRS_ResourceID_r18_constraint_1 },
		0, 0, /* No default value */
		"sl-PRS-ResourceID-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18, mNumberOfSymbols_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_mNumberOfSymbols_r18_constr_3,  memb_ASN_RRC_mNumberOfSymbols_r18_constraint_1 },
		0, 0, /* No default value */
		"mNumberOfSymbols-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18, sl_PRS_CombSizeN_AndReOffset_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_sl_PRS_CombSizeN_AndReOffset_r18_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-PRS-CombSizeN-AndReOffset-r18"
		},
};
static const int asn_MAP_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sl-PRS-ResourceID-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mNumberOfSymbols-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* sl-PRS-CombSizeN-AndReOffset-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_specs_1 = {
	sizeof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18),
	offsetof(struct ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18, _asn_ctx),
	asn_MAP_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18 = {
	"SL-PRS-ResourceSharedSL-PRS-RP-r18",
	"SL-PRS-ResourceSharedSL-PRS-RP-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tags_1,
	sizeof(asn_DEF_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_1,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_SL_PRS_ResourceSharedSL_PRS_RP_r18_specs_1	/* Additional specs */
};

