/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_PositionVelocity-r17.h"

asn_TYPE_member_t asn_MBR_ASN_RRC_PositionVelocity_r17_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_PositionVelocity_r17, positionX_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_PositionStateVector_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"positionX-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_PositionVelocity_r17, positionY_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_PositionStateVector_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"positionY-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_PositionVelocity_r17, positionZ_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_PositionStateVector_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"positionZ-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_PositionVelocity_r17, velocityVX_r17),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_VelocityStateVector_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"velocityVX-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_PositionVelocity_r17, velocityVY_r17),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_VelocityStateVector_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"velocityVY-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_PositionVelocity_r17, velocityVZ_r17),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_VelocityStateVector_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"velocityVZ-r17"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_PositionVelocity_r17_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_PositionVelocity_r17_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* positionX-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* positionY-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* positionZ-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* velocityVX-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* velocityVY-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* velocityVZ-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_PositionVelocity_r17_specs_1 = {
	sizeof(struct ASN_RRC_PositionVelocity_r17),
	offsetof(struct ASN_RRC_PositionVelocity_r17, _asn_ctx),
	asn_MAP_ASN_RRC_PositionVelocity_r17_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_PositionVelocity_r17 = {
	"PositionVelocity-r17",
	"PositionVelocity-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_PositionVelocity_r17_tags_1,
	sizeof(asn_DEF_ASN_RRC_PositionVelocity_r17_tags_1)
		/sizeof(asn_DEF_ASN_RRC_PositionVelocity_r17_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_PositionVelocity_r17_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_PositionVelocity_r17_tags_1)
		/sizeof(asn_DEF_ASN_RRC_PositionVelocity_r17_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_PositionVelocity_r17_1,
	6,	/* Elements count */
	&asn_SPC_ASN_RRC_PositionVelocity_r17_specs_1	/* Additional specs */
};

