/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_N1-N2-CBSR-r18.h"

static int
memb_ASN_RRC_cbsr_r18_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 27)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_8(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_11(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 35)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_14(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 24)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_17(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 43)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_20(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_23(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 59)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_26(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 48)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_29(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 75)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_32(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 75)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_cbsr_r18_constraint_35(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  8,  8 }	/* (SIZE(8..8)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_two_one_r18_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  27,  27 }	/* (SIZE(27..27)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_two_two_r18_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_10 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  16,  16 }	/* (SIZE(16..16)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_four_one_r18_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  35,  35 }	/* (SIZE(35..35)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_three_two_r18_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_16 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  24,  24 }	/* (SIZE(24..24)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_six_one_r18_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_19 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  43,  43 }	/* (SIZE(43..43)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_four_two_r18_constr_17 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_22 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  32,  32 }	/* (SIZE(32..32)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_eight_one_r18_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_25 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  59,  59 }	/* (SIZE(59..59)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_four_three_r18_constr_23 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_28 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  48,  48 }	/* (SIZE(48..48)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_twelve_one_r18_constr_26 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_31 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  75,  75 }	/* (SIZE(75..75)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_four_four_r18_constr_29 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_34 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  75,  75 }	/* (SIZE(75..75)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_eight_two_r18_constr_32 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cbsr_r18_constr_37 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  64,  64 }	/* (SIZE(64..64)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_sixteen_one_r18_constr_35 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_ASN_RRC_N1_N2_CBSR_r18_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  11 }	/* (0..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_two_one_r18_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__two_one_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__two_one_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_4,  memb_ASN_RRC_cbsr_r18_constraint_2 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_two_one_r18_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_two_one_r18_specs_2 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__two_one_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__two_one_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__two_one_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__two_one_r18 *)0)->present),
	asn_MAP_ASN_RRC_two_one_r18_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_two_one_r18_2 = {
	"two-one-r18",
	"two-one-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_two_one_r18_constr_2, CHOICE_constraint },
	asn_MBR_ASN_RRC_two_one_r18_2,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_two_one_r18_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_two_two_r18_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__two_two_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__two_two_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_7,  memb_ASN_RRC_cbsr_r18_constraint_5 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_two_two_r18_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_two_two_r18_specs_5 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__two_two_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__two_two_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__two_two_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__two_two_r18 *)0)->present),
	asn_MAP_ASN_RRC_two_two_r18_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_two_two_r18_5 = {
	"two-two-r18",
	"two-two-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_two_two_r18_constr_5, CHOICE_constraint },
	asn_MBR_ASN_RRC_two_two_r18_5,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_two_two_r18_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_four_one_r18_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_one_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_one_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_10,  memb_ASN_RRC_cbsr_r18_constraint_8 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_four_one_r18_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_four_one_r18_specs_8 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__four_one_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_one_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_one_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__four_one_r18 *)0)->present),
	asn_MAP_ASN_RRC_four_one_r18_tag2el_8,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_four_one_r18_8 = {
	"four-one-r18",
	"four-one-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_four_one_r18_constr_8, CHOICE_constraint },
	asn_MBR_ASN_RRC_four_one_r18_8,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_four_one_r18_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_three_two_r18_11[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__three_two_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__three_two_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_13,  memb_ASN_RRC_cbsr_r18_constraint_11 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_three_two_r18_tag2el_11[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_three_two_r18_specs_11 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__three_two_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__three_two_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__three_two_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__three_two_r18 *)0)->present),
	asn_MAP_ASN_RRC_three_two_r18_tag2el_11,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_three_two_r18_11 = {
	"three-two-r18",
	"three-two-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_three_two_r18_constr_11, CHOICE_constraint },
	asn_MBR_ASN_RRC_three_two_r18_11,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_three_two_r18_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_six_one_r18_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__six_one_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__six_one_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_16,  memb_ASN_RRC_cbsr_r18_constraint_14 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_six_one_r18_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_six_one_r18_specs_14 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__six_one_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__six_one_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__six_one_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__six_one_r18 *)0)->present),
	asn_MAP_ASN_RRC_six_one_r18_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_six_one_r18_14 = {
	"six-one-r18",
	"six-one-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_six_one_r18_constr_14, CHOICE_constraint },
	asn_MBR_ASN_RRC_six_one_r18_14,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_six_one_r18_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_four_two_r18_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_two_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_two_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_19,  memb_ASN_RRC_cbsr_r18_constraint_17 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_four_two_r18_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_four_two_r18_specs_17 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__four_two_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_two_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_two_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__four_two_r18 *)0)->present),
	asn_MAP_ASN_RRC_four_two_r18_tag2el_17,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_four_two_r18_17 = {
	"four-two-r18",
	"four-two-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_four_two_r18_constr_17, CHOICE_constraint },
	asn_MBR_ASN_RRC_four_two_r18_17,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_four_two_r18_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_eight_one_r18_20[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__eight_one_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__eight_one_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_22,  memb_ASN_RRC_cbsr_r18_constraint_20 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_eight_one_r18_tag2el_20[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_eight_one_r18_specs_20 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__eight_one_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__eight_one_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__eight_one_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__eight_one_r18 *)0)->present),
	asn_MAP_ASN_RRC_eight_one_r18_tag2el_20,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_eight_one_r18_20 = {
	"eight-one-r18",
	"eight-one-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_eight_one_r18_constr_20, CHOICE_constraint },
	asn_MBR_ASN_RRC_eight_one_r18_20,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_eight_one_r18_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_four_three_r18_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_three_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_three_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_25,  memb_ASN_RRC_cbsr_r18_constraint_23 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_four_three_r18_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_four_three_r18_specs_23 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__four_three_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_three_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_three_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__four_three_r18 *)0)->present),
	asn_MAP_ASN_RRC_four_three_r18_tag2el_23,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_four_three_r18_23 = {
	"four-three-r18",
	"four-three-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_four_three_r18_constr_23, CHOICE_constraint },
	asn_MBR_ASN_RRC_four_three_r18_23,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_four_three_r18_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_twelve_one_r18_26[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__twelve_one_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__twelve_one_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_28,  memb_ASN_RRC_cbsr_r18_constraint_26 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_twelve_one_r18_tag2el_26[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_twelve_one_r18_specs_26 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__twelve_one_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__twelve_one_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__twelve_one_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__twelve_one_r18 *)0)->present),
	asn_MAP_ASN_RRC_twelve_one_r18_tag2el_26,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_twelve_one_r18_26 = {
	"twelve-one-r18",
	"twelve-one-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_twelve_one_r18_constr_26, CHOICE_constraint },
	asn_MBR_ASN_RRC_twelve_one_r18_26,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_twelve_one_r18_specs_26	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_four_four_r18_29[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_four_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_four_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_31,  memb_ASN_RRC_cbsr_r18_constraint_29 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_four_four_r18_tag2el_29[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_four_four_r18_specs_29 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__four_four_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_four_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__four_four_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__four_four_r18 *)0)->present),
	asn_MAP_ASN_RRC_four_four_r18_tag2el_29,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_four_four_r18_29 = {
	"four-four-r18",
	"four-four-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_four_four_r18_constr_29, CHOICE_constraint },
	asn_MBR_ASN_RRC_four_four_r18_29,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_four_four_r18_specs_29	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_eight_two_r18_32[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__eight_two_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__eight_two_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_34,  memb_ASN_RRC_cbsr_r18_constraint_32 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_eight_two_r18_tag2el_32[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_eight_two_r18_specs_32 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__eight_two_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__eight_two_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__eight_two_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__eight_two_r18 *)0)->present),
	asn_MAP_ASN_RRC_eight_two_r18_tag2el_32,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_eight_two_r18_32 = {
	"eight-two-r18",
	"eight-two-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_eight_two_r18_constr_32, CHOICE_constraint },
	asn_MBR_ASN_RRC_eight_two_r18_32,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_eight_two_r18_specs_32	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_sixteen_one_r18_35[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__sixteen_one_r18, choice.no_cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"no-cbsr-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18__sixteen_one_r18, choice.cbsr_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cbsr_r18_constr_37,  memb_ASN_RRC_cbsr_r18_constraint_35 },
		0, 0, /* No default value */
		"cbsr-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_sixteen_one_r18_tag2el_35[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* no-cbsr-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cbsr-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_sixteen_one_r18_specs_35 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18__sixteen_one_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__sixteen_one_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18__sixteen_one_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18__sixteen_one_r18 *)0)->present),
	asn_MAP_ASN_RRC_sixteen_one_r18_tag2el_35,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_sixteen_one_r18_35 = {
	"sixteen-one-r18",
	"sixteen-one-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_sixteen_one_r18_constr_35, CHOICE_constraint },
	asn_MBR_ASN_RRC_sixteen_one_r18_35,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_sixteen_one_r18_specs_35	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_N1_N2_CBSR_r18_1[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.two_one_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_two_one_r18_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"two-one-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.two_two_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_two_two_r18_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"two-two-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.four_one_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_four_one_r18_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"four-one-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.three_two_r18),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_three_two_r18_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"three-two-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.six_one_r18),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_six_one_r18_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"six-one-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.four_two_r18),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_four_two_r18_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"four-two-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.eight_one_r18),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_eight_one_r18_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eight-one-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.four_three_r18),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_four_three_r18_23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"four-three-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.twelve_one_r18),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_twelve_one_r18_26,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"twelve-one-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.four_four_r18),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_four_four_r18_29,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"four-four-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.eight_two_r18),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_eight_two_r18_32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eight-two-r18"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_N1_N2_CBSR_r18, choice.sixteen_one_r18),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_sixteen_one_r18_35,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sixteen-one-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_N1_N2_CBSR_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* two-one-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* two-two-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* four-one-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* three-two-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* six-one-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* four-two-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* eight-one-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* four-three-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* twelve-one-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* four-four-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* eight-two-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* sixteen-one-r18 */
};
asn_CHOICE_specifics_t asn_SPC_ASN_RRC_N1_N2_CBSR_r18_specs_1 = {
	sizeof(struct ASN_RRC_N1_N2_CBSR_r18),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18, _asn_ctx),
	offsetof(struct ASN_RRC_N1_N2_CBSR_r18, present),
	sizeof(((struct ASN_RRC_N1_N2_CBSR_r18 *)0)->present),
	asn_MAP_ASN_RRC_N1_N2_CBSR_r18_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_N1_N2_CBSR_r18 = {
	"N1-N2-CBSR-r18",
	"N1-N2-CBSR-r18",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_N1_N2_CBSR_r18_constr_1, CHOICE_constraint },
	asn_MBR_ASN_RRC_N1_N2_CBSR_r18_1,
	12,	/* Elements count */
	&asn_SPC_ASN_RRC_N1_N2_CBSR_r18_specs_1	/* Additional specs */
};

