/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_UE_NR_Capability_v1740_H_
#define	_ASN_RRC_UE_NR_Capability_v1740_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_RRC_RedCapParameters-v1740.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_RRC_UE_NR_Capability_v1750;

/* UE-NR-Capability-v1740 */
typedef struct ASN_RRC_UE_NR_Capability_v1740 {
	ASN_RRC_RedCapParameters_v1740_t	 redCapParameters_v1740;
	struct ASN_RRC_UE_NR_Capability_v1750	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_UE_NR_Capability_v1740_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_UE_NR_Capability_v1740;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_UE_NR_Capability_v1740_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_UE_NR_Capability_v1740_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_UE_NR_Capability_v1740_H_ */
#include "../asn1c/asn_internal.h"
