/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_SL-SFN-DFN-Offset-r18.h"

static int
memb_ASN_RRC_sl_FrameOffset_r18_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1023)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl_SubframeOffset_r18_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl_SlotOffset_r18_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 31)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl_FrameOffset_r18_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 10,  10,  0,  1023 }	/* (0..1023) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl_SubframeOffset_r18_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl_SlotOffset_r18_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ASN_RRC_SL_SFN_DFN_Offset_r18_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SL_SFN_DFN_Offset_r18, sl_FrameOffset_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl_FrameOffset_r18_constr_2,  memb_ASN_RRC_sl_FrameOffset_r18_constraint_1 },
		0, 0, /* No default value */
		"sl-FrameOffset-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SL_SFN_DFN_Offset_r18, sl_SubframeOffset_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl_SubframeOffset_r18_constr_3,  memb_ASN_RRC_sl_SubframeOffset_r18_constraint_1 },
		0, 0, /* No default value */
		"sl-SubframeOffset-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SL_SFN_DFN_Offset_r18, sl_SlotOffset_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl_SlotOffset_r18_constr_4,  memb_ASN_RRC_sl_SlotOffset_r18_constraint_1 },
		0, 0, /* No default value */
		"sl-SlotOffset-r18"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_SL_SFN_DFN_Offset_r18_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_SL_SFN_DFN_Offset_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sl-FrameOffset-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sl-SubframeOffset-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* sl-SlotOffset-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SL_SFN_DFN_Offset_r18_specs_1 = {
	sizeof(struct ASN_RRC_SL_SFN_DFN_Offset_r18),
	offsetof(struct ASN_RRC_SL_SFN_DFN_Offset_r18, _asn_ctx),
	asn_MAP_ASN_RRC_SL_SFN_DFN_Offset_r18_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SL_SFN_DFN_Offset_r18 = {
	"SL-SFN-DFN-Offset-r18",
	"SL-SFN-DFN-Offset-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_SL_SFN_DFN_Offset_r18_tags_1,
	sizeof(asn_DEF_ASN_RRC_SL_SFN_DFN_Offset_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_SL_SFN_DFN_Offset_r18_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_SL_SFN_DFN_Offset_r18_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_SL_SFN_DFN_Offset_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_SL_SFN_DFN_Offset_r18_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_SL_SFN_DFN_Offset_r18_1,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_SL_SFN_DFN_Offset_r18_specs_1	/* Additional specs */
};

