/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_H_
#define	_ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeInteger.h"
#include "../asn1c/constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_PR {
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_PR_NOTHING,	/* No components present */
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_PR_scs15,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_PR_scs30,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_PR_scs60,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_PR_scs120
	/* Extensions may appear below */
	
} ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_PR;
typedef enum ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR {
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_NOTHING,	/* No components present */
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n4,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n5,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n8,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n10,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n16,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n20,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n32,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n40,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n64,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n80,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n160,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n320,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n640,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n1280,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n2560,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n5120,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR_n10240
	/* Extensions may appear below */
	
} ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR;
typedef enum ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR {
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_NOTHING,	/* No components present */
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n8,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n10,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n16,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n20,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n32,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n40,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n64,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n80,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n128,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n160,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n320,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n640,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n1280,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n2560,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n5120,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n10240,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR_n20480
	/* Extensions may appear below */
	
} ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR;
typedef enum ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR {
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_NOTHING,	/* No components present */
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n16,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n20,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n32,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n40,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n64,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n80,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n128,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n160,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n256,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n320,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n640,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n1280,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n2560,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n5120,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n10240,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n20480,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR_n40960
	/* Extensions may appear below */
	
} ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR;
typedef enum ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR {
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_NOTHING,	/* No components present */
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n32,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n40,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n64,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n80,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n128,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n160,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n256,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n320,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n512,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n640,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n1280,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n2560,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n5120,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n10240,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n20480,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n40960,
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR_n81920
	/* Extensions may appear below */
	
} ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR;

/* DL-PPW-PeriodicityAndStartSlot-r17 */
typedef struct ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17 {
	ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_PR present;
	union ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_u {
		struct ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15 {
			ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_PR present;
			union ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs15_u {
				long	 n4;
				long	 n5;
				long	 n8;
				long	 n10;
				long	 n16;
				long	 n20;
				long	 n32;
				long	 n40;
				long	 n64;
				long	 n80;
				long	 n160;
				long	 n320;
				long	 n640;
				long	 n1280;
				long	 n2560;
				long	 n5120;
				long	 n10240;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *scs15;
		struct ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30 {
			ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_PR present;
			union ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs30_u {
				long	 n8;
				long	 n10;
				long	 n16;
				long	 n20;
				long	 n32;
				long	 n40;
				long	 n64;
				long	 n80;
				long	 n128;
				long	 n160;
				long	 n320;
				long	 n640;
				long	 n1280;
				long	 n2560;
				long	 n5120;
				long	 n10240;
				long	 n20480;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *scs30;
		struct ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60 {
			ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_PR present;
			union ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs60_u {
				long	 n16;
				long	 n20;
				long	 n32;
				long	 n40;
				long	 n64;
				long	 n80;
				long	 n128;
				long	 n160;
				long	 n256;
				long	 n320;
				long	 n640;
				long	 n1280;
				long	 n2560;
				long	 n5120;
				long	 n10240;
				long	 n20480;
				long	 n40960;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *scs60;
		struct ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120 {
			ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_PR present;
			union ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17__scs120_u {
				long	 n32;
				long	 n40;
				long	 n64;
				long	 n80;
				long	 n128;
				long	 n160;
				long	 n256;
				long	 n320;
				long	 n512;
				long	 n640;
				long	 n1280;
				long	 n2560;
				long	 n5120;
				long	 n10240;
				long	 n20480;
				long	 n40960;
				long	 n81920;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *scs120;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17;
extern asn_CHOICE_specifics_t asn_SPC_ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_1[4];
extern asn_per_constraints_t asn_PER_type_ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_DL_PPW_PeriodicityAndStartSlot_r17_H_ */
#include "../asn1c/asn_internal.h"
