/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_VarLogMeasConfig-r16.h"

#include "ASN_RRC_AreaConfiguration-r16.h"
#include "ASN_RRC_BT-NameList-r16.h"
#include "ASN_RRC_WLAN-NameList-r16.h"
#include "ASN_RRC_Sensor-NameList-r16.h"
#include "ASN_RRC_AreaConfiguration-r17.h"
#include "ASN_RRC_AreaConfiguration-v1800.h"
#include "ASN_RRC_LoggedPeriodicalReportConfig-r16.h"
#include "ASN_RRC_LoggedEventTriggerConfig-r16.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_ASN_RRC_reportType_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_earlyMeasIndication_r17_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_reportType_7[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_VarLogMeasConfig_r16__reportType, choice.periodical),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_LoggedPeriodicalReportConfig_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"periodical"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_VarLogMeasConfig_r16__reportType, choice.eventTriggered),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_LoggedEventTriggerConfig_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventTriggered"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_reportType_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* periodical */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eventTriggered */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_reportType_specs_7 = {
	sizeof(struct ASN_RRC_VarLogMeasConfig_r16__reportType),
	offsetof(struct ASN_RRC_VarLogMeasConfig_r16__reportType, _asn_ctx),
	offsetof(struct ASN_RRC_VarLogMeasConfig_r16__reportType, present),
	sizeof(((struct ASN_RRC_VarLogMeasConfig_r16__reportType *)0)->present),
	asn_MAP_ASN_RRC_reportType_tag2el_7,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_reportType_7 = {
	"reportType",
	"reportType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_reportType_constr_7, CHOICE_constraint },
	asn_MBR_ASN_RRC_reportType_7,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_reportType_specs_7	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_earlyMeasIndication_r17_value2enum_10[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_ASN_RRC_earlyMeasIndication_r17_enum2value_10[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_earlyMeasIndication_r17_specs_10 = {
	asn_MAP_ASN_RRC_earlyMeasIndication_r17_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_earlyMeasIndication_r17_enum2value_10,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_earlyMeasIndication_r17_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_earlyMeasIndication_r17_10 = {
	"earlyMeasIndication-r17",
	"earlyMeasIndication-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_earlyMeasIndication_r17_tags_10,
	sizeof(asn_DEF_ASN_RRC_earlyMeasIndication_r17_tags_10)
		/sizeof(asn_DEF_ASN_RRC_earlyMeasIndication_r17_tags_10[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_earlyMeasIndication_r17_tags_10,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_earlyMeasIndication_r17_tags_10)
		/sizeof(asn_DEF_ASN_RRC_earlyMeasIndication_r17_tags_10[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_earlyMeasIndication_r17_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_earlyMeasIndication_r17_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_VarLogMeasConfig_r16_1[] = {
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, areaConfiguration_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_AreaConfiguration_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"areaConfiguration-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, bt_NameList_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BT_NameList_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bt-NameList-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, wlan_NameList_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_WLAN_NameList_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"wlan-NameList-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, sensor_NameList_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_Sensor_NameList_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sensor-NameList-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, loggingDuration_r16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_LoggingDuration_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"loggingDuration-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, reportType),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_reportType_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportType"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, earlyMeasIndication_r17),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_earlyMeasIndication_r17_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"earlyMeasIndication-r17"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, areaConfiguration_r17),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_AreaConfiguration_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"areaConfiguration-r17"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_VarLogMeasConfig_r16, areaConfiguration_v1800),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_AreaConfiguration_v1800,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"areaConfiguration-v1800"
		},
};
static const int asn_MAP_ASN_RRC_VarLogMeasConfig_r16_oms_1[] = { 0, 1, 2, 3, 6, 7, 8 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_VarLogMeasConfig_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_VarLogMeasConfig_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* areaConfiguration-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* bt-NameList-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* wlan-NameList-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sensor-NameList-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* loggingDuration-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* reportType */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* earlyMeasIndication-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* areaConfiguration-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* areaConfiguration-v1800 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_VarLogMeasConfig_r16_specs_1 = {
	sizeof(struct ASN_RRC_VarLogMeasConfig_r16),
	offsetof(struct ASN_RRC_VarLogMeasConfig_r16, _asn_ctx),
	asn_MAP_ASN_RRC_VarLogMeasConfig_r16_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_VarLogMeasConfig_r16_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_VarLogMeasConfig_r16 = {
	"VarLogMeasConfig-r16",
	"VarLogMeasConfig-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_VarLogMeasConfig_r16_tags_1,
	sizeof(asn_DEF_ASN_RRC_VarLogMeasConfig_r16_tags_1)
		/sizeof(asn_DEF_ASN_RRC_VarLogMeasConfig_r16_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_VarLogMeasConfig_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_VarLogMeasConfig_r16_tags_1)
		/sizeof(asn_DEF_ASN_RRC_VarLogMeasConfig_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_VarLogMeasConfig_r16_1,
	9,	/* Elements count */
	&asn_SPC_ASN_RRC_VarLogMeasConfig_r16_specs_1	/* Additional specs */
};

