/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_RF-ParametersMRDC.h"

#include "ASN_RRC_BandCombinationList.h"
#include "ASN_RRC_FreqBandList.h"
#include "ASN_RRC_BandCombinationList-v1540.h"
#include "ASN_RRC_BandCombinationList-v1550.h"
#include "ASN_RRC_BandCombinationList-v1560.h"
#include "ASN_RRC_BandCombinationList-v1570.h"
#include "ASN_RRC_BandCombinationList-v1580.h"
#include "ASN_RRC_BandCombinationList-v1590.h"
#include "ASN_RRC_BandCombinationList-v1610.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-r16.h"
#include "ASN_RRC_BandCombinationList-v1630.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1630.h"
#include "ASN_RRC_BandCombinationList-v1640.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1640.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1670.h"
#include "ASN_RRC_BandCombinationList-v1700.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1700.h"
#include "ASN_RRC_BandCombinationList-v1720.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1720.h"
#include "ASN_RRC_BandCombinationList-v1730.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1730.h"
#include "ASN_RRC_BandCombinationList-v1740.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1740.h"
#include "ASN_RRC_BandCombinationList-v1770.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1770.h"
#include "ASN_RRC_BandCombinationList-v1780.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1780.h"
#include "ASN_RRC_BandCombinationList-v1790.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1790.h"
#include "ASN_RRC_BandCombinationList-v1800.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1800.h"
#include "ASN_RRC_BandCombinationList-v1830.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1830.h"
#include "ASN_RRC_BandCombinationList-v1840.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1840.h"
#include "ASN_RRC_BandCombinationList-v1860.h"
#include "ASN_RRC_BandCombinationList-UplinkTxSwitch-v1860.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_ASN_RRC_srs_SwitchingTimeRequested_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_srs_SwitchingTimeRequested_value2enum_5[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_ASN_RRC_srs_SwitchingTimeRequested_enum2value_5[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_srs_SwitchingTimeRequested_specs_5 = {
	asn_MAP_ASN_RRC_srs_SwitchingTimeRequested_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_srs_SwitchingTimeRequested_enum2value_5,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_5 = {
	"srs-SwitchingTimeRequested",
	"srs-SwitchingTimeRequested",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_5,
	sizeof(asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_5)
		/sizeof(asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_5[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_5,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_5)
		/sizeof(asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_5[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_srs_SwitchingTimeRequested_constr_5, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_srs_SwitchingTimeRequested_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_14[] = {
	{ ATF_POINTER, 5, offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v15a0, supportedBandCombinationList_v1540),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1540,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1540"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v15a0, supportedBandCombinationList_v1560),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1560,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1560"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v15a0, supportedBandCombinationList_v1570),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1570,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1570"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v15a0, supportedBandCombinationList_v1580),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1580,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1580"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v15a0, supportedBandCombinationList_v1590),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1590,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1590"
		},
};
static const int asn_MAP_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_oms_14[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedBandCombinationList-v1540 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* supportedBandCombinationList-v1560 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* supportedBandCombinationList-v1570 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* supportedBandCombinationList-v1580 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* supportedBandCombinationList-v1590 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_specs_14 = {
	sizeof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v15a0),
	offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v15a0, _asn_ctx),
	asn_MAP_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tag2el_14,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_oms_14,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_14 = {
	"supportedBandCombinationListNEDC-Only-v15a0",
	"supportedBandCombinationListNEDC-Only-v15a0",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tags_14,
	sizeof(asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tags_14)
		/sizeof(asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tags_14[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tags_14,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tags_14)
		/sizeof(asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_tags_14[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_14,
	5,	/* Elements count */
	&asn_SPC_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_33[] = {
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v1720, supportedBandCombinationList_v1700),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1700,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1700"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v1720, supportedBandCombinationList_v1720),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1720,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1720"
		},
};
static const int asn_MAP_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_oms_33[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tag2el_33[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedBandCombinationList-v1700 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* supportedBandCombinationList-v1720 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_specs_33 = {
	sizeof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v1720),
	offsetof(struct ASN_RRC_RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v1720, _asn_ctx),
	asn_MAP_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tag2el_33,
	2,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_oms_33,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_33 = {
	"supportedBandCombinationListNEDC-Only-v1720",
	"supportedBandCombinationListNEDC-Only-v1720",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tags_33,
	sizeof(asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tags_33)
		/sizeof(asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tags_33[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tags_33,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tags_33)
		/sizeof(asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_tags_33[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_33,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_specs_33	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_RF_ParametersMRDC_1[] = {
	{ ATF_POINTER, 47, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList"
		},
	{ ATF_POINTER, 46, offsetof(struct ASN_RRC_RF_ParametersMRDC, appliedFreqBandListFilter),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_FreqBandList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"appliedFreqBandListFilter"
		},
	{ ATF_POINTER, 45, offsetof(struct ASN_RRC_RF_ParametersMRDC, srs_SwitchingTimeRequested),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srs-SwitchingTimeRequested"
		},
	{ ATF_POINTER, 44, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1540),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1540,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1540"
		},
	{ ATF_POINTER, 43, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1550),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1550,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1550"
		},
	{ ATF_POINTER, 42, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1560),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1560,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1560"
		},
	{ ATF_POINTER, 41, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only"
		},
	{ ATF_POINTER, 40, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1570),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1570,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1570"
		},
	{ ATF_POINTER, 39, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1580),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1580,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1580"
		},
	{ ATF_POINTER, 38, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1590),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1590,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1590"
		},
	{ ATF_POINTER, 37, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only_v15a0),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		0,
		&asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v15a0_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only-v15a0"
		},
	{ ATF_POINTER, 36, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1610),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1610,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1610"
		},
	{ ATF_POINTER, 35, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only_v1610),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1610,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only-v1610"
		},
	{ ATF_POINTER, 34, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_r16),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-r16"
		},
	{ ATF_POINTER, 33, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1630),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1630,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1630"
		},
	{ ATF_POINTER, 32, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only_v1630),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1630,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only-v1630"
		},
	{ ATF_POINTER, 31, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1630),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1630,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1630"
		},
	{ ATF_POINTER, 30, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1640),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1640,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1640"
		},
	{ ATF_POINTER, 29, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only_v1640),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1640,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only-v1640"
		},
	{ ATF_POINTER, 28, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1640),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1640,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1640"
		},
	{ ATF_POINTER, 27, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1670),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1670,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1670"
		},
	{ ATF_POINTER, 26, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1700),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1700,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1700"
		},
	{ ATF_POINTER, 25, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1700),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1700,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1700"
		},
	{ ATF_POINTER, 24, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1720),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1720,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1720"
		},
	{ ATF_POINTER, 23, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only_v1720),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		0,
		&asn_DEF_ASN_RRC_supportedBandCombinationListNEDC_Only_v1720_33,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only-v1720"
		},
	{ ATF_POINTER, 22, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1720),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1720,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1720"
		},
	{ ATF_POINTER, 21, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1730),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1730,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1730"
		},
	{ ATF_POINTER, 20, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only_v1730),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1730,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only-v1730"
		},
	{ ATF_POINTER, 19, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1730),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1730,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1730"
		},
	{ ATF_POINTER, 18, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1740),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1740,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1740"
		},
	{ ATF_POINTER, 17, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only_v1740),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1740,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only-v1740"
		},
	{ ATF_POINTER, 16, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1740),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1740,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1740"
		},
	{ ATF_POINTER, 15, offsetof(struct ASN_RRC_RF_ParametersMRDC, dummy1),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1770,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dummy1"
		},
	{ ATF_POINTER, 14, offsetof(struct ASN_RRC_RF_ParametersMRDC, dummy2),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1770,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dummy2"
		},
	{ ATF_POINTER, 13, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1780),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1780,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1780"
		},
	{ ATF_POINTER, 12, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationListNEDC_Only_v1780),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1780,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only-v1780"
		},
	{ ATF_POINTER, 11, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1780),
		(ASN_TAG_CLASS_CONTEXT | (36 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1780,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1780"
		},
	{ ATF_POINTER, 10, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1790),
		(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1790,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1790"
		},
	{ ATF_POINTER, 9, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1790),
		(ASN_TAG_CLASS_CONTEXT | (38 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1790,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1790"
		},
	{ ATF_POINTER, 8, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1800),
		(ASN_TAG_CLASS_CONTEXT | (39 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1800,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1800"
		},
	{ ATF_POINTER, 7, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1800),
		(ASN_TAG_CLASS_CONTEXT | (40 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1800,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1800"
		},
	{ ATF_POINTER, 6, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1830),
		(ASN_TAG_CLASS_CONTEXT | (41 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1830,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1830"
		},
	{ ATF_POINTER, 5, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1830),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1830,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1830"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1840),
		(ASN_TAG_CLASS_CONTEXT | (43 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1840,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1840"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1840),
		(ASN_TAG_CLASS_CONTEXT | (44 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1840,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1840"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_v1860),
		(ASN_TAG_CLASS_CONTEXT | (45 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1860,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1860"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList_UplinkTxSwitch_v1860),
		(ASN_TAG_CLASS_CONTEXT | (46 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_UplinkTxSwitch_v1860,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-UplinkTxSwitch-v1860"
		},
};
static const int asn_MAP_ASN_RRC_RF_ParametersMRDC_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_RF_ParametersMRDC_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedBandCombinationList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* appliedFreqBandListFilter */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* srs-SwitchingTimeRequested */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* supportedBandCombinationList-v1540 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* supportedBandCombinationList-v1550 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* supportedBandCombinationList-v1560 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* supportedBandCombinationListNEDC-Only */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* supportedBandCombinationList-v1570 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* supportedBandCombinationList-v1580 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* supportedBandCombinationList-v1590 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* supportedBandCombinationListNEDC-Only-v15a0 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* supportedBandCombinationList-v1610 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* supportedBandCombinationListNEDC-Only-v1610 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* supportedBandCombinationList-v1630 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* supportedBandCombinationListNEDC-Only-v1630 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1630 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* supportedBandCombinationList-v1640 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* supportedBandCombinationListNEDC-Only-v1640 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1640 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1670 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* supportedBandCombinationList-v1700 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1700 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* supportedBandCombinationList-v1720 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* supportedBandCombinationListNEDC-Only-v1720 */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1720 */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* supportedBandCombinationList-v1730 */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* supportedBandCombinationListNEDC-Only-v1730 */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1730 */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 29, 0, 0 }, /* supportedBandCombinationList-v1740 */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 30, 0, 0 }, /* supportedBandCombinationListNEDC-Only-v1740 */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 31, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1740 */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 32, 0, 0 }, /* dummy1 */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 33, 0, 0 }, /* dummy2 */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 34, 0, 0 }, /* supportedBandCombinationList-v1780 */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 35, 0, 0 }, /* supportedBandCombinationListNEDC-Only-v1780 */
    { (ASN_TAG_CLASS_CONTEXT | (36 << 2)), 36, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1780 */
    { (ASN_TAG_CLASS_CONTEXT | (37 << 2)), 37, 0, 0 }, /* supportedBandCombinationList-v1790 */
    { (ASN_TAG_CLASS_CONTEXT | (38 << 2)), 38, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1790 */
    { (ASN_TAG_CLASS_CONTEXT | (39 << 2)), 39, 0, 0 }, /* supportedBandCombinationList-v1800 */
    { (ASN_TAG_CLASS_CONTEXT | (40 << 2)), 40, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1800 */
    { (ASN_TAG_CLASS_CONTEXT | (41 << 2)), 41, 0, 0 }, /* supportedBandCombinationList-v1830 */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 42, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1830 */
    { (ASN_TAG_CLASS_CONTEXT | (43 << 2)), 43, 0, 0 }, /* supportedBandCombinationList-v1840 */
    { (ASN_TAG_CLASS_CONTEXT | (44 << 2)), 44, 0, 0 }, /* supportedBandCombinationList-UplinkTxSwitch-v1840 */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 45, 0, 0 }, /* supportedBandCombinationList-v1860 */
    { (ASN_TAG_CLASS_CONTEXT | (46 << 2)), 46, 0, 0 } /* supportedBandCombinationList-UplinkTxSwitch-v1860 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_RF_ParametersMRDC_specs_1 = {
	sizeof(struct ASN_RRC_RF_ParametersMRDC),
	offsetof(struct ASN_RRC_RF_ParametersMRDC, _asn_ctx),
	asn_MAP_ASN_RRC_RF_ParametersMRDC_tag2el_1,
	47,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_RF_ParametersMRDC_oms_1,	/* Optional members */
	2, 45,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_RF_ParametersMRDC = {
	"RF-ParametersMRDC",
	"RF-ParametersMRDC",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1,
	sizeof(asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1)
		/sizeof(asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1)
		/sizeof(asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_RF_ParametersMRDC_1,
	47,	/* Elements count */
	&asn_SPC_ASN_RRC_RF_ParametersMRDC_specs_1	/* Additional specs */
};

