/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_FeatureSetUplink-v16d0.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_value2enum_3[] = {
	{ 0,	2,	"n2" },
	{ 1,	2,	"n3" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n7" },
	{ 4,	2,	"n8" },
	{ 5,	3,	"n12" }
};
static const unsigned int asn_MAP_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_enum2value_3[] = {
	5,	/* n12(5) */
	0,	/* n2(0) */
	1,	/* n3(1) */
	2,	/* n4(2) */
	3,	/* n7(3) */
	4	/* n8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_specs_3 = {
	asn_MAP_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_enum2value_3,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_3 = {
	"maxNumberPUSCH-Tx-Cap1-r16",
	"maxNumberPUSCH-Tx-Cap1-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_tags_3,
	sizeof(asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_tags_3)
		/sizeof(asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_tags_3[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_tags_3,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_tags_3)
		/sizeof(asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_value2enum_10[] = {
	{ 0,	2,	"n2" },
	{ 1,	2,	"n3" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n7" },
	{ 4,	2,	"n8" },
	{ 5,	3,	"n12" }
};
static const unsigned int asn_MAP_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_enum2value_10[] = {
	5,	/* n12(5) */
	0,	/* n2(0) */
	1,	/* n3(1) */
	2,	/* n4(2) */
	3,	/* n7(3) */
	4	/* n8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_specs_10 = {
	asn_MAP_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_enum2value_10,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_10 = {
	"maxNumberPUSCH-Tx-Cap2-r16",
	"maxNumberPUSCH-Tx-Cap2-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_tags_10,
	sizeof(asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_tags_10)
		/sizeof(asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_tags_10[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_tags_10,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_tags_10)
		/sizeof(asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_tags_10[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_pusch_RepetitionTypeB_v16d0_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_FeatureSetUplink_v16d0__pusch_RepetitionTypeB_v16d0, maxNumberPUSCH_Tx_Cap1_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap1_r16_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxNumberPUSCH-Tx-Cap1-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_FeatureSetUplink_v16d0__pusch_RepetitionTypeB_v16d0, maxNumberPUSCH_Tx_Cap2_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_maxNumberPUSCH_Tx_Cap2_r16_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxNumberPUSCH-Tx-Cap2-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_pusch_RepetitionTypeB_v16d0_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maxNumberPUSCH-Tx-Cap1-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* maxNumberPUSCH-Tx-Cap2-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_pusch_RepetitionTypeB_v16d0_specs_2 = {
	sizeof(struct ASN_RRC_FeatureSetUplink_v16d0__pusch_RepetitionTypeB_v16d0),
	offsetof(struct ASN_RRC_FeatureSetUplink_v16d0__pusch_RepetitionTypeB_v16d0, _asn_ctx),
	asn_MAP_ASN_RRC_pusch_RepetitionTypeB_v16d0_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_2 = {
	"pusch-RepetitionTypeB-v16d0",
	"pusch-RepetitionTypeB-v16d0",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_tags_2,
	sizeof(asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_tags_2)
		/sizeof(asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_tags_2[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_tags_2,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_tags_2)
		/sizeof(asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_pusch_RepetitionTypeB_v16d0_2,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_pusch_RepetitionTypeB_v16d0_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_FeatureSetUplink_v16d0_1[] = {
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_FeatureSetUplink_v16d0, pusch_RepetitionTypeB_v16d0),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ASN_RRC_pusch_RepetitionTypeB_v16d0_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-RepetitionTypeB-v16d0"
		},
};
static const int asn_MAP_ASN_RRC_FeatureSetUplink_v16d0_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_FeatureSetUplink_v16d0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_FeatureSetUplink_v16d0_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* pusch-RepetitionTypeB-v16d0 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_FeatureSetUplink_v16d0_specs_1 = {
	sizeof(struct ASN_RRC_FeatureSetUplink_v16d0),
	offsetof(struct ASN_RRC_FeatureSetUplink_v16d0, _asn_ctx),
	asn_MAP_ASN_RRC_FeatureSetUplink_v16d0_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_FeatureSetUplink_v16d0_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_FeatureSetUplink_v16d0 = {
	"FeatureSetUplink-v16d0",
	"FeatureSetUplink-v16d0",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_FeatureSetUplink_v16d0_tags_1,
	sizeof(asn_DEF_ASN_RRC_FeatureSetUplink_v16d0_tags_1)
		/sizeof(asn_DEF_ASN_RRC_FeatureSetUplink_v16d0_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_FeatureSetUplink_v16d0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_FeatureSetUplink_v16d0_tags_1)
		/sizeof(asn_DEF_ASN_RRC_FeatureSetUplink_v16d0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_FeatureSetUplink_v16d0_1,
	1,	/* Elements count */
	&asn_SPC_ASN_RRC_FeatureSetUplink_v16d0_specs_1	/* Additional specs */
};

