/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_SL_IndirectPathAddChange_r18_H_
#define	_ASN_RRC_SL_IndirectPathAddChange_r18_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_RRC_SL-SourceIdentity-r17.h"
#include "ASN_RRC_CellIdentity.h"
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18 {
	ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18_ms50	= 0,
	ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18_ms100	= 1,
	ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18_ms150	= 2,
	ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18_ms200	= 3,
	ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18_ms500	= 4,
	ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18_ms1000	= 5,
	ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18_ms2000	= 6,
	ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18_ms10000	= 7
} e_ASN_RRC_SL_IndirectPathAddChange_r18__t421_r18;

/* SL-IndirectPathAddChange-r18 */
typedef struct ASN_RRC_SL_IndirectPathAddChange_r18 {
	ASN_RRC_SL_SourceIdentity_r17_t	 sl_IndirectPathRelayUE_Identity_r18;
	ASN_RRC_CellIdentity_t	 sl_IndirectPathCellIdentity_r18;
	long	*t421_r18	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SL_IndirectPathAddChange_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_t421_r18_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SL_IndirectPathAddChange_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SL_IndirectPathAddChange_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SL_IndirectPathAddChange_r18_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SL_IndirectPathAddChange_r18_H_ */
#include "../asn1c/asn_internal.h"
