/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_PeriodicalReportConfig_H_
#define	_ASN_RRC_PeriodicalReportConfig_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_RRC_NR-RS-Type.h"
#include "ASN_RRC_ReportInterval.h"
#include "../asn1c/NativeEnumerated.h"
#include "ASN_RRC_MeasReportQuantity.h"
#include "../asn1c/NativeInteger.h"
#include "../asn1c/BOOLEAN.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_PeriodicalReportConfig__reportAmount {
	ASN_RRC_PeriodicalReportConfig__reportAmount_r1	= 0,
	ASN_RRC_PeriodicalReportConfig__reportAmount_r2	= 1,
	ASN_RRC_PeriodicalReportConfig__reportAmount_r4	= 2,
	ASN_RRC_PeriodicalReportConfig__reportAmount_r8	= 3,
	ASN_RRC_PeriodicalReportConfig__reportAmount_r16	= 4,
	ASN_RRC_PeriodicalReportConfig__reportAmount_r32	= 5,
	ASN_RRC_PeriodicalReportConfig__reportAmount_r64	= 6,
	ASN_RRC_PeriodicalReportConfig__reportAmount_infinity	= 7
} e_ASN_RRC_PeriodicalReportConfig__reportAmount;
typedef enum ASN_RRC_PeriodicalReportConfig__includeCommonLocationInfo_r16 {
	ASN_RRC_PeriodicalReportConfig__includeCommonLocationInfo_r16_true	= 0
} e_ASN_RRC_PeriodicalReportConfig__includeCommonLocationInfo_r16;
typedef enum ASN_RRC_PeriodicalReportConfig__reportAddNeighMeas_r16 {
	ASN_RRC_PeriodicalReportConfig__reportAddNeighMeas_r16_setup	= 0
} e_ASN_RRC_PeriodicalReportConfig__reportAddNeighMeas_r16;
typedef enum ASN_RRC_PeriodicalReportConfig__coarseLocationRequest_r17 {
	ASN_RRC_PeriodicalReportConfig__coarseLocationRequest_r17_true	= 0
} e_ASN_RRC_PeriodicalReportConfig__coarseLocationRequest_r17;

/* Forward declarations */
struct ASN_RRC_MeasReportQuantity;
struct ASN_RRC_MeasRSSI_ReportConfig_r16;
struct ASN_RRC_SetupRelease_3430P1;
struct ASN_RRC_SetupRelease_3430P2;
struct ASN_RRC_SetupRelease_3430P3;
struct ASN_RRC_SetupRelease_3430P183;
struct ASN_RRC_SetupRelease_3430P184;
struct ASN_RRC_SL_MeasReportQuantity_r16;

/* PeriodicalReportConfig */
typedef struct ASN_RRC_PeriodicalReportConfig {
	ASN_RRC_NR_RS_Type_t	 rsType;
	ASN_RRC_ReportInterval_t	 reportInterval;
	long	 reportAmount;
	ASN_RRC_MeasReportQuantity_t	 reportQuantityCell;
	long	 maxReportCells;
	struct ASN_RRC_MeasReportQuantity	*reportQuantityRS_Indexes	/* OPTIONAL */;
	long	*maxNrofRS_IndexesToReport	/* OPTIONAL */;
	BOOLEAN_t	 includeBeamMeasurements;
	BOOLEAN_t	 useAllowedCellList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct ASN_RRC_MeasRSSI_ReportConfig_r16	*measRSSI_ReportConfig_r16	/* OPTIONAL */;
	long	*includeCommonLocationInfo_r16	/* OPTIONAL */;
	struct ASN_RRC_SetupRelease_3430P1	*includeBT_Meas_r16	/* OPTIONAL */;
	struct ASN_RRC_SetupRelease_3430P2	*includeWLAN_Meas_r16	/* OPTIONAL */;
	struct ASN_RRC_SetupRelease_3430P3	*includeSensor_Meas_r16	/* OPTIONAL */;
	struct ASN_RRC_SetupRelease_3430P183	*ul_DelayValueConfig_r16	/* OPTIONAL */;
	long	*reportAddNeighMeas_r16	/* OPTIONAL */;
	struct ASN_RRC_SetupRelease_3430P184	*ul_ExcessDelayConfig_r17	/* OPTIONAL */;
	long	*coarseLocationRequest_r17	/* OPTIONAL */;
	struct ASN_RRC_SL_MeasReportQuantity_r16	*reportQuantityRelay_r17	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_PeriodicalReportConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_reportAmount_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_includeCommonLocationInfo_r16_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_reportAddNeighMeas_r16_27;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_coarseLocationRequest_r17_30;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_PeriodicalReportConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_PeriodicalReportConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_PeriodicalReportConfig_1[19];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_PeriodicalReportConfig_H_ */
#include "../asn1c/asn_internal.h"
