/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_CrossCarrierSchedulingConfig.h"

static int
memb_ASN_RRC_cif_InSchedulingCell_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_carrierIndicatorSizeDCI_1_2_r16_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_carrierIndicatorSizeDCI_0_2_r16_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_memb_ASN_RRC_cif_InSchedulingCell_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (1..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_schedulingCellInfo_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_carrierIndicatorSizeDCI_1_2_r16_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_carrierIndicatorSizeDCI_0_2_r16_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_enableDefaultBeamForCCS_r16_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_ccs_BlindDetectionSplit_r17_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_own_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo__own, cif_Presence),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cif-Presence"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_own_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_own_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* cif-Presence */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_own_specs_3 = {
	sizeof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo__own),
	offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo__own, _asn_ctx),
	asn_MAP_ASN_RRC_own_tag2el_3,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_own_3 = {
	"own",
	"own",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_own_tags_3,
	sizeof(asn_DEF_ASN_RRC_own_tags_3)
		/sizeof(asn_DEF_ASN_RRC_own_tags_3[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_own_tags_3,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_own_tags_3)
		/sizeof(asn_DEF_ASN_RRC_own_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_own_3,
	1,	/* Elements count */
	&asn_SPC_ASN_RRC_own_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_other_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo__other, schedulingCellId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_ServCellIndex,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"schedulingCellId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo__other, cif_InSchedulingCell),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_cif_InSchedulingCell_constr_7,  memb_ASN_RRC_cif_InSchedulingCell_constraint_5 },
		0, 0, /* No default value */
		"cif-InSchedulingCell"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_other_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_other_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* schedulingCellId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cif-InSchedulingCell */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_other_specs_5 = {
	sizeof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo__other),
	offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo__other, _asn_ctx),
	asn_MAP_ASN_RRC_other_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_other_5 = {
	"other",
	"other",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_other_tags_5,
	sizeof(asn_DEF_ASN_RRC_other_tags_5)
		/sizeof(asn_DEF_ASN_RRC_other_tags_5[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_other_tags_5,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_other_tags_5)
		/sizeof(asn_DEF_ASN_RRC_other_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_other_5,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_other_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_schedulingCellInfo_2[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo, choice.own),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ASN_RRC_own_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"own"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo, choice.other),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ASN_RRC_other_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"other"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_schedulingCellInfo_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* own */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* other */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_schedulingCellInfo_specs_2 = {
	sizeof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo),
	offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo, _asn_ctx),
	offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo, present),
	sizeof(((struct ASN_RRC_CrossCarrierSchedulingConfig__schedulingCellInfo *)0)->present),
	asn_MAP_ASN_RRC_schedulingCellInfo_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_schedulingCellInfo_2 = {
	"schedulingCellInfo",
	"schedulingCellInfo",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_schedulingCellInfo_constr_2, CHOICE_constraint },
	asn_MBR_ASN_RRC_schedulingCellInfo_2,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_schedulingCellInfo_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_carrierIndicatorSize_r16_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__carrierIndicatorSize_r16, carrierIndicatorSizeDCI_1_2_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_carrierIndicatorSizeDCI_1_2_r16_constr_10,  memb_ASN_RRC_carrierIndicatorSizeDCI_1_2_r16_constraint_9 },
		0, 0, /* No default value */
		"carrierIndicatorSizeDCI-1-2-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__carrierIndicatorSize_r16, carrierIndicatorSizeDCI_0_2_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_carrierIndicatorSizeDCI_0_2_r16_constr_11,  memb_ASN_RRC_carrierIndicatorSizeDCI_0_2_r16_constraint_9 },
		0, 0, /* No default value */
		"carrierIndicatorSizeDCI-0-2-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_carrierIndicatorSize_r16_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_carrierIndicatorSize_r16_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* carrierIndicatorSizeDCI-1-2-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* carrierIndicatorSizeDCI-0-2-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_carrierIndicatorSize_r16_specs_9 = {
	sizeof(struct ASN_RRC_CrossCarrierSchedulingConfig__carrierIndicatorSize_r16),
	offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig__carrierIndicatorSize_r16, _asn_ctx),
	asn_MAP_ASN_RRC_carrierIndicatorSize_r16_tag2el_9,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_carrierIndicatorSize_r16_9 = {
	"carrierIndicatorSize-r16",
	"carrierIndicatorSize-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_carrierIndicatorSize_r16_tags_9,
	sizeof(asn_DEF_ASN_RRC_carrierIndicatorSize_r16_tags_9)
		/sizeof(asn_DEF_ASN_RRC_carrierIndicatorSize_r16_tags_9[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_carrierIndicatorSize_r16_tags_9,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_carrierIndicatorSize_r16_tags_9)
		/sizeof(asn_DEF_ASN_RRC_carrierIndicatorSize_r16_tags_9[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_carrierIndicatorSize_r16_9,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_carrierIndicatorSize_r16_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_enableDefaultBeamForCCS_r16_value2enum_12[] = {
	{ 0,	7,	"enabled" }
};
static const unsigned int asn_MAP_ASN_RRC_enableDefaultBeamForCCS_r16_enum2value_12[] = {
	0	/* enabled(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_enableDefaultBeamForCCS_r16_specs_12 = {
	asn_MAP_ASN_RRC_enableDefaultBeamForCCS_r16_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_enableDefaultBeamForCCS_r16_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_12 = {
	"enableDefaultBeamForCCS-r16",
	"enableDefaultBeamForCCS-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_tags_12,
	sizeof(asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_tags_12)
		/sizeof(asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_tags_12[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_tags_12,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_tags_12)
		/sizeof(asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_tags_12[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_enableDefaultBeamForCCS_r16_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_enableDefaultBeamForCCS_r16_specs_12	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_ccs_BlindDetectionSplit_r17_value2enum_14[] = {
	{ 0,	10,	"oneSeventh" },
	{ 1,	15,	"threeFourteenth" },
	{ 2,	10,	"twoSeventh" },
	{ 3,	12,	"threeSeventh" },
	{ 4,	7,	"oneHalf" },
	{ 5,	11,	"fourSeventh" },
	{ 6,	11,	"fiveSeventh" },
	{ 7,	6,	"spare1" }
};
static const unsigned int asn_MAP_ASN_RRC_ccs_BlindDetectionSplit_r17_enum2value_14[] = {
	6,	/* fiveSeventh(6) */
	5,	/* fourSeventh(5) */
	4,	/* oneHalf(4) */
	0,	/* oneSeventh(0) */
	7,	/* spare1(7) */
	1,	/* threeFourteenth(1) */
	3,	/* threeSeventh(3) */
	2	/* twoSeventh(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_ccs_BlindDetectionSplit_r17_specs_14 = {
	asn_MAP_ASN_RRC_ccs_BlindDetectionSplit_r17_value2enum_14,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_ccs_BlindDetectionSplit_r17_enum2value_14,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_14 = {
	"ccs-BlindDetectionSplit-r17",
	"ccs-BlindDetectionSplit-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_tags_14,
	sizeof(asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_tags_14)
		/sizeof(asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_tags_14[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_tags_14,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_tags_14)
		/sizeof(asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_tags_14[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_ccs_BlindDetectionSplit_r17_constr_14, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_ccs_BlindDetectionSplit_r17_specs_14	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_CrossCarrierSchedulingConfig_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig, schedulingCellInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_schedulingCellInfo_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"schedulingCellInfo"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig, carrierIndicatorSize_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ASN_RRC_carrierIndicatorSize_r16_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"carrierIndicatorSize-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig, enableDefaultBeamForCCS_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_enableDefaultBeamForCCS_r16_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enableDefaultBeamForCCS-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig, ccs_BlindDetectionSplit_r17),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_ccs_BlindDetectionSplit_r17_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ccs-BlindDetectionSplit-r17"
		},
};
static const int asn_MAP_ASN_RRC_CrossCarrierSchedulingConfig_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_CrossCarrierSchedulingConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_CrossCarrierSchedulingConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* schedulingCellInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* carrierIndicatorSize-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* enableDefaultBeamForCCS-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ccs-BlindDetectionSplit-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_CrossCarrierSchedulingConfig_specs_1 = {
	sizeof(struct ASN_RRC_CrossCarrierSchedulingConfig),
	offsetof(struct ASN_RRC_CrossCarrierSchedulingConfig, _asn_ctx),
	asn_MAP_ASN_RRC_CrossCarrierSchedulingConfig_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_CrossCarrierSchedulingConfig_oms_1,	/* Optional members */
	0, 3,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_CrossCarrierSchedulingConfig = {
	"CrossCarrierSchedulingConfig",
	"CrossCarrierSchedulingConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_CrossCarrierSchedulingConfig_tags_1,
	sizeof(asn_DEF_ASN_RRC_CrossCarrierSchedulingConfig_tags_1)
		/sizeof(asn_DEF_ASN_RRC_CrossCarrierSchedulingConfig_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_CrossCarrierSchedulingConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_CrossCarrierSchedulingConfig_tags_1)
		/sizeof(asn_DEF_ASN_RRC_CrossCarrierSchedulingConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_CrossCarrierSchedulingConfig_1,
	4,	/* Elements count */
	&asn_SPC_ASN_RRC_CrossCarrierSchedulingConfig_specs_1	/* Additional specs */
};

