/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_MSD-Information-r18.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_ASN_RRC_msd_Type_r18_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_msd_PowerClass_r18_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_msd_Class_r18_constr_23 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_msd_Type_r18_value2enum_2[] = {
	{ 0,	8,	"harmonic" },
	{ 1,	14,	"harmonicMixing" },
	{ 2,	18,	"crossBandIsolation" },
	{ 3,	4,	"imd2" },
	{ 4,	4,	"imd3" },
	{ 5,	4,	"imd4" },
	{ 6,	4,	"imd5" },
	{ 7,	3,	"all" },
	{ 8,	6,	"spare8" },
	{ 9,	6,	"spare7" },
	{ 10,	6,	"spare6" },
	{ 11,	6,	"spare5" },
	{ 12,	6,	"spare4" },
	{ 13,	6,	"spare3" },
	{ 14,	6,	"spare2" },
	{ 15,	6,	"spare1" }
};
static const unsigned int asn_MAP_ASN_RRC_msd_Type_r18_enum2value_2[] = {
	7,	/* all(7) */
	2,	/* crossBandIsolation(2) */
	0,	/* harmonic(0) */
	1,	/* harmonicMixing(1) */
	3,	/* imd2(3) */
	4,	/* imd3(4) */
	5,	/* imd4(5) */
	6,	/* imd5(6) */
	15,	/* spare1(15) */
	14,	/* spare2(14) */
	13,	/* spare3(13) */
	12,	/* spare4(12) */
	11,	/* spare5(11) */
	10,	/* spare6(10) */
	9,	/* spare7(9) */
	8	/* spare8(8) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_msd_Type_r18_specs_2 = {
	asn_MAP_ASN_RRC_msd_Type_r18_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_msd_Type_r18_enum2value_2,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_msd_Type_r18_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_msd_Type_r18_2 = {
	"msd-Type-r18",
	"msd-Type-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_msd_Type_r18_tags_2,
	sizeof(asn_DEF_ASN_RRC_msd_Type_r18_tags_2)
		/sizeof(asn_DEF_ASN_RRC_msd_Type_r18_tags_2[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_msd_Type_r18_tags_2,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_msd_Type_r18_tags_2)
		/sizeof(asn_DEF_ASN_RRC_msd_Type_r18_tags_2[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_msd_Type_r18_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_msd_Type_r18_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_msd_PowerClass_r18_value2enum_19[] = {
	{ 0,	7,	"pc1dot5" },
	{ 1,	3,	"pc2" },
	{ 2,	3,	"pc3" }
};
static const unsigned int asn_MAP_ASN_RRC_msd_PowerClass_r18_enum2value_19[] = {
	0,	/* pc1dot5(0) */
	1,	/* pc2(1) */
	2	/* pc3(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_msd_PowerClass_r18_specs_19 = {
	asn_MAP_ASN_RRC_msd_PowerClass_r18_value2enum_19,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_msd_PowerClass_r18_enum2value_19,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_msd_PowerClass_r18_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_msd_PowerClass_r18_19 = {
	"msd-PowerClass-r18",
	"msd-PowerClass-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_msd_PowerClass_r18_tags_19,
	sizeof(asn_DEF_ASN_RRC_msd_PowerClass_r18_tags_19)
		/sizeof(asn_DEF_ASN_RRC_msd_PowerClass_r18_tags_19[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_msd_PowerClass_r18_tags_19,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_msd_PowerClass_r18_tags_19)
		/sizeof(asn_DEF_ASN_RRC_msd_PowerClass_r18_tags_19[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_msd_PowerClass_r18_constr_19, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_msd_PowerClass_r18_specs_19	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_msd_Class_r18_value2enum_23[] = {
	{ 0,	6,	"classI" },
	{ 1,	7,	"classII" },
	{ 2,	8,	"classIII" },
	{ 3,	7,	"classIV" },
	{ 4,	6,	"classV" },
	{ 5,	7,	"classVI" },
	{ 6,	8,	"classVII" },
	{ 7,	9,	"classVIII" }
};
static const unsigned int asn_MAP_ASN_RRC_msd_Class_r18_enum2value_23[] = {
	0,	/* classI(0) */
	1,	/* classII(1) */
	2,	/* classIII(2) */
	3,	/* classIV(3) */
	4,	/* classV(4) */
	5,	/* classVI(5) */
	6,	/* classVII(6) */
	7	/* classVIII(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_msd_Class_r18_specs_23 = {
	asn_MAP_ASN_RRC_msd_Class_r18_value2enum_23,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_msd_Class_r18_enum2value_23,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_msd_Class_r18_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_msd_Class_r18_23 = {
	"msd-Class-r18",
	"msd-Class-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_msd_Class_r18_tags_23,
	sizeof(asn_DEF_ASN_RRC_msd_Class_r18_tags_23)
		/sizeof(asn_DEF_ASN_RRC_msd_Class_r18_tags_23[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_msd_Class_r18_tags_23,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_msd_Class_r18_tags_23)
		/sizeof(asn_DEF_ASN_RRC_msd_Class_r18_tags_23[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_msd_Class_r18_constr_23, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_msd_Class_r18_specs_23	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_MSD_Information_r18_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_MSD_Information_r18, msd_Type_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_msd_Type_r18_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"msd-Type-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_MSD_Information_r18, msd_PowerClass_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_msd_PowerClass_r18_19,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"msd-PowerClass-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_MSD_Information_r18, msd_Class_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_msd_Class_r18_23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"msd-Class-r18"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_MSD_Information_r18_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_MSD_Information_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msd-Type-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* msd-PowerClass-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* msd-Class-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_MSD_Information_r18_specs_1 = {
	sizeof(struct ASN_RRC_MSD_Information_r18),
	offsetof(struct ASN_RRC_MSD_Information_r18, _asn_ctx),
	asn_MAP_ASN_RRC_MSD_Information_r18_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_MSD_Information_r18 = {
	"MSD-Information-r18",
	"MSD-Information-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_MSD_Information_r18_tags_1,
	sizeof(asn_DEF_ASN_RRC_MSD_Information_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_MSD_Information_r18_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_MSD_Information_r18_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_MSD_Information_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_MSD_Information_r18_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_MSD_Information_r18_1,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_MSD_Information_r18_specs_1	/* Additional specs */
};

