/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18_H_
#define	_ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_RRC_SRS-PosResourceSetId-r16.h"
#include "ASN_RRC_ServingCellAndBWP-Id-r17.h"
#include "../asn1c/constr_SEQUENCE.h"
#include "ASN_RRC_SCS-SpecificCarrier.h"
#include "ASN_RRC_ARFCN-ValueNR.h"
#include "../asn1c/constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18_PR {
	ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18_PR_NOTHING,	/* No components present */
	ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18_PR_rrc_connectedState_r18,
	ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18_PR_rrc_inactiveState_r18
} ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18_PR;

/* SRS-PosResourceSetLinkedForAggBW-r18 */
typedef struct ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18 {
	ASN_RRC_SRS_PosResourceSetId_r16_t	 srs_PosResourceSetLinked_r18;
	struct ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18 {
		ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18_PR present;
		union ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18_u {
			struct ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18__rrc_connectedState_r18 {
				ASN_RRC_ServingCellAndBWP_Id_r17_t	 servingCellAndBWP_Id_r18;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *rrc_connectedState_r18;
			struct ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18__srs_LinkedConfig_r18__rrc_inactiveState_r18 {
				ASN_RRC_SCS_SpecificCarrier_t	 scs_SpecificCarrier_r18;
				ASN_RRC_ARFCN_ValueNR_t	 freqInfo_r18;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *rrc_inactiveState_r18;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} srs_LinkedConfig_r18;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SRS_PosResourceSetLinkedForAggBW_r18_H_ */
#include "../asn1c/asn_internal.h"
