/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_AerialParameters-r18.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_ASN_RRC_aerialUE_Capability_r18_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_altitudeMeas_r18_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_eventAxHy_r18_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_flightPathReporting_r18_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_multipleCellsMeasExtension_r18_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_nr_NS_PmaxListAerial_r18_constr_16 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_sl_A2X_Service_r18_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aerialUE_Capability_r18_value2enum_2[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_aerialUE_Capability_r18_enum2value_2[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aerialUE_Capability_r18_specs_2 = {
	asn_MAP_ASN_RRC_aerialUE_Capability_r18_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aerialUE_Capability_r18_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aerialUE_Capability_r18_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aerialUE_Capability_r18_2 = {
	"aerialUE-Capability-r18",
	"aerialUE-Capability-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aerialUE_Capability_r18_tags_2,
	sizeof(asn_DEF_ASN_RRC_aerialUE_Capability_r18_tags_2)
		/sizeof(asn_DEF_ASN_RRC_aerialUE_Capability_r18_tags_2[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aerialUE_Capability_r18_tags_2,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aerialUE_Capability_r18_tags_2)
		/sizeof(asn_DEF_ASN_RRC_aerialUE_Capability_r18_tags_2[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aerialUE_Capability_r18_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aerialUE_Capability_r18_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_altitudeMeas_r18_value2enum_4[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_altitudeMeas_r18_enum2value_4[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_altitudeMeas_r18_specs_4 = {
	asn_MAP_ASN_RRC_altitudeMeas_r18_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_altitudeMeas_r18_enum2value_4,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_altitudeMeas_r18_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_altitudeMeas_r18_4 = {
	"altitudeMeas-r18",
	"altitudeMeas-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_altitudeMeas_r18_tags_4,
	sizeof(asn_DEF_ASN_RRC_altitudeMeas_r18_tags_4)
		/sizeof(asn_DEF_ASN_RRC_altitudeMeas_r18_tags_4[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_altitudeMeas_r18_tags_4,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_altitudeMeas_r18_tags_4)
		/sizeof(asn_DEF_ASN_RRC_altitudeMeas_r18_tags_4[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_altitudeMeas_r18_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_altitudeMeas_r18_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_value2enum_6[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_enum2value_6[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_specs_6 = {
	asn_MAP_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_enum2value_6,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_6 = {
	"altitudeBasedSSB-ToMeasure-r18",
	"altitudeBasedSSB-ToMeasure-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_tags_6,
	sizeof(asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_tags_6)
		/sizeof(asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_tags_6[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_tags_6,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_tags_6)
		/sizeof(asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_tags_6[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_constr_6, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_specs_6	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_eventAxHy_r18_value2enum_8[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_eventAxHy_r18_enum2value_8[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_eventAxHy_r18_specs_8 = {
	asn_MAP_ASN_RRC_eventAxHy_r18_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_eventAxHy_r18_enum2value_8,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_eventAxHy_r18_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_eventAxHy_r18_8 = {
	"eventAxHy-r18",
	"eventAxHy-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_eventAxHy_r18_tags_8,
	sizeof(asn_DEF_ASN_RRC_eventAxHy_r18_tags_8)
		/sizeof(asn_DEF_ASN_RRC_eventAxHy_r18_tags_8[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_eventAxHy_r18_tags_8,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_eventAxHy_r18_tags_8)
		/sizeof(asn_DEF_ASN_RRC_eventAxHy_r18_tags_8[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_eventAxHy_r18_constr_8, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_eventAxHy_r18_specs_8	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_flightPathReporting_r18_value2enum_10[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_flightPathReporting_r18_enum2value_10[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_flightPathReporting_r18_specs_10 = {
	asn_MAP_ASN_RRC_flightPathReporting_r18_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_flightPathReporting_r18_enum2value_10,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_flightPathReporting_r18_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_flightPathReporting_r18_10 = {
	"flightPathReporting-r18",
	"flightPathReporting-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_flightPathReporting_r18_tags_10,
	sizeof(asn_DEF_ASN_RRC_flightPathReporting_r18_tags_10)
		/sizeof(asn_DEF_ASN_RRC_flightPathReporting_r18_tags_10[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_flightPathReporting_r18_tags_10,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_flightPathReporting_r18_tags_10)
		/sizeof(asn_DEF_ASN_RRC_flightPathReporting_r18_tags_10[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_flightPathReporting_r18_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_flightPathReporting_r18_specs_10	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_value2enum_12[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_enum2value_12[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_specs_12 = {
	asn_MAP_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_12 = {
	"flightPathAvailabilityIndicationUAI-r18",
	"flightPathAvailabilityIndicationUAI-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_tags_12,
	sizeof(asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_tags_12)
		/sizeof(asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_tags_12[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_tags_12,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_tags_12)
		/sizeof(asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_tags_12[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_specs_12	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_multipleCellsMeasExtension_r18_value2enum_14[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_multipleCellsMeasExtension_r18_enum2value_14[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_multipleCellsMeasExtension_r18_specs_14 = {
	asn_MAP_ASN_RRC_multipleCellsMeasExtension_r18_value2enum_14,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_multipleCellsMeasExtension_r18_enum2value_14,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_14 = {
	"multipleCellsMeasExtension-r18",
	"multipleCellsMeasExtension-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_tags_14,
	sizeof(asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_tags_14)
		/sizeof(asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_tags_14[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_tags_14,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_tags_14)
		/sizeof(asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_tags_14[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_multipleCellsMeasExtension_r18_constr_14, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_multipleCellsMeasExtension_r18_specs_14	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_nr_NS_PmaxListAerial_r18_value2enum_16[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_nr_NS_PmaxListAerial_r18_enum2value_16[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_nr_NS_PmaxListAerial_r18_specs_16 = {
	asn_MAP_ASN_RRC_nr_NS_PmaxListAerial_r18_value2enum_16,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_nr_NS_PmaxListAerial_r18_enum2value_16,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_16 = {
	"nr-NS-PmaxListAerial-r18",
	"nr-NS-PmaxListAerial-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_tags_16,
	sizeof(asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_tags_16)
		/sizeof(asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_tags_16[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_tags_16,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_tags_16)
		/sizeof(asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_tags_16[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_nr_NS_PmaxListAerial_r18_constr_16, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_nr_NS_PmaxListAerial_r18_specs_16	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_value2enum_18[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_enum2value_18[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_specs_18 = {
	asn_MAP_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_value2enum_18,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_enum2value_18,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_18 = {
	"simulMultiTriggerSingleMeasReport-r18",
	"simulMultiTriggerSingleMeasReport-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_tags_18,
	sizeof(asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_tags_18)
		/sizeof(asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_tags_18[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_tags_18,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_tags_18)
		/sizeof(asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_tags_18[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_constr_18, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_sl_A2X_Service_r18_value2enum_20[] = {
	{ 0,	4,	"brid" },
	{ 1,	3,	"daa" },
	{ 2,	10,	"bridAndDAA" }
};
static const unsigned int asn_MAP_ASN_RRC_sl_A2X_Service_r18_enum2value_20[] = {
	0,	/* brid(0) */
	2,	/* bridAndDAA(2) */
	1	/* daa(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_sl_A2X_Service_r18_specs_20 = {
	asn_MAP_ASN_RRC_sl_A2X_Service_r18_value2enum_20,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_sl_A2X_Service_r18_enum2value_20,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_sl_A2X_Service_r18_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_sl_A2X_Service_r18_20 = {
	"sl-A2X-Service-r18",
	"sl-A2X-Service-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_sl_A2X_Service_r18_tags_20,
	sizeof(asn_DEF_ASN_RRC_sl_A2X_Service_r18_tags_20)
		/sizeof(asn_DEF_ASN_RRC_sl_A2X_Service_r18_tags_20[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_sl_A2X_Service_r18_tags_20,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_sl_A2X_Service_r18_tags_20)
		/sizeof(asn_DEF_ASN_RRC_sl_A2X_Service_r18_tags_20[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_sl_A2X_Service_r18_constr_20, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_sl_A2X_Service_r18_specs_20	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_AerialParameters_r18_1[] = {
	{ ATF_POINTER, 10, offsetof(struct ASN_RRC_AerialParameters_r18, aerialUE_Capability_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aerialUE_Capability_r18_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aerialUE-Capability-r18"
		},
	{ ATF_POINTER, 9, offsetof(struct ASN_RRC_AerialParameters_r18, altitudeMeas_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_altitudeMeas_r18_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"altitudeMeas-r18"
		},
	{ ATF_POINTER, 8, offsetof(struct ASN_RRC_AerialParameters_r18, altitudeBasedSSB_ToMeasure_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_altitudeBasedSSB_ToMeasure_r18_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"altitudeBasedSSB-ToMeasure-r18"
		},
	{ ATF_POINTER, 7, offsetof(struct ASN_RRC_AerialParameters_r18, eventAxHy_r18),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_eventAxHy_r18_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventAxHy-r18"
		},
	{ ATF_POINTER, 6, offsetof(struct ASN_RRC_AerialParameters_r18, flightPathReporting_r18),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_flightPathReporting_r18_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"flightPathReporting-r18"
		},
	{ ATF_POINTER, 5, offsetof(struct ASN_RRC_AerialParameters_r18, flightPathAvailabilityIndicationUAI_r18),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_flightPathAvailabilityIndicationUAI_r18_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"flightPathAvailabilityIndicationUAI-r18"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_AerialParameters_r18, multipleCellsMeasExtension_r18),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_multipleCellsMeasExtension_r18_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"multipleCellsMeasExtension-r18"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_AerialParameters_r18, nr_NS_PmaxListAerial_r18),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_nr_NS_PmaxListAerial_r18_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-NS-PmaxListAerial-r18"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_AerialParameters_r18, simulMultiTriggerSingleMeasReport_r18),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_simulMultiTriggerSingleMeasReport_r18_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"simulMultiTriggerSingleMeasReport-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_AerialParameters_r18, sl_A2X_Service_r18),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_sl_A2X_Service_r18_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-A2X-Service-r18"
		},
};
static const int asn_MAP_ASN_RRC_AerialParameters_r18_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_AerialParameters_r18_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_AerialParameters_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aerialUE-Capability-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* altitudeMeas-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* altitudeBasedSSB-ToMeasure-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* eventAxHy-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* flightPathReporting-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* flightPathAvailabilityIndicationUAI-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* multipleCellsMeasExtension-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* nr-NS-PmaxListAerial-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* simulMultiTriggerSingleMeasReport-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* sl-A2X-Service-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_AerialParameters_r18_specs_1 = {
	sizeof(struct ASN_RRC_AerialParameters_r18),
	offsetof(struct ASN_RRC_AerialParameters_r18, _asn_ctx),
	asn_MAP_ASN_RRC_AerialParameters_r18_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_AerialParameters_r18_oms_1,	/* Optional members */
	10, 0,	/* Root/Additions */
	10,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_AerialParameters_r18 = {
	"AerialParameters-r18",
	"AerialParameters-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_AerialParameters_r18_tags_1,
	sizeof(asn_DEF_ASN_RRC_AerialParameters_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_AerialParameters_r18_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_AerialParameters_r18_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_AerialParameters_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_AerialParameters_r18_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_AerialParameters_r18_1,
	10,	/* Elements count */
	&asn_SPC_ASN_RRC_AerialParameters_r18_specs_1	/* Additional specs */
};

