/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_ExtendedPagingCycleConfig_r18_H_
#define	_ASN_RRC_ExtendedPagingCycleConfig_r18_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18 {
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf2	= 0,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf4	= 1,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf8	= 2,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf16	= 3,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf32	= 4,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf64	= 5,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf128	= 6,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf256	= 7,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf512	= 8,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_hf1024	= 9,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_spare6	= 10,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_spare5	= 11,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_spare4	= 12,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_spare3	= 13,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_spare2	= 14,
	ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18_spare1	= 15
} e_ASN_RRC_ExtendedPagingCycleConfig_r18__extendedPagingCycle_r18;
typedef enum ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18 {
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms1280	= 0,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms2560	= 1,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms3840	= 2,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms5120	= 3,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms6400	= 4,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms7680	= 5,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms8960	= 6,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms10240	= 7,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms11520	= 8,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms12800	= 9,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms14080	= 10,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms15360	= 11,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms16640	= 12,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms17920	= 13,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms19200	= 14,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms20480	= 15,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms21760	= 16,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms23040	= 17,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms24320	= 18,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms25600	= 19,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms26880	= 20,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms28160	= 21,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms29440	= 22,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms30720	= 23,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms32000	= 24,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms33280	= 25,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms34560	= 26,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms35840	= 27,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms37120	= 28,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms38400	= 29,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms39680	= 30,
	ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18_ms40960	= 31
} e_ASN_RRC_ExtendedPagingCycleConfig_r18__pagingPTWLength_r18;

/* ExtendedPagingCycleConfig-r18 */
typedef struct ASN_RRC_ExtendedPagingCycleConfig_r18 {
	long	 extendedPagingCycle_r18;
	long	 pagingPTWLength_r18;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_ExtendedPagingCycleConfig_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_extendedPagingCycle_r18_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_pagingPTWLength_r18_19;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ExtendedPagingCycleConfig_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_ExtendedPagingCycleConfig_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_ExtendedPagingCycleConfig_r18_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_ExtendedPagingCycleConfig_r18_H_ */
#include "../asn1c/asn_internal.h"
