/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_MeasWindowConfig_r18_H_
#define	_ASN_RRC_MeasWindowConfig_r18_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/NativeInteger.h"
#include "../asn1c/constr_CHOICE.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_MeasWindowConfig_r18__windowOffsetPeriodicity_r18_PR {
	ASN_RRC_MeasWindowConfig_r18__windowOffsetPeriodicity_r18_PR_NOTHING,	/* No components present */
	ASN_RRC_MeasWindowConfig_r18__windowOffsetPeriodicity_r18_PR_periodicityMs40_r18,
	ASN_RRC_MeasWindowConfig_r18__windowOffsetPeriodicity_r18_PR_periodicityMs80_r18
	/* Extensions may appear below */
	
} ASN_RRC_MeasWindowConfig_r18__windowOffsetPeriodicity_r18_PR;
typedef enum ASN_RRC_MeasWindowConfig_r18__windowDuration_r18 {
	ASN_RRC_MeasWindowConfig_r18__windowDuration_r18_ms2	= 0,
	ASN_RRC_MeasWindowConfig_r18__windowDuration_r18_ms5	= 1,
	ASN_RRC_MeasWindowConfig_r18__windowDuration_r18_ms5dot5	= 2,
	ASN_RRC_MeasWindowConfig_r18__windowDuration_r18_spare1	= 3
} e_ASN_RRC_MeasWindowConfig_r18__windowDuration_r18;

/* MeasWindowConfig-r18 */
typedef struct ASN_RRC_MeasWindowConfig_r18 {
	struct ASN_RRC_MeasWindowConfig_r18__windowOffsetPeriodicity_r18 {
		ASN_RRC_MeasWindowConfig_r18__windowOffsetPeriodicity_r18_PR present;
		union ASN_RRC_MeasWindowConfig_r18__windowOffsetPeriodicity_r18_u {
			long	 periodicityMs40_r18;
			long	 periodicityMs80_r18;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} windowOffsetPeriodicity_r18;
	long	 windowDuration_r18;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_MeasWindowConfig_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_windowDuration_r18_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_MeasWindowConfig_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_MeasWindowConfig_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_MeasWindowConfig_r18_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_MeasWindowConfig_r18_H_ */
#include "../asn1c/asn_internal.h"
