/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_UE-MRDC-Capability-v15g0.h"

#include "ASN_RRC_RF-ParametersMRDC-v15g0.h"
#include "ASN_RRC_UE-MRDC-Capability-v15n0.h"
static asn_TYPE_member_t asn_MBR_ASN_RRC_UE_MRDC_Capability_v15g0_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_UE_MRDC_Capability_v15g0, rf_ParametersMRDC_v15g0),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_RF_ParametersMRDC_v15g0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rf-ParametersMRDC-v15g0"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_UE_MRDC_Capability_v15g0, nonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_UE_MRDC_Capability_v15n0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtension"
		},
};
static const int asn_MAP_ASN_RRC_UE_MRDC_Capability_v15g0_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_UE_MRDC_Capability_v15g0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_UE_MRDC_Capability_v15g0_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rf-ParametersMRDC-v15g0 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtension */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_UE_MRDC_Capability_v15g0_specs_1 = {
	sizeof(struct ASN_RRC_UE_MRDC_Capability_v15g0),
	offsetof(struct ASN_RRC_UE_MRDC_Capability_v15g0, _asn_ctx),
	asn_MAP_ASN_RRC_UE_MRDC_Capability_v15g0_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_UE_MRDC_Capability_v15g0_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_UE_MRDC_Capability_v15g0 = {
	"UE-MRDC-Capability-v15g0",
	"UE-MRDC-Capability-v15g0",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_UE_MRDC_Capability_v15g0_tags_1,
	sizeof(asn_DEF_ASN_RRC_UE_MRDC_Capability_v15g0_tags_1)
		/sizeof(asn_DEF_ASN_RRC_UE_MRDC_Capability_v15g0_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_UE_MRDC_Capability_v15g0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_UE_MRDC_Capability_v15g0_tags_1)
		/sizeof(asn_DEF_ASN_RRC_UE_MRDC_Capability_v15g0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_UE_MRDC_Capability_v15g0_1,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_UE_MRDC_Capability_v15g0_specs_1	/* Additional specs */
};

