/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_SL_PSSCH_TxConfig_r16_H_
#define	_ASN_RRC_SL_PSSCH_TxConfig_r16_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_RRC_SL-TypeTxSync-r16.h"
#include "../asn1c/NativeEnumerated.h"
#include "ASN_RRC_SL-PSSCH-TxParameters-r16.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16 {
	ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16_kmph60	= 0,
	ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16_kmph80	= 1,
	ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16_kmph100	= 2,
	ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16_kmph120	= 3,
	ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16_kmph140	= 4,
	ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16_kmph160	= 5,
	ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16_kmph180	= 6,
	ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16_kmph200	= 7
} e_ASN_RRC_SL_PSSCH_TxConfig_r16__sl_ThresUE_Speed_r16;

/* Forward declarations */
struct ASN_RRC_SL_MinMaxMCS_List_r16;

/* SL-PSSCH-TxConfig-r16 */
typedef struct ASN_RRC_SL_PSSCH_TxConfig_r16 {
	ASN_RRC_SL_TypeTxSync_r16_t	*sl_TypeTxSync_r16	/* OPTIONAL */;
	long	 sl_ThresUE_Speed_r16;
	ASN_RRC_SL_PSSCH_TxParameters_r16_t	 sl_ParametersAboveThres_r16;
	ASN_RRC_SL_PSSCH_TxParameters_r16_t	 sl_ParametersBelowThres_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct ASN_RRC_SL_MinMaxMCS_List_r16	*sl_ParametersAboveThres_v1650	/* OPTIONAL */;
	struct ASN_RRC_SL_MinMaxMCS_List_r16	*sl_ParametersBelowThres_v1650	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SL_PSSCH_TxConfig_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_sl_ThresUE_Speed_r16_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SL_PSSCH_TxConfig_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SL_PSSCH_TxConfig_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SL_PSSCH_TxConfig_r16_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SL_PSSCH_TxConfig_r16_H_ */
#include "../asn1c/asn_internal.h"
