/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_VictimSystemType_H_
#define	_ASN_RRC_VictimSystemType_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_VictimSystemType__gps {
	ASN_RRC_VictimSystemType__gps_true	= 0
} e_ASN_RRC_VictimSystemType__gps;
typedef enum ASN_RRC_VictimSystemType__glonass {
	ASN_RRC_VictimSystemType__glonass_true	= 0
} e_ASN_RRC_VictimSystemType__glonass;
typedef enum ASN_RRC_VictimSystemType__bds {
	ASN_RRC_VictimSystemType__bds_true	= 0
} e_ASN_RRC_VictimSystemType__bds;
typedef enum ASN_RRC_VictimSystemType__galileo {
	ASN_RRC_VictimSystemType__galileo_true	= 0
} e_ASN_RRC_VictimSystemType__galileo;
typedef enum ASN_RRC_VictimSystemType__wlan {
	ASN_RRC_VictimSystemType__wlan_true	= 0
} e_ASN_RRC_VictimSystemType__wlan;
typedef enum ASN_RRC_VictimSystemType__bluetooth {
	ASN_RRC_VictimSystemType__bluetooth_true	= 0
} e_ASN_RRC_VictimSystemType__bluetooth;

/* VictimSystemType */
typedef struct ASN_RRC_VictimSystemType {
	long	*gps	/* OPTIONAL */;
	long	*glonass	/* OPTIONAL */;
	long	*bds	/* OPTIONAL */;
	long	*galileo	/* OPTIONAL */;
	long	*wlan	/* OPTIONAL */;
	long	*bluetooth	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_VictimSystemType_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_gps_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_glonass_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_bds_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_galileo_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_wlan_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_bluetooth_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_VictimSystemType;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_VictimSystemType_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_VictimSystemType_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_VictimSystemType_H_ */
#include "../asn1c/asn_internal.h"
