/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_UECapabilityInformationSidelink_r16_IEs_H_
#define	_ASN_RRC_UECapabilityInformationSidelink_r16_IEs_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_RRC_AccessStratumReleaseSidelink-r16.h"
#include "../asn1c/OCTET_STRING.h"
#include "../asn1c/asn_SEQUENCE_OF.h"
#include "../asn1c/constr_SEQUENCE_OF.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_RRC_PDCP_ParametersSidelink_r16;
struct ASN_RRC_RLC_ParametersSidelink_r16;
struct ASN_RRC_BandCombinationListSidelinkNR_r16;
struct ASN_RRC_FreqBandList;
struct ASN_RRC_UECapabilityInformationSidelink_v1700_IEs;
struct ASN_RRC_BandSidelinkPC5_r16;

/* UECapabilityInformationSidelink-r16-IEs */
typedef struct ASN_RRC_UECapabilityInformationSidelink_r16_IEs {
	ASN_RRC_AccessStratumReleaseSidelink_r16_t	 accessStratumReleaseSidelink_r16;
	struct ASN_RRC_PDCP_ParametersSidelink_r16	*pdcp_ParametersSidelink_r16	/* OPTIONAL */;
	struct ASN_RRC_RLC_ParametersSidelink_r16	*rlc_ParametersSidelink_r16	/* OPTIONAL */;
	struct ASN_RRC_BandCombinationListSidelinkNR_r16	*supportedBandCombinationListSidelinkNR_r16	/* OPTIONAL */;
	struct ASN_RRC_UECapabilityInformationSidelink_r16_IEs__supportedBandListSidelink_r16 {
		A_SEQUENCE_OF(struct ASN_RRC_BandSidelinkPC5_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *supportedBandListSidelink_r16;
	struct ASN_RRC_FreqBandList	*appliedFreqBandListFilter_r16	/* OPTIONAL */;
	OCTET_STRING_t	*lateNonCriticalExtension	/* OPTIONAL */;
	struct ASN_RRC_UECapabilityInformationSidelink_v1700_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_UECapabilityInformationSidelink_r16_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_UECapabilityInformationSidelink_r16_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_UECapabilityInformationSidelink_r16_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_UECapabilityInformationSidelink_r16_IEs_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_UECapabilityInformationSidelink_r16_IEs_H_ */
#include "../asn1c/asn_internal.h"
