/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_SIB5_H_
#define	_ASN_RRC_SIB5_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_RRC_T-Reselection.h"
#include "../asn1c/OCTET_STRING.h"
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SIB5__idleModeMeasVoiceFallback_r17 {
	ASN_RRC_SIB5__idleModeMeasVoiceFallback_r17_true	= 0
} e_ASN_RRC_SIB5__idleModeMeasVoiceFallback_r17;

/* Forward declarations */
struct ASN_RRC_CarrierFreqListEUTRA;
struct ASN_RRC_SpeedStateScaleFactors;
struct ASN_RRC_CarrierFreqListEUTRA_v1610;
struct ASN_RRC_CarrierFreqListEUTRA_v1700;
struct ASN_RRC_CarrierFreqListEUTRA_v1800;

/* SIB5 */
typedef struct ASN_RRC_SIB5 {
	struct ASN_RRC_CarrierFreqListEUTRA	*carrierFreqListEUTRA	/* OPTIONAL */;
	ASN_RRC_T_Reselection_t	 t_ReselectionEUTRA;
	struct ASN_RRC_SpeedStateScaleFactors	*t_ReselectionEUTRA_SF	/* OPTIONAL */;
	OCTET_STRING_t	*lateNonCriticalExtension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct ASN_RRC_CarrierFreqListEUTRA_v1610	*carrierFreqListEUTRA_v1610	/* OPTIONAL */;
	struct ASN_RRC_CarrierFreqListEUTRA_v1700	*carrierFreqListEUTRA_v1700	/* OPTIONAL */;
	long	*idleModeMeasVoiceFallback_r17	/* OPTIONAL */;
	struct ASN_RRC_CarrierFreqListEUTRA_v1800	*carrierFreqListEUTRA_v1800	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SIB5_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_idleModeMeasVoiceFallback_r17_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SIB5;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SIB5_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SIB5_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SIB5_H_ */
#include "../asn1c/asn_internal.h"
