/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_AreaConfiguration-r17.h"

#include "ASN_RRC_AreaConfig-r16.h"
#include "ASN_RRC_InterFreqTargetInfo-r16.h"
static int
memb_ASN_RRC_interFreqTargetList_r17_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 8)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_ASN_RRC_interFreqTargetList_r17_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_interFreqTargetList_r17_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_interFreqTargetList_r17_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_RRC_InterFreqTargetInfo_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_interFreqTargetList_r17_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ASN_RRC_interFreqTargetList_r17_specs_3 = {
	sizeof(struct ASN_RRC_AreaConfiguration_r17__interFreqTargetList_r17),
	offsetof(struct ASN_RRC_AreaConfiguration_r17__interFreqTargetList_r17, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_interFreqTargetList_r17_3 = {
	"interFreqTargetList-r17",
	"interFreqTargetList-r17",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ASN_RRC_interFreqTargetList_r17_tags_3,
	sizeof(asn_DEF_ASN_RRC_interFreqTargetList_r17_tags_3)
		/sizeof(asn_DEF_ASN_RRC_interFreqTargetList_r17_tags_3[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_interFreqTargetList_r17_tags_3,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_interFreqTargetList_r17_tags_3)
		/sizeof(asn_DEF_ASN_RRC_interFreqTargetList_r17_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_interFreqTargetList_r17_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_ASN_RRC_interFreqTargetList_r17_3,
	1,	/* Single element */
	&asn_SPC_ASN_RRC_interFreqTargetList_r17_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_AreaConfiguration_r17_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_AreaConfiguration_r17, areaConfig_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_AreaConfig_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"areaConfig-r17"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_AreaConfiguration_r17, interFreqTargetList_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ASN_RRC_interFreqTargetList_r17_3,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_interFreqTargetList_r17_constr_3,  memb_ASN_RRC_interFreqTargetList_r17_constraint_1 },
		0, 0, /* No default value */
		"interFreqTargetList-r17"
		},
};
static const int asn_MAP_ASN_RRC_AreaConfiguration_r17_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_AreaConfiguration_r17_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_AreaConfiguration_r17_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* areaConfig-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* interFreqTargetList-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_AreaConfiguration_r17_specs_1 = {
	sizeof(struct ASN_RRC_AreaConfiguration_r17),
	offsetof(struct ASN_RRC_AreaConfiguration_r17, _asn_ctx),
	asn_MAP_ASN_RRC_AreaConfiguration_r17_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_AreaConfiguration_r17_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_AreaConfiguration_r17 = {
	"AreaConfiguration-r17",
	"AreaConfiguration-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_AreaConfiguration_r17_tags_1,
	sizeof(asn_DEF_ASN_RRC_AreaConfiguration_r17_tags_1)
		/sizeof(asn_DEF_ASN_RRC_AreaConfiguration_r17_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_AreaConfiguration_r17_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_AreaConfiguration_r17_tags_1)
		/sizeof(asn_DEF_ASN_RRC_AreaConfiguration_r17_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_AreaConfiguration_r17_1,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_AreaConfiguration_r17_specs_1	/* Additional specs */
};

