/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_LocationMeasurementInfo_H_
#define	_ASN_RRC_LocationMeasurementInfo_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NULL.h"
#include "../asn1c/constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_LocationMeasurementInfo_PR {
	ASN_RRC_LocationMeasurementInfo_PR_NOTHING,	/* No components present */
	ASN_RRC_LocationMeasurementInfo_PR_eutra_RSTD,
	/* Extensions may appear below */
	ASN_RRC_LocationMeasurementInfo_PR_eutra_FineTimingDetection,
	ASN_RRC_LocationMeasurementInfo_PR_nr_PRS_Measurement_r16
} ASN_RRC_LocationMeasurementInfo_PR;

/* Forward declarations */
struct ASN_RRC_EUTRA_RSTD_InfoList;
struct ASN_RRC_NR_PRS_MeasurementInfoList_r16;

/* LocationMeasurementInfo */
typedef struct ASN_RRC_LocationMeasurementInfo {
	ASN_RRC_LocationMeasurementInfo_PR present;
	union ASN_RRC_LocationMeasurementInfo_u {
		struct ASN_RRC_EUTRA_RSTD_InfoList	*eutra_RSTD;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		NULL_t	 eutra_FineTimingDetection;
		struct ASN_RRC_NR_PRS_MeasurementInfoList_r16	*nr_PRS_Measurement_r16;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_LocationMeasurementInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_LocationMeasurementInfo;
extern asn_CHOICE_specifics_t asn_SPC_ASN_RRC_LocationMeasurementInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_LocationMeasurementInfo_1[3];
extern asn_per_constraints_t asn_PER_type_ASN_RRC_LocationMeasurementInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_LocationMeasurementInfo_H_ */
#include "../asn1c/asn_internal.h"
