/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_CSI_ReportPeriodicityAndOffset_H_
#define	_ASN_RRC_CSI_ReportPeriodicityAndOffset_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeInteger.h"
#include "../asn1c/constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_CSI_ReportPeriodicityAndOffset_PR {
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_NOTHING,	/* No components present */
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots4,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots5,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots8,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots10,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots16,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots20,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots40,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots80,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots160,
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR_slots320
} ASN_RRC_CSI_ReportPeriodicityAndOffset_PR;

/* CSI-ReportPeriodicityAndOffset */
typedef struct ASN_RRC_CSI_ReportPeriodicityAndOffset {
	ASN_RRC_CSI_ReportPeriodicityAndOffset_PR present;
	union ASN_RRC_CSI_ReportPeriodicityAndOffset_u {
		long	 slots4;
		long	 slots5;
		long	 slots8;
		long	 slots10;
		long	 slots16;
		long	 slots20;
		long	 slots40;
		long	 slots80;
		long	 slots160;
		long	 slots320;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_CSI_ReportPeriodicityAndOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_CSI_ReportPeriodicityAndOffset;
extern asn_CHOICE_specifics_t asn_SPC_ASN_RRC_CSI_ReportPeriodicityAndOffset_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_CSI_ReportPeriodicityAndOffset_1[10];
extern asn_per_constraints_t asn_PER_type_ASN_RRC_CSI_ReportPeriodicityAndOffset_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_CSI_ReportPeriodicityAndOffset_H_ */
#include "../asn1c/asn_internal.h"
