/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_SL_ResourceReservePeriod_r16_H_
#define	_ASN_RRC_SL_ResourceReservePeriod_r16_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/NativeInteger.h"
#include "../asn1c/constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SL_ResourceReservePeriod_r16_PR {
	ASN_RRC_SL_ResourceReservePeriod_r16_PR_NOTHING,	/* No components present */
	ASN_RRC_SL_ResourceReservePeriod_r16_PR_sl_ResourceReservePeriod1_r16,
	ASN_RRC_SL_ResourceReservePeriod_r16_PR_sl_ResourceReservePeriod2_r16
} ASN_RRC_SL_ResourceReservePeriod_r16_PR;
typedef enum ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16 {
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms0	= 0,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms100	= 1,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms200	= 2,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms300	= 3,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms400	= 4,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms500	= 5,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms600	= 6,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms700	= 7,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms800	= 8,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms900	= 9,
	ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16_ms1000	= 10
} e_ASN_RRC_SL_ResourceReservePeriod_r16__sl_ResourceReservePeriod1_r16;

/* SL-ResourceReservePeriod-r16 */
typedef struct ASN_RRC_SL_ResourceReservePeriod_r16 {
	ASN_RRC_SL_ResourceReservePeriod_r16_PR present;
	union ASN_RRC_SL_ResourceReservePeriod_r16_u {
		long	 sl_ResourceReservePeriod1_r16;
		long	 sl_ResourceReservePeriod2_r16;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SL_ResourceReservePeriod_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_sl_ResourceReservePeriod1_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SL_ResourceReservePeriod_r16;
extern asn_CHOICE_specifics_t asn_SPC_ASN_RRC_SL_ResourceReservePeriod_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SL_ResourceReservePeriod_r16_1[2];
extern asn_per_constraints_t asn_PER_type_ASN_RRC_SL_ResourceReservePeriod_r16_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SL_ResourceReservePeriod_r16_H_ */
#include "../asn1c/asn_internal.h"
