/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_SIB24-r18.h"

#include "ASN_RRC_MCCH-Config-r17.h"
#include "ASN_RRC_CFR-ConfigMCCH-MTCH-r17.h"
asn_TYPE_member_t asn_MBR_ASN_RRC_SIB24_r18_1[] = {
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_SIB24_r18, multicastMCCH_Config_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MCCH_Config_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"multicastMCCH-Config-r18"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_SIB24_r18, cfr_ConfigMCCH_MTCH_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_CFR_ConfigMCCH_MTCH_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cfr-ConfigMCCH-MTCH-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_SIB24_r18, lateNonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lateNonCriticalExtension"
		},
};
static const int asn_MAP_ASN_RRC_SIB24_r18_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_SIB24_r18_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_SIB24_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* multicastMCCH-Config-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cfr-ConfigMCCH-MTCH-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* lateNonCriticalExtension */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SIB24_r18_specs_1 = {
	sizeof(struct ASN_RRC_SIB24_r18),
	offsetof(struct ASN_RRC_SIB24_r18, _asn_ctx),
	asn_MAP_ASN_RRC_SIB24_r18_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_SIB24_r18_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SIB24_r18 = {
	"SIB24-r18",
	"SIB24-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_SIB24_r18_tags_1,
	sizeof(asn_DEF_ASN_RRC_SIB24_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_SIB24_r18_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_SIB24_r18_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_SIB24_r18_tags_1)
		/sizeof(asn_DEF_ASN_RRC_SIB24_r18_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_SIB24_r18_1,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_SIB24_r18_specs_1	/* Additional specs */
};

