/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_CO-DurationsPerCell-r16.h"

static int
memb_ASN_RRC_positionInDCI_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 127)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_co_DurationList_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 64)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_ASN_RRC_co_DurationList_r16_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  64 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_positionInDCI_r16_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (0..127) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_co_DurationList_r16_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  64 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_co_DurationList_r16_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ASN_RRC_CO_Duration_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_co_DurationList_r16_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ASN_RRC_co_DurationList_r16_specs_5 = {
	sizeof(struct ASN_RRC_CO_DurationsPerCell_r16__co_DurationList_r16),
	offsetof(struct ASN_RRC_CO_DurationsPerCell_r16__co_DurationList_r16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_co_DurationList_r16_5 = {
	"co-DurationList-r16",
	"co-DurationList-r16",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ASN_RRC_co_DurationList_r16_tags_5,
	sizeof(asn_DEF_ASN_RRC_co_DurationList_r16_tags_5)
		/sizeof(asn_DEF_ASN_RRC_co_DurationList_r16_tags_5[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_co_DurationList_r16_tags_5,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_co_DurationList_r16_tags_5)
		/sizeof(asn_DEF_ASN_RRC_co_DurationList_r16_tags_5[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_co_DurationList_r16_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_ASN_RRC_co_DurationList_r16_5,
	1,	/* Single element */
	&asn_SPC_ASN_RRC_co_DurationList_r16_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_CO_DurationsPerCell_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CO_DurationsPerCell_r16, servingCellId_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_ServCellIndex,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"servingCellId-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CO_DurationsPerCell_r16, positionInDCI_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_positionInDCI_r16_constr_3,  memb_ASN_RRC_positionInDCI_r16_constraint_1 },
		0, 0, /* No default value */
		"positionInDCI-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CO_DurationsPerCell_r16, subcarrierSpacing_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_SubcarrierSpacing,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subcarrierSpacing-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CO_DurationsPerCell_r16, co_DurationList_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ASN_RRC_co_DurationList_r16_5,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_co_DurationList_r16_constr_5,  memb_ASN_RRC_co_DurationList_r16_constraint_1 },
		0, 0, /* No default value */
		"co-DurationList-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_CO_DurationsPerCell_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_CO_DurationsPerCell_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* servingCellId-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* positionInDCI-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* subcarrierSpacing-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* co-DurationList-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_CO_DurationsPerCell_r16_specs_1 = {
	sizeof(struct ASN_RRC_CO_DurationsPerCell_r16),
	offsetof(struct ASN_RRC_CO_DurationsPerCell_r16, _asn_ctx),
	asn_MAP_ASN_RRC_CO_DurationsPerCell_r16_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_CO_DurationsPerCell_r16 = {
	"CO-DurationsPerCell-r16",
	"CO-DurationsPerCell-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_CO_DurationsPerCell_r16_tags_1,
	sizeof(asn_DEF_ASN_RRC_CO_DurationsPerCell_r16_tags_1)
		/sizeof(asn_DEF_ASN_RRC_CO_DurationsPerCell_r16_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_CO_DurationsPerCell_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_CO_DurationsPerCell_r16_tags_1)
		/sizeof(asn_DEF_ASN_RRC_CO_DurationsPerCell_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_CO_DurationsPerCell_r16_1,
	4,	/* Elements count */
	&asn_SPC_ASN_RRC_CO_DurationsPerCell_r16_specs_1	/* Additional specs */
};

