/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_MCCH_Config_r17_H_
#define	_ASN_RRC_MCCH_Config_r17_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_RRC_MCCH-RepetitionPeriodAndOffset-r17.h"
#include "../asn1c/NativeInteger.h"
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17 {
	ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17_sl2	= 0,
	ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17_sl4	= 1,
	ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17_sl8	= 2,
	ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17_sl10	= 3,
	ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17_sl20	= 4,
	ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17_sl40	= 5,
	ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17_sl80	= 6,
	ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17_sl160	= 7
} e_ASN_RRC_MCCH_Config_r17__mcch_WindowDuration_r17;
typedef enum ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17 {
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf2	= 0,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf4	= 1,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf8	= 2,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf16	= 3,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf32	= 4,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf64	= 5,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf128	= 6,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf256	= 7,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf512	= 8,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf1024	= 9,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf2048	= 10,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf4096	= 11,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf8192	= 12,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf16384	= 13,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf32768	= 14,
	ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17_rf65536	= 15
} e_ASN_RRC_MCCH_Config_r17__mcch_ModificationPeriod_r17;

/* MCCH-Config-r17 */
typedef struct ASN_RRC_MCCH_Config_r17 {
	ASN_RRC_MCCH_RepetitionPeriodAndOffset_r17_t	 mcch_RepetitionPeriodAndOffset_r17;
	long	 mcch_WindowStartSlot_r17;
	long	*mcch_WindowDuration_r17	/* OPTIONAL */;
	long	 mcch_ModificationPeriod_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_MCCH_Config_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_mcch_WindowDuration_r17_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_mcch_ModificationPeriod_r17_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_MCCH_Config_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_MCCH_Config_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_MCCH_Config_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_MCCH_Config_r17_H_ */
#include "../asn1c/asn_internal.h"
