/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_FeatureSets_H_
#define	_ASN_RRC_FeatureSets_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/asn_SEQUENCE_OF.h"
#include "../asn1c/constr_SEQUENCE_OF.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_RRC_FeatureSetDownlink;
struct ASN_RRC_FeatureSetDownlinkPerCC;
struct ASN_RRC_FeatureSetUplink;
struct ASN_RRC_FeatureSetUplinkPerCC;
struct ASN_RRC_FeatureSetDownlink_v1540;
struct ASN_RRC_FeatureSetUplink_v1540;
struct ASN_RRC_FeatureSetUplinkPerCC_v1540;
struct ASN_RRC_FeatureSetDownlink_v15a0;
struct ASN_RRC_FeatureSetDownlink_v1610;
struct ASN_RRC_FeatureSetUplink_v1610;
struct ASN_RRC_FeatureSetDownlinkPerCC_v1620;
struct ASN_RRC_FeatureSetUplink_v1630;
struct ASN_RRC_FeatureSetUplink_v1640;
struct ASN_RRC_FeatureSetDownlink_v1700;
struct ASN_RRC_FeatureSetDownlinkPerCC_v1700;
struct ASN_RRC_FeatureSetUplink_v1710;
struct ASN_RRC_FeatureSetUplinkPerCC_v1700;
struct ASN_RRC_FeatureSetDownlink_v1720;
struct ASN_RRC_FeatureSetDownlinkPerCC_v1720;
struct ASN_RRC_FeatureSetUplink_v1720;
struct ASN_RRC_FeatureSetDownlink_v1730;
struct ASN_RRC_FeatureSetDownlinkPerCC_v1730;
struct ASN_RRC_FeatureSetDownlinkPerCC_v1780;
struct ASN_RRC_FeatureSetUplinkPerCC_v1780;
struct ASN_RRC_FeatureSetDownlink_v1800;
struct ASN_RRC_FeatureSetDownlinkPerCC_v1800;
struct ASN_RRC_FeatureSetUplink_v1800;
struct ASN_RRC_FeatureSetUplinkPerCC_v1800;
struct ASN_RRC_FeatureSetDownlink_v1830;
struct ASN_RRC_FeatureSetDownlinkPerCC_v1840;
struct ASN_RRC_FeatureSetUplinkPerCC_v1840;
struct ASN_RRC_FeatureSetUplink_v1850;
struct ASN_RRC_FeatureSetUplinkPerCC_v1850;
struct ASN_RRC_FeatureSetDownlink_v1860;

/* FeatureSets */
typedef struct ASN_RRC_FeatureSets {
	struct ASN_RRC_FeatureSets__featureSetsDownlink {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink;
	struct ASN_RRC_FeatureSets__featureSetsDownlinkPerCC {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlinkPerCC) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlinkPerCC;
	struct ASN_RRC_FeatureSets__featureSetsUplink {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink;
	struct ASN_RRC_FeatureSets__featureSetsUplinkPerCC {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplinkPerCC) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplinkPerCC;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v1540 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v1540) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v1540;
	struct ASN_RRC_FeatureSets__featureSetsUplink_v1540 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink_v1540) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink_v1540;
	struct ASN_RRC_FeatureSets__featureSetsUplinkPerCC_v1540 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplinkPerCC_v1540) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplinkPerCC_v1540;
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v15a0 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v15a0) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v15a0;
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v1610 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v1610) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v1610;
	struct ASN_RRC_FeatureSets__featureSetsUplink_v1610 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink_v1610) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink_v1610;
	struct ASN_RRC_FeatureSets__featureSetDownlinkPerCC_v1620 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlinkPerCC_v1620) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetDownlinkPerCC_v1620;
	struct ASN_RRC_FeatureSets__featureSetsUplink_v1630 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink_v1630) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink_v1630;
	struct ASN_RRC_FeatureSets__featureSetsUplink_v1640 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink_v1640) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink_v1640;
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v1700 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v1700) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v1700;
	struct ASN_RRC_FeatureSets__featureSetsDownlinkPerCC_v1700 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlinkPerCC_v1700) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlinkPerCC_v1700;
	struct ASN_RRC_FeatureSets__featureSetsUplink_v1710 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink_v1710) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink_v1710;
	struct ASN_RRC_FeatureSets__featureSetsUplinkPerCC_v1700 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplinkPerCC_v1700) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplinkPerCC_v1700;
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v1720 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v1720) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v1720;
	struct ASN_RRC_FeatureSets__featureSetsDownlinkPerCC_v1720 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlinkPerCC_v1720) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlinkPerCC_v1720;
	struct ASN_RRC_FeatureSets__featureSetsUplink_v1720 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink_v1720) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink_v1720;
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v1730 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v1730) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v1730;
	struct ASN_RRC_FeatureSets__featureSetsDownlinkPerCC_v1730 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlinkPerCC_v1730) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlinkPerCC_v1730;
	struct ASN_RRC_FeatureSets__featureSetsDownlinkPerCC_v1780 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlinkPerCC_v1780) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlinkPerCC_v1780;
	struct ASN_RRC_FeatureSets__featureSetsUplinkPerCC_v1780 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplinkPerCC_v1780) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplinkPerCC_v1780;
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v1800 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v1800) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v1800;
	struct ASN_RRC_FeatureSets__featureSetsDownlinkPerCC_v1800 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlinkPerCC_v1800) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlinkPerCC_v1800;
	struct ASN_RRC_FeatureSets__featureSetsUplink_v1800 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink_v1800) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink_v1800;
	struct ASN_RRC_FeatureSets__featureSetsUplinkPerCC_v1800 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplinkPerCC_v1800) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplinkPerCC_v1800;
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v1830 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v1830) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v1830;
	struct ASN_RRC_FeatureSets__featureSetsDownlinkPerCC_v1840 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlinkPerCC_v1840) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlinkPerCC_v1840;
	struct ASN_RRC_FeatureSets__featureSetsUplinkPerCC_v1840 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplinkPerCC_v1840) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplinkPerCC_v1840;
	struct ASN_RRC_FeatureSets__featureSetsUplink_v1850 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplink_v1850) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplink_v1850;
	struct ASN_RRC_FeatureSets__featureSetsUplinkPerCC_v1850 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetUplinkPerCC_v1850) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsUplinkPerCC_v1850;
	struct ASN_RRC_FeatureSets__featureSetsDownlink_v1860 {
		A_SEQUENCE_OF(struct ASN_RRC_FeatureSetDownlink_v1860) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetsDownlink_v1860;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_FeatureSets_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_FeatureSets;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_FeatureSets_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_FeatureSets_1[34];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_FeatureSets_H_ */
#include "../asn1c/asn_internal.h"
