/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_AutonomousDenialParameters_r18_H_
#define	_ASN_RRC_AutonomousDenialParameters_r18_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18 {
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18_n2	= 0,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18_n5	= 1,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18_n10	= 2,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18_n15	= 3,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18_n20	= 4,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18_n30	= 5,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18_spare2	= 6,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18_spare1	= 7
} e_ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialSlots_r18;
typedef enum ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialValidity_r18 {
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialValidity_r18_n200	= 0,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialValidity_r18_n500	= 1,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialValidity_r18_n1000	= 2,
	ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialValidity_r18_n2000	= 3
} e_ASN_RRC_AutonomousDenialParameters_r18__autonomousDenialValidity_r18;

/* AutonomousDenialParameters-r18 */
typedef struct ASN_RRC_AutonomousDenialParameters_r18 {
	long	 autonomousDenialSlots_r18;
	long	 autonomousDenialValidity_r18;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_AutonomousDenialParameters_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_autonomousDenialSlots_r18_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_autonomousDenialValidity_r18_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_AutonomousDenialParameters_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_AutonomousDenialParameters_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_AutonomousDenialParameters_r18_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_AutonomousDenialParameters_r18_H_ */
#include "../asn1c/asn_internal.h"
