/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_RRC_CondTriggerConfig-r16.h"

static int
memb_ASN_RRC_distanceThreshFromReference1_r17_constraint_17(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65525)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_distanceThreshFromReference2_r17_constraint_17(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65525)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_t1_Threshold_r17_constraint_24(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(asn_INTEGER2long(st, &value)) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value too large (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((value >= 0 && value <= 549755813887)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_duration_r17_constraint_24(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 6000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_distanceThreshFromReference1_r18_constraint_27(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_distanceThreshFromReference2_r18_constraint_27(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_memb_ASN_RRC_distanceThreshFromReference1_r17_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65525 }	/* (0..65525) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_distanceThreshFromReference2_r17_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65525 }	/* (0..65525) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_t1_Threshold_r17_constr_25 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 39, -1,  0,  549755813887 }	/* (0..549755813887) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_duration_r17_constr_26 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 13,  13,  1,  6000 }	/* (1..6000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_distanceThreshFromReference1_r18_constr_28 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_distanceThreshFromReference2_r18_constr_29 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_condEventId_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_nesEvent_r18_constr_34 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_condEventA3_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA3, a3_Offset),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasTriggerQuantityOffset,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"a3-Offset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA3, hysteresis),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_Hysteresis,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresis"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA3, timeToTrigger),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_condEventA3_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_condEventA3_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* a3-Offset */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hysteresis */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timeToTrigger */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_condEventA3_specs_3 = {
	sizeof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA3),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA3, _asn_ctx),
	asn_MAP_ASN_RRC_condEventA3_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_condEventA3_3 = {
	"condEventA3",
	"condEventA3",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_condEventA3_tags_3,
	sizeof(asn_DEF_ASN_RRC_condEventA3_tags_3)
		/sizeof(asn_DEF_ASN_RRC_condEventA3_tags_3[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_condEventA3_tags_3,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_condEventA3_tags_3)
		/sizeof(asn_DEF_ASN_RRC_condEventA3_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_condEventA3_3,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_condEventA3_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_condEventA5_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA5, a5_Threshold1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasTriggerQuantity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"a5-Threshold1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA5, a5_Threshold2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasTriggerQuantity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"a5-Threshold2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA5, hysteresis),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_Hysteresis,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresis"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA5, timeToTrigger),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_condEventA5_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_condEventA5_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* a5-Threshold1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* a5-Threshold2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* hysteresis */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* timeToTrigger */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_condEventA5_specs_7 = {
	sizeof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA5),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA5, _asn_ctx),
	asn_MAP_ASN_RRC_condEventA5_tag2el_7,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_condEventA5_7 = {
	"condEventA5",
	"condEventA5",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_condEventA5_tags_7,
	sizeof(asn_DEF_ASN_RRC_condEventA5_tags_7)
		/sizeof(asn_DEF_ASN_RRC_condEventA5_tags_7[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_condEventA5_tags_7,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_condEventA5_tags_7)
		/sizeof(asn_DEF_ASN_RRC_condEventA5_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_condEventA5_7,
	4,	/* Elements count */
	&asn_SPC_ASN_RRC_condEventA5_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_condEventA4_r17_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA4_r17, a4_Threshold_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasTriggerQuantity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"a4-Threshold-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA4_r17, hysteresis_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_Hysteresis,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresis-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA4_r17, timeToTrigger_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger-r17"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_condEventA4_r17_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_condEventA4_r17_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* a4-Threshold-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hysteresis-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timeToTrigger-r17 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_condEventA4_r17_specs_13 = {
	sizeof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA4_r17),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventA4_r17, _asn_ctx),
	asn_MAP_ASN_RRC_condEventA4_r17_tag2el_13,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_condEventA4_r17_13 = {
	"condEventA4-r17",
	"condEventA4-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_condEventA4_r17_tags_13,
	sizeof(asn_DEF_ASN_RRC_condEventA4_r17_tags_13)
		/sizeof(asn_DEF_ASN_RRC_condEventA4_r17_tags_13[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_condEventA4_r17_tags_13,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_condEventA4_r17_tags_13)
		/sizeof(asn_DEF_ASN_RRC_condEventA4_r17_tags_13[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_condEventA4_r17_13,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_condEventA4_r17_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_condEventD1_r17_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD1_r17, distanceThreshFromReference1_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_distanceThreshFromReference1_r17_constr_18,  memb_ASN_RRC_distanceThreshFromReference1_r17_constraint_17 },
		0, 0, /* No default value */
		"distanceThreshFromReference1-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD1_r17, distanceThreshFromReference2_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_distanceThreshFromReference2_r17_constr_19,  memb_ASN_RRC_distanceThreshFromReference2_r17_constraint_17 },
		0, 0, /* No default value */
		"distanceThreshFromReference2-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD1_r17, referenceLocation1_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_ReferenceLocation_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referenceLocation1-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD1_r17, referenceLocation2_r17),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_ReferenceLocation_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referenceLocation2-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD1_r17, hysteresisLocation_r17),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_HysteresisLocation_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresisLocation-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD1_r17, timeToTrigger_r17),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger-r17"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_condEventD1_r17_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_condEventD1_r17_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* distanceThreshFromReference1-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* distanceThreshFromReference2-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* referenceLocation1-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* referenceLocation2-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* hysteresisLocation-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* timeToTrigger-r17 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_condEventD1_r17_specs_17 = {
	sizeof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD1_r17),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD1_r17, _asn_ctx),
	asn_MAP_ASN_RRC_condEventD1_r17_tag2el_17,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_condEventD1_r17_17 = {
	"condEventD1-r17",
	"condEventD1-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_condEventD1_r17_tags_17,
	sizeof(asn_DEF_ASN_RRC_condEventD1_r17_tags_17)
		/sizeof(asn_DEF_ASN_RRC_condEventD1_r17_tags_17[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_condEventD1_r17_tags_17,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_condEventD1_r17_tags_17)
		/sizeof(asn_DEF_ASN_RRC_condEventD1_r17_tags_17[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_condEventD1_r17_17,
	6,	/* Elements count */
	&asn_SPC_ASN_RRC_condEventD1_r17_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_condEventT1_r17_24[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventT1_r17, t1_Threshold_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_t1_Threshold_r17_constr_25,  memb_ASN_RRC_t1_Threshold_r17_constraint_24 },
		0, 0, /* No default value */
		"t1-Threshold-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventT1_r17, duration_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_duration_r17_constr_26,  memb_ASN_RRC_duration_r17_constraint_24 },
		0, 0, /* No default value */
		"duration-r17"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_condEventT1_r17_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_condEventT1_r17_tag2el_24[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* t1-Threshold-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* duration-r17 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_condEventT1_r17_specs_24 = {
	sizeof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventT1_r17),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventT1_r17, _asn_ctx),
	asn_MAP_ASN_RRC_condEventT1_r17_tag2el_24,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_condEventT1_r17_24 = {
	"condEventT1-r17",
	"condEventT1-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_condEventT1_r17_tags_24,
	sizeof(asn_DEF_ASN_RRC_condEventT1_r17_tags_24)
		/sizeof(asn_DEF_ASN_RRC_condEventT1_r17_tags_24[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_condEventT1_r17_tags_24,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_condEventT1_r17_tags_24)
		/sizeof(asn_DEF_ASN_RRC_condEventT1_r17_tags_24[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_condEventT1_r17_24,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_condEventT1_r17_specs_24	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_condEventD2_r18_27[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD2_r18, distanceThreshFromReference1_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_distanceThreshFromReference1_r18_constr_28,  memb_ASN_RRC_distanceThreshFromReference1_r18_constraint_27 },
		0, 0, /* No default value */
		"distanceThreshFromReference1-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD2_r18, distanceThreshFromReference2_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_distanceThreshFromReference2_r18_constr_29,  memb_ASN_RRC_distanceThreshFromReference2_r18_constraint_27 },
		0, 0, /* No default value */
		"distanceThreshFromReference2-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD2_r18, hysteresisLocation_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_HysteresisLocation_r17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresisLocation-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD2_r18, timeToTrigger_r18),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger-r18"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_condEventD2_r18_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_condEventD2_r18_tag2el_27[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* distanceThreshFromReference1-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* distanceThreshFromReference2-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* hysteresisLocation-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* timeToTrigger-r18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_condEventD2_r18_specs_27 = {
	sizeof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD2_r18),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId__condEventD2_r18, _asn_ctx),
	asn_MAP_ASN_RRC_condEventD2_r18_tag2el_27,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_condEventD2_r18_27 = {
	"condEventD2-r18",
	"condEventD2-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_condEventD2_r18_tags_27,
	sizeof(asn_DEF_ASN_RRC_condEventD2_r18_tags_27)
		/sizeof(asn_DEF_ASN_RRC_condEventD2_r18_tags_27[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_condEventD2_r18_tags_27,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_condEventD2_r18_tags_27)
		/sizeof(asn_DEF_ASN_RRC_condEventD2_r18_tags_27[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_condEventD2_r18_27,
	4,	/* Elements count */
	&asn_SPC_ASN_RRC_condEventD2_r18_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_condEventId_2[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId, choice.condEventA3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ASN_RRC_condEventA3_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condEventA3"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId, choice.condEventA5),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ASN_RRC_condEventA5_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condEventA5"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId, choice.condEventA4_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ASN_RRC_condEventA4_r17_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condEventA4-r17"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId, choice.condEventD1_r17),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ASN_RRC_condEventD1_r17_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condEventD1-r17"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId, choice.condEventT1_r17),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ASN_RRC_condEventT1_r17_24,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condEventT1-r17"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId, choice.condEventD2_r18),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_ASN_RRC_condEventD2_r18_27,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condEventD2-r18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_condEventId_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* condEventA3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* condEventA5 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* condEventA4-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* condEventD1-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* condEventT1-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* condEventD2-r18 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_condEventId_specs_2 = {
	sizeof(struct ASN_RRC_CondTriggerConfig_r16__condEventId),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId, _asn_ctx),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16__condEventId, present),
	sizeof(((struct ASN_RRC_CondTriggerConfig_r16__condEventId *)0)->present),
	asn_MAP_ASN_RRC_condEventId_tag2el_2,
	6,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_condEventId_2 = {
	"condEventId",
	"condEventId",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_condEventId_constr_2, CHOICE_constraint },
	asn_MBR_ASN_RRC_condEventId_2,
	6,	/* Elements count */
	&asn_SPC_ASN_RRC_condEventId_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_nesEvent_r18_value2enum_34[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_ASN_RRC_nesEvent_r18_enum2value_34[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_nesEvent_r18_specs_34 = {
	asn_MAP_ASN_RRC_nesEvent_r18_value2enum_34,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_nesEvent_r18_enum2value_34,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_nesEvent_r18_tags_34[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_nesEvent_r18_34 = {
	"nesEvent-r18",
	"nesEvent-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_nesEvent_r18_tags_34,
	sizeof(asn_DEF_ASN_RRC_nesEvent_r18_tags_34)
		/sizeof(asn_DEF_ASN_RRC_nesEvent_r18_tags_34[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_nesEvent_r18_tags_34,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_nesEvent_r18_tags_34)
		/sizeof(asn_DEF_ASN_RRC_nesEvent_r18_tags_34[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_nesEvent_r18_constr_34, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_nesEvent_r18_specs_34	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_CondTriggerConfig_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16, condEventId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_condEventId_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condEventId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CondTriggerConfig_r16, rsType_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_NR_RS_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsType-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_CondTriggerConfig_r16, nesEvent_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_nesEvent_r18_34,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nesEvent-r18"
		},
};
static const int asn_MAP_ASN_RRC_CondTriggerConfig_r16_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_CondTriggerConfig_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_CondTriggerConfig_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* condEventId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rsType-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nesEvent-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_CondTriggerConfig_r16_specs_1 = {
	sizeof(struct ASN_RRC_CondTriggerConfig_r16),
	offsetof(struct ASN_RRC_CondTriggerConfig_r16, _asn_ctx),
	asn_MAP_ASN_RRC_CondTriggerConfig_r16_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_CondTriggerConfig_r16_oms_1,	/* Optional members */
	0, 1,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_CondTriggerConfig_r16 = {
	"CondTriggerConfig-r16",
	"CondTriggerConfig-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_CondTriggerConfig_r16_tags_1,
	sizeof(asn_DEF_ASN_RRC_CondTriggerConfig_r16_tags_1)
		/sizeof(asn_DEF_ASN_RRC_CondTriggerConfig_r16_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_CondTriggerConfig_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_CondTriggerConfig_r16_tags_1)
		/sizeof(asn_DEF_ASN_RRC_CondTriggerConfig_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_CondTriggerConfig_r16_1,
	3,	/* Elements count */
	&asn_SPC_ASN_RRC_CondTriggerConfig_r16_specs_1	/* Additional specs */
};

