/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_SL_PDCP_Config_r16_H_
#define	_ASN_RRC_SL_PDCP_Config_r16_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeEnumerated.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16 {
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms3	= 0,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms10	= 1,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms20	= 2,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms25	= 3,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms30	= 4,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms40	= 5,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms50	= 6,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms60	= 7,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms75	= 8,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms100	= 9,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms150	= 10,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms200	= 11,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms250	= 12,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms300	= 13,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms500	= 14,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms750	= 15,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms1500	= 16,
	ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16_infinity	= 17
} e_ASN_RRC_SL_PDCP_Config_r16__sl_DiscardTimer_r16;
typedef enum ASN_RRC_SL_PDCP_Config_r16__sl_PDCP_SN_Size_r16 {
	ASN_RRC_SL_PDCP_Config_r16__sl_PDCP_SN_Size_r16_len12bits	= 0,
	ASN_RRC_SL_PDCP_Config_r16__sl_PDCP_SN_Size_r16_len18bits	= 1
} e_ASN_RRC_SL_PDCP_Config_r16__sl_PDCP_SN_Size_r16;
typedef enum ASN_RRC_SL_PDCP_Config_r16__sl_OutOfOrderDelivery {
	ASN_RRC_SL_PDCP_Config_r16__sl_OutOfOrderDelivery_true	= 0
} e_ASN_RRC_SL_PDCP_Config_r16__sl_OutOfOrderDelivery;

/* SL-PDCP-Config-r16 */
typedef struct ASN_RRC_SL_PDCP_Config_r16 {
	long	*sl_DiscardTimer_r16	/* OPTIONAL */;
	long	*sl_PDCP_SN_Size_r16	/* OPTIONAL */;
	long	*sl_OutOfOrderDelivery	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SL_PDCP_Config_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_sl_DiscardTimer_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_sl_PDCP_SN_Size_r16_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_sl_OutOfOrderDelivery_24;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SL_PDCP_Config_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SL_PDCP_Config_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SL_PDCP_Config_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SL_PDCP_Config_r16_H_ */
#include "../asn1c/asn_internal.h"
