/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn1-definitions/rrc-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/rrc -fprefix=ASN_RRC_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_RRC_UL_GapFR2_Config_r17_H_
#define	_ASN_RRC_UL_GapFR2_Config_r17_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeInteger.h"
#include "../asn1c/NativeEnumerated.h"
#include "ASN_RRC_ServCellIndex.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_UL_GapFR2_Config_r17__ugl_r17 {
	ASN_RRC_UL_GapFR2_Config_r17__ugl_r17_ms0dot125	= 0,
	ASN_RRC_UL_GapFR2_Config_r17__ugl_r17_ms0dot25	= 1,
	ASN_RRC_UL_GapFR2_Config_r17__ugl_r17_ms0dot5	= 2,
	ASN_RRC_UL_GapFR2_Config_r17__ugl_r17_ms1	= 3
} e_ASN_RRC_UL_GapFR2_Config_r17__ugl_r17;
typedef enum ASN_RRC_UL_GapFR2_Config_r17__ugrp_r17 {
	ASN_RRC_UL_GapFR2_Config_r17__ugrp_r17_ms5	= 0,
	ASN_RRC_UL_GapFR2_Config_r17__ugrp_r17_ms20	= 1,
	ASN_RRC_UL_GapFR2_Config_r17__ugrp_r17_ms40	= 2,
	ASN_RRC_UL_GapFR2_Config_r17__ugrp_r17_ms160	= 3
} e_ASN_RRC_UL_GapFR2_Config_r17__ugrp_r17;

/* UL-GapFR2-Config-r17 */
typedef struct ASN_RRC_UL_GapFR2_Config_r17 {
	long	 gapOffset_r17;
	long	 ugl_r17;
	long	 ugrp_r17;
	ASN_RRC_ServCellIndex_t	*refFR2_ServCellAsyncCA_r17	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_UL_GapFR2_Config_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ugl_r17_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ugrp_r17_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_UL_GapFR2_Config_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_UL_GapFR2_Config_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_UL_GapFR2_Config_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_UL_GapFR2_Config_r17_H_ */
#include "../asn1c/asn_internal.h"
