//
// This file is a part of UERANSIM project.
// Copyright (c) 2023 ALİ GÜNGÖR.
//
// https://github.com/aligungr/UERANSIM/
// See README, LICENSE, and CONTRIBUTING files for licensing details.
//

#include "udp_task.hpp"

#include <cstdint>
#include <cstring>
#include <set>

#include <ue/nts.hpp>
#include <utils/common.hpp>
#include <utils/constants.hpp>

static constexpr const int BUFFER_SIZE = 16384;
static constexpr const int LOOP_PERIOD = 1000;
static constexpr const int RECEIVE_TIMEOUT = 200;
static constexpr const int HEARTBEAT_THRESHOLD = 2000; // (LOOP_PERIOD + RECEIVE_TIMEOUT)'dan büyük olmalı

namespace nr::ue
{

RlsUdpTask::RlsUdpTask(TaskBase *base, RlsSharedContext *shCtx, const std::vector<std::string> &searchSpace)
    : m_base{base}, m_server{}, m_ctlTask{}, m_shCtx{shCtx}, m_searchSpace{}, m_cells{}, m_cellIdToSti{}, m_lastLoop{},
      m_cellIdCounter{}
{
    m_logger = base->logBase->makeUniqueLogger(base->config->getLoggerPrefix() + "rls-udp");

    m_server = new udp::UdpServer();

    // Search space is the list GNB IPs
    for (auto &ip : searchSpace)
        m_searchSpace.emplace_back(ip, cons::RadioLinkPort);

    m_simPos = Vector3{};

    handoverEnabled = m_base->config->useHandoverMeasFramework;

}

void RlsUdpTask::onStart()
{
}

void RlsUdpTask::onLoop()
{
    // Do a heartbeat cycle every LOOP_PERIOD milliseconds, 
    //  - send a HEARTBEAT message to all gnb IPs in the search space
    //  - check if any known cells haven't sent HEARTBEAT_ACKs for more than HEARTBEAT_THRESHOLD
    //  
    auto current = utils::CurrentTimeMillis();
    if (current - m_lastLoop > LOOP_PERIOD)
    {
        m_lastLoop = current;
        heartbeatCycle(current, m_simPos);
    }
    uint8_t buffer[BUFFER_SIZE];
    InetAddress peerAddress;

    // pull a UDP message from the server, and if one is received, 
    //  decode it as an RLS message and handle it
    int size = m_server->Receive(buffer, BUFFER_SIZE, RECEIVE_TIMEOUT, peerAddress);
    if (size > 0)
    {
        auto rlsMsg = rls::DecodeRlsMessage(OctetView{buffer, static_cast<size_t>(size)}, true);
        if (rlsMsg == nullptr)
            m_logger->err("Unable to decode RLS message");
        else
            receiveRlsPdu(peerAddress, std::move(rlsMsg));
    }
}

void RlsUdpTask::onQuit()
{
    delete m_server;
}

void RlsUdpTask::sendRlsPdu(const InetAddress &addr, const rls::RlsMessage &msg)
{
    OctetString stream;
    rls::EncodeRlsMessage(msg, stream, false);

    m_server->Send(addr, stream.data(), static_cast<size_t>(stream.length()));
}

void RlsUdpTask::send(int cellId, const rls::RlsMessage &msg)
{
    if (m_cellIdToSti.count(cellId))
    {
        auto sti = m_cellIdToSti[cellId];
        sendRlsPdu(m_cells[sti].address, msg);
    }
}

void RlsUdpTask::receiveRlsPdu(const InetAddress &addr, std::unique_ptr<rls::RlsMessage> &&msg)
{
    
    // HEARTBEAT_ACKS are from gnbs to advertise themselves
    //   they will contain:
    //    - a simulation temp identifier (STI) that is randomly generated by the gnb and should be unique across 
    //       runs of the same gnb in different simulations (avoids stale message problem)
    //    - the cellId of the gnb (if the gnb supports it; otherwise 0)
    //    - the dbm signal strength being simulated for this UE as estimated by the gnb
    if (msg->msgType == rls::EMessageType::HEARTBEAT_ACK)
    {
        int reportedCellId = static_cast<int>(msg->cellId);

        // if the STI is not in the cell map, this is a new gnb.  Add it.
        if (!m_cells.count(msg->sti))
        {
            m_cells[msg->sti].cellId = reportedCellId != 0 ? reportedCellId : ++m_cellIdCounter;  // this ternary is to handle the case where the gnb doesn't support cellId in the header; 
                                                                                                  //   in that case we generate a UE-local cellId for it
            m_cellIdToSti[m_cells[msg->sti].cellId] = msg->sti;
        }
        // if the STI is in the cell map, but the cellId in the message is different from the cellId in the map, 
        //  then update the cellId in the map with the new value from the message (this shouldn't happen)
        else if (reportedCellId != 0 && m_cells[msg->sti].cellId != reportedCellId)
        {
            m_cellIdToSti.erase(m_cells[msg->sti].cellId);
            m_cells[msg->sti].cellId = reportedCellId;
            m_cellIdToSti[reportedCellId] = msg->sti;
        }

        // legacy dbm process
        //int oldDbm = INT32_MIN;
        //if (m_cells.count(msg->sti))
        //    oldDbm = m_cells[msg->sti].dbm;

        // update the cell info in the cell map with the provided address, 
        //  set its last seen time to now
        m_cells[msg->sti].address = addr;
        m_cells[msg->sti].lastSeen = utils::CurrentTimeMillis();

        // dbm update
        int newDbm = ((const rls::RlsHeartBeatAck &)*msg).dbm;
        updateMeasurements(newDbm, reportedCellId);

        // Legacy process used m_cells to track dbm
        // m_cells[msg->sti].dbm = newDbm;

        // // if the signal strength has changed, push a SIGNAL_CHANGED message 
        // //  to the control task with the cellId
        // if (oldDbm != newDbm)
        //     onSignalChangeOrLost(m_cells[msg->sti].cellId);
        return;
    }


    // if not a heartbeat ack, and the STI is not in the cell map, 
    //  then ignore the message (could be a prior failed simulation)
    if (!m_cells.count(msg->sti))
    {
        m_logger->warn("Received RLS message with unknown STI %lu, but handover measurement framework is enabled, so ignoring STI and processing message anyway", msg->sti);

        return;
    }

    // for PDU_TRANSMISSION and other messages, forward to control task with cellId info
    auto w = std::make_unique<NmUeRlsToRls>(NmUeRlsToRls::RECEIVE_RLS_MESSAGE);
    if (msg->cellId != 0)
        w->cellId = static_cast<int>(msg->cellId);
    else if (m_cells.count(msg->sti))
        w->cellId = m_cells[msg->sti].cellId;
    else
        w->cellId = 0;

    w->msg = std::move(msg);
    m_ctlTask->push(std::move(w));
}

void RlsUdpTask::onSignalChangeOrLost(int cellId)
{
    int dbm = INT32_MIN;
    if (m_cellIdToSti.count(cellId))
    {
        auto sti = m_cellIdToSti[cellId];
        dbm = m_cells[sti].dbm;
    }

    auto w = std::make_unique<NmUeRlsToRls>(NmUeRlsToRls::SIGNAL_CHANGED);
    w->cellId = cellId;
    w->dbm = dbm;
    m_ctlTask->push(std::move(w));
}

void RlsUdpTask::heartbeatCycle(uint64_t time, const Vector3 &simPos)
{
    std::set<std::pair<uint64_t, int>> toRemove;

    // ACK check - loop through each known cell (in m_cells map)
    //  if it hasn't been "seen" (no heartbeat ack received) for more than HEARTBEAT_THRESHOLD, 
    //  mark it for removal
    for (auto &cell : m_cells)
    {
        auto delta = time - cell.second.lastSeen;
        if (delta > HEARTBEAT_THRESHOLD)
            toRemove.insert({cell.first, cell.second.cellId});
    }

    // remove from cell trackers
    {
        // write lock for cellDbMeas since we're modifying it based on the removed cells
        std::unique_lock lock(m_base->cellDbMeasMutex);
        for (auto cell : toRemove)
        {
            m_cells.erase(cell.first);
            m_cellIdToSti.erase(cell.second);
            m_base->cellDbMeas.erase(cell.second);
        }
    }
    // TODO: this probably needs to be removed
    //for (auto cell : toRemove)
    //    onSignalChangeOrLost(cell.second);

    // Send HEARTBEATs
    //   for all the IP addresses in the "search space", send a HEARTBEAT message 
    //   with the simulated position of the UE
    for (auto &addr : m_searchSpace)
    {
        rls::RlsHeartBeat msg{m_shCtx->sti};
        msg.simPos = simPos;
        sendRlsPdu(addr, msg);
    }
}

void RlsUdpTask::updateMeasurements(const int dbm, const int cellId)
{
    
    if (cellId != 0)
    {
        // write lock
        std::unique_lock lock(m_base->cellDbMeasMutex);
        // cell already exists in map, so update dbm
        if (m_base->cellDbMeas.count(cellId) != 0)
            m_base->cellDbMeas[cellId] = dbm;
        else
            m_base->cellDbMeas.insert({cellId, dbm});
    }
}

void RlsUdpTask::initialize(NtsTask *ctlTask)
{
    m_ctlTask = ctlTask;
}

} // namespace nr::ue
