mcc: '286'          # Mobile Country Code value
mnc: '01'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 127.0.0.1   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 127.0.0.1   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 127.0.0.1    # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 127.0.0.5
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    sd: 1

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true

# RSRP configuration:  (DEPRECATED)
#   dbValue: initial RSRP value (dBm) used in Fixed mode and as the starting fixed value
#   updateMode: Calculated (distance/path-loss based) or Fixed (ignore distance)
#rsrp:
#  dbValue: -120
#  updateMode: Calculated

# rf link parameters to calculate RSRP values sent to UEs
#   if updateMode is "Fixed", only the provided rsrpDbValue is used and the other parameters are ignored.
#     Note: this value can be manually changed during operation through the command interface to simulate changes in RF conditions.
#   if updateMode is "Calculated", the RSRP is calculated  using the carrier frequency, tx power, and antenna gains.
rfLink:
  # updateMode: Fixed
  # rsrpDbValue: -120
  updateMode: Calculated
  # typical values for a LEO satellite gNB
  carrFrequencyHz: 10.7e9   # carrier frequency (Hz)
  txPowerDbm: 43.0          # Radiated (transmit) power (dBm)
  txGainDbi: 35.0           # gNB Transmit antenna gain (dBi)
  ueRxGainDbi: 25.0         # UE Receive antenna gain (dBi)
  # typical values for a terrestrial gNB (macro)
  # carrFrequencyHz: 3.5e9   # carrier frequency (Hz)
  # txPowerDbm: 15.0          # Radiated (transmit) power (dBm)
  # txGainDbi: 15.0           # gNB Transmit antenna gain (dBi)
  # ueRxGainDbi: 0.0         # UE Receive antenna gain (dBi)

# RLS loop/timer settings (ms).
#  If these are omitted, default values will be used:
#   LOOP_COUNTER: 1000
#   RECEIVE_TIMEOUT: 200
#   TIMER_PERIOD_ACK_SEND: 1500
#   TIMER_PERIOD_ACK_CONTROL: 2250
# (HEARTBEAT_THRESHOLD is always computed as LOOP_COUNTER + RECEIVE_TIMEOUT).
# Ensure these values match the values set for the UE, otherwise there will be timeout issues causing UE registration flapping.
rls:
  LOOP_COUNTER: 200
  RECEIVE_TIMEOUT: 100
  TIMER_PERIOD_ACK_SEND: 300
  TIMER_PERIOD_ACK_CONTROL: 500

# gNB geographic position (lat/lon/alt, WGS-84)
# Used as the static terrestrial position or as fallback
#     when no position information has been received in satellite (NTN) mode
position:
  latitude: 33.7490     # degrees North
  longitude: -84.3880   # degrees East
#  altitude: 550000.0    # meters above Earth surface ellipsoid (typical LEO orbit - 550km)
  altitude: 500.0      # meters above Earth surface ellipsoid (typical for terrestrial gNB macro cell)


# Neighbor cells for handover
#   Note: these can be updated at runtime through the command interface to simulate changes in neighbor cells.
neighborList:
  - nci: '0x000000020'
    idLength: 32
    tac: 1
    ipAddress: 127.0.0.2
    # interface to use for handover signaling with this neighbor (N2 or Xn).
    handoverInterface: N2
  - nci: '0x000000030'
    idLength: 32
    tac: 1
    ipAddress: 127.0.0.3
    # interface to use for handover signaling with this neighbor (N2 or Xn).
    handoverInterface: N2

# Xn interface configuration (used for handover signaling with neighbor cells that support Xn handover)
xn:
  enabled: false
  bindAddress: 127.0.0.1
  bindPort: 9487
  requestTimeoutMs: 1000
  contextTtlMs: 5000
  fallbackToN2: true


# Handover measurement/CHO configuration.
# events: classic (non-CHO) events always sent to UEs.
# if choEnbaled is true, then Conditional Handover (CHO) events in choEvents will also be sent to UEs.
# choEvents: CHO profiles with a condition group (AND within group).
# CHO priority is derived from target candidate ranking (best=1).
# TTT values are an enum that take one of the following values: "ms0", "ms40", "ms64", "ms80", "ms100", "ms128", "ms160", "ms256", "ms320", "ms480", "ms512", "ms640", "ms1024", "ms1280", "ms2560", "ms5120"
handover:
  events:
    - eventType: A3
      a3OffsetDb: 3
      a3hysteresisDb: 1
      ttt: ms100

  choEnabled: false
  choDefaultProfileId: 1  # default profile ID to use for CHO candidates if not overridden

  choCandidateProfiles:
    - candidateProfileId: 1
      # targetCellId is either a specific cell ID (e.g. '0x000000020') which must be on the neighbor list
      #   or "calculated", which causes the gNB to use the cell ID of the best candidate neighbor cell based on distance
      targetCellId: '0x000000020'
      conditions:
        - eventType: condD1
          condD1DistanceThreshold1: 1200
          condD1DistanceThreshold2: 2000
          condD1ReferenceLocation1:
            latitude: 37.7749
            longitude: -122.4194
          condD1ReferenceLocation2:
            latitude: 37.7749
            longitude: -122.4194
          condD1HysteresisM: 100
          ttt: ms100

    - candidateProfileId: 2
      #   for NTN, this always be calculated, since the target cell will change based on satellite movement
      targetCellId: calculated
      conditions:
        - eventType: condT1
          threhsoldSecTS: 0
          durationSec: 6000

        
# NTN (non-Terrestrial Network) configuration
ntn:

  # setting ntnEnabled to false will ignore all other ntn parameters and cause gnb to 
  #   operate in regular (terrestrial) mode
  ntnEnabled: false

  # Two Line Element (TLE) set for the satellite, used to calculate satellite position.
  tle:
    # Samples - same epoch, nadir: lat=45N, lon=90W
    #  Sat 1: Zenith (Elevation ~90 deg)
    line1: '1 99991U 26106A   26106.97180556  .00000000  00000-0  00000-0 0  9993'
    line2: '2 99991  45.0000 270.0000 0001000   0.0000  90.0000 15.00000000    14'
    #    Sat 2: Rising (Elevation ~30 deg)
    # line1: '1 99992U 26106B   26106.97180556  .00000000  00000-0  00000-0 0  9995'
    # line2: '2 99992  45.0000 270.0000 0001000   0.0000  70.0000 15.00000000    12'
    #    Sat 3: Trailing (Elevation ~10 deg)
    # line1: '1 99993U 26106C   26106.97180556  .00000000  00000-0  00000-0 0  9997'
    # line2: '2 99993  45.0000 270.0000 0001000   0.0000  50.0000 15.00000000    10'
    #    Sat 4: Distant 1 (Below Horizon)
    # line1: '1 99994U 26106D   26106.97180556  .00000000  00000-0  00000-0 0  9999'
    # line2: '2 99994  45.0000 270.0000 0001000   0.0000  30.0000 15.00000000    18'
    #    Sat 5: Distant 2 (Below Horizon)
    # line1: '1 99995U 26106E   26106.97180556  .00000000  00000-0  00000-0 0  9990'
    # line2: '2 99995  45.0000 270.0000 0001000   0.0000  10.0000 15.00000000    16'

  # Satellite time control for NTN simulation.
  timeWarp:
    # startEpoch must be in TLE epoch format YYDDD.DDDDDDDD
    startEpoch: "26106.97180556"   # lines up with the TLE epoch
    # startCondition controls whether the satellite time starts immediately (moving) 
    #   or waits for a trigger (paused).
    startCondition: moving
    # tickScaling controls the speed of time progression relative to real time
    #   tickScaling=2.0 means satellite time progresses twice as fast as real time.
    #   tickScaling=0.5 means satellite time progresses at half the speed of real time.
    tickScaling: 1.0

  # minimum elevation angle (degrees) for the satellite to be considered 
  #   "visible" to the UE - used for CHO conditions
  elevationMinDeg: 20   

  # controls how SIB19 is configured/sent
  sib19:
    # sib19on must be true to enable SIB19 transmissions
    sib19on: true
    # send period (in ms)
    sib19timing: 1000
    # ephemeris type ('orbital' or 'pos-vel')
    ephType: orbital
    # these params are not used in the simulation, set to default values for completeness
    kOffset: 0
    taCommon: 0
    taCommonDrift: 0
    # taCommonDriftVariation: 0
    # ulSyncValidityDuration: 60
    # cellSpecificKoffset: 0
    # polarization: 0          # 0: RHCP, 1: LHCP, 2: LINEAR
    # taDrift: 0
