/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn1-definitions/ngap-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/ngap -fprefix=ASN_NGAP_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_NGAP_BroadcastCompletedAreaList_H_
#define	_ASN_NGAP_BroadcastCompletedAreaList_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_NGAP_BroadcastCompletedAreaList_PR {
	ASN_NGAP_BroadcastCompletedAreaList_PR_NOTHING,	/* No components present */
	ASN_NGAP_BroadcastCompletedAreaList_PR_cellIDBroadcastEUTRA,
	ASN_NGAP_BroadcastCompletedAreaList_PR_tAIBroadcastEUTRA,
	ASN_NGAP_BroadcastCompletedAreaList_PR_emergencyAreaIDBroadcastEUTRA,
	ASN_NGAP_BroadcastCompletedAreaList_PR_cellIDBroadcastNR,
	ASN_NGAP_BroadcastCompletedAreaList_PR_tAIBroadcastNR,
	ASN_NGAP_BroadcastCompletedAreaList_PR_emergencyAreaIDBroadcastNR,
	ASN_NGAP_BroadcastCompletedAreaList_PR_choice_Extensions
} ASN_NGAP_BroadcastCompletedAreaList_PR;

/* Forward declarations */
struct ASN_NGAP_CellIDBroadcastEUTRA;
struct ASN_NGAP_TAIBroadcastEUTRA;
struct ASN_NGAP_EmergencyAreaIDBroadcastEUTRA;
struct ASN_NGAP_CellIDBroadcastNR;
struct ASN_NGAP_TAIBroadcastNR;
struct ASN_NGAP_EmergencyAreaIDBroadcastNR;
struct ASN_NGAP_ProtocolIE_SingleContainer_13558P5;

/* BroadcastCompletedAreaList */
typedef struct ASN_NGAP_BroadcastCompletedAreaList {
	ASN_NGAP_BroadcastCompletedAreaList_PR present;
	union ASN_NGAP_BroadcastCompletedAreaList_u {
		struct ASN_NGAP_CellIDBroadcastEUTRA	*cellIDBroadcastEUTRA;
		struct ASN_NGAP_TAIBroadcastEUTRA	*tAIBroadcastEUTRA;
		struct ASN_NGAP_EmergencyAreaIDBroadcastEUTRA	*emergencyAreaIDBroadcastEUTRA;
		struct ASN_NGAP_CellIDBroadcastNR	*cellIDBroadcastNR;
		struct ASN_NGAP_TAIBroadcastNR	*tAIBroadcastNR;
		struct ASN_NGAP_EmergencyAreaIDBroadcastNR	*emergencyAreaIDBroadcastNR;
		struct ASN_NGAP_ProtocolIE_SingleContainer_13558P5	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_BroadcastCompletedAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_BroadcastCompletedAreaList;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_NGAP_BroadcastCompletedAreaList_H_ */
#include "../asn1c/asn_internal.h"
