/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn1-definitions/ngap-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/ngap -fprefix=ASN_NGAP_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_NGAP_SNPNTAIListforMDT.h"

#include "ASN_NGAP_SNPNTAIListforMDTItem.h"
asn_per_constraints_t asn_PER_type_ASN_NGAP_SNPNTAIListforMDT_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ASN_NGAP_SNPNTAIListforMDT_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_NGAP_SNPNTAIListforMDTItem,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_NGAP_SNPNTAIListforMDT_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_SNPNTAIListforMDT_specs_1 = {
	sizeof(struct ASN_NGAP_SNPNTAIListforMDT),
	offsetof(struct ASN_NGAP_SNPNTAIListforMDT, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_SNPNTAIListforMDT = {
	"SNPNTAIListforMDT",
	"SNPNTAIListforMDT",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ASN_NGAP_SNPNTAIListforMDT_tags_1,
	sizeof(asn_DEF_ASN_NGAP_SNPNTAIListforMDT_tags_1)
		/sizeof(asn_DEF_ASN_NGAP_SNPNTAIListforMDT_tags_1[0]), /* 1 */
	asn_DEF_ASN_NGAP_SNPNTAIListforMDT_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_NGAP_SNPNTAIListforMDT_tags_1)
		/sizeof(asn_DEF_ASN_NGAP_SNPNTAIListforMDT_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_ASN_NGAP_SNPNTAIListforMDT_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_ASN_NGAP_SNPNTAIListforMDT_1,
	1,	/* Single element */
	&asn_SPC_ASN_NGAP_SNPNTAIListforMDT_specs_1	/* Additional specs */
};

