/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn1-definitions/ngap-rel18-v18_9.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/ngap -fprefix=ASN_NGAP_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_NGAP_FiveG_ProSeAuthorized_H_
#define	_ASN_NGAP_FiveG_ProSeAuthorized_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_NGAP_FiveGProSeDirectDiscovery.h"
#include "ASN_NGAP_FiveGProSeDirectCommunication.h"
#include "ASN_NGAP_FiveGProSeLayer2UEtoNetworkRelay.h"
#include "ASN_NGAP_FiveGProSeLayer3UEtoNetworkRelay.h"
#include "ASN_NGAP_FiveGProSeLayer2RemoteUE.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_NGAP_ProtocolExtensionContainer_13606P106;

/* FiveG-ProSeAuthorized */
typedef struct ASN_NGAP_FiveG_ProSeAuthorized {
	ASN_NGAP_FiveGProSeDirectDiscovery_t	*fiveGProSeDirectDiscovery	/* OPTIONAL */;
	ASN_NGAP_FiveGProSeDirectCommunication_t	*fiveGProSeDirectCommunication	/* OPTIONAL */;
	ASN_NGAP_FiveGProSeLayer2UEtoNetworkRelay_t	*fiveGProSeLayer2UEtoNetworkRelay	/* OPTIONAL */;
	ASN_NGAP_FiveGProSeLayer3UEtoNetworkRelay_t	*fiveGProSeLayer3UEtoNetworkRelay	/* OPTIONAL */;
	ASN_NGAP_FiveGProSeLayer2RemoteUE_t	*fiveGProSeLayer2RemoteUE	/* OPTIONAL */;
	struct ASN_NGAP_ProtocolExtensionContainer_13606P106	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_FiveG_ProSeAuthorized_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_FiveG_ProSeAuthorized;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_NGAP_FiveG_ProSeAuthorized_H_ */
#include "../asn1c/asn_internal.h"
