/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Descriptions"
 * 	found in "/home/joe/repos/UERANSIM-Handover/asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D /tmp/claude-1000/-home-joe-repos-UERANSIM-Handover/10b80aa1-9a4a-4ef1-b127-6dd0b1e6f604/scratchpad/gen3/out/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_XNAP_InitiatingMessage.h"

static const long asn_VAL_1_ASN_XNAP_id_handoverPreparation = 0;
static const long asn_VAL_1_ASN_XNAP_reject = 0;
static const long asn_VAL_2_ASN_XNAP_id_retrieveUEContext = 3;
static const long asn_VAL_2_ASN_XNAP_reject = 0;
static const long asn_VAL_3_ASN_XNAP_id_sNGRANnodeAdditionPreparation = 7;
static const long asn_VAL_3_ASN_XNAP_reject = 0;
static const long asn_VAL_4_ASN_XNAP_id_mNGRANnodeinitiatedSNGRANnodeModificationPreparation = 9;
static const long asn_VAL_4_ASN_XNAP_reject = 0;
static const long asn_VAL_5_ASN_XNAP_id_sNGRANnodeinitiatedSNGRANnodeModificationPreparation = 10;
static const long asn_VAL_5_ASN_XNAP_reject = 0;
static const long asn_VAL_6_ASN_XNAP_id_mNGRANnodeinitiatedSNGRANnodeRelease = 11;
static const long asn_VAL_6_ASN_XNAP_reject = 0;
static const long asn_VAL_7_ASN_XNAP_id_sNGRANnodeinitiatedSNGRANnodeRelease = 12;
static const long asn_VAL_7_ASN_XNAP_reject = 0;
static const long asn_VAL_8_ASN_XNAP_id_sNGRANnodeChange = 14;
static const long asn_VAL_8_ASN_XNAP_reject = 0;
static const long asn_VAL_9_ASN_XNAP_id_xnRemoval = 16;
static const long asn_VAL_9_ASN_XNAP_reject = 0;
static const long asn_VAL_10_ASN_XNAP_id_xnSetup = 17;
static const long asn_VAL_10_ASN_XNAP_reject = 0;
static const long asn_VAL_11_ASN_XNAP_id_nGRANnodeConfigurationUpdate = 18;
static const long asn_VAL_11_ASN_XNAP_reject = 0;
static const long asn_VAL_12_ASN_XNAP_id_e_UTRA_NR_CellResourceCoordination = 25;
static const long asn_VAL_12_ASN_XNAP_reject = 0;
static const long asn_VAL_13_ASN_XNAP_id_cellActivation = 19;
static const long asn_VAL_13_ASN_XNAP_reject = 0;
static const long asn_VAL_14_ASN_XNAP_id_reset = 20;
static const long asn_VAL_14_ASN_XNAP_reject = 0;
static const long asn_VAL_15_ASN_XNAP_id_resourceStatusReportingInitiation = 34;
static const long asn_VAL_15_ASN_XNAP_reject = 0;
static const long asn_VAL_16_ASN_XNAP_id_mobilitySettingsChange = 36;
static const long asn_VAL_16_ASN_XNAP_reject = 0;
static const long asn_VAL_17_ASN_XNAP_id_iABTransportMigrationManagement = 44;
static const long asn_VAL_17_ASN_XNAP_reject = 0;
static const long asn_VAL_18_ASN_XNAP_id_iABTransportMigrationModification = 45;
static const long asn_VAL_18_ASN_XNAP_reject = 0;
static const long asn_VAL_19_ASN_XNAP_id_iABResourceCoordination = 46;
static const long asn_VAL_19_ASN_XNAP_reject = 0;
static const long asn_VAL_20_ASN_XNAP_id_partialUEContextTransfer = 49;
static const long asn_VAL_20_ASN_XNAP_reject = 0;
static const long asn_VAL_21_ASN_XNAP_id_dataCollectionReportingInitiation = 51;
static const long asn_VAL_21_ASN_XNAP_reject = 0;
static const long asn_VAL_22_ASN_XNAP_id_sNStatusTransfer = 1;
static const long asn_VAL_22_ASN_XNAP_ignore = 1;
static const long asn_VAL_23_ASN_XNAP_id_handoverCancel = 2;
static const long asn_VAL_23_ASN_XNAP_ignore = 1;
static const long asn_VAL_24_ASN_XNAP_id_rANPaging = 4;
static const long asn_VAL_24_ASN_XNAP_reject = 0;
static const long asn_VAL_25_ASN_XNAP_id_xnUAddressIndication = 5;
static const long asn_VAL_25_ASN_XNAP_reject = 0;
static const long asn_VAL_26_ASN_XNAP_id_uEContextRelease = 6;
static const long asn_VAL_26_ASN_XNAP_reject = 0;
static const long asn_VAL_27_ASN_XNAP_id_sNGRANnodeReconfigurationCompletion = 8;
static const long asn_VAL_27_ASN_XNAP_reject = 0;
static const long asn_VAL_28_ASN_XNAP_id_sNGRANnodeCounterCheck = 13;
static const long asn_VAL_28_ASN_XNAP_reject = 0;
static const long asn_VAL_29_ASN_XNAP_id_rRCTransfer = 15;
static const long asn_VAL_29_ASN_XNAP_reject = 0;
static const long asn_VAL_30_ASN_XNAP_id_errorIndication = 21;
static const long asn_VAL_30_ASN_XNAP_ignore = 1;
static const long asn_VAL_31_ASN_XNAP_id_privateMessage = 22;
static const long asn_VAL_31_ASN_XNAP_ignore = 1;
static const long asn_VAL_32_ASN_XNAP_id_notificationControl = 23;
static const long asn_VAL_32_ASN_XNAP_ignore = 1;
static const long asn_VAL_33_ASN_XNAP_id_activityNotification = 24;
static const long asn_VAL_33_ASN_XNAP_ignore = 1;
static const long asn_VAL_34_ASN_XNAP_id_secondaryRATDataUsageReport = 26;
static const long asn_VAL_34_ASN_XNAP_reject = 0;
static const long asn_VAL_35_ASN_XNAP_id_deactivateTrace = 27;
static const long asn_VAL_35_ASN_XNAP_ignore = 1;
static const long asn_VAL_36_ASN_XNAP_id_traceStart = 28;
static const long asn_VAL_36_ASN_XNAP_ignore = 1;
static const long asn_VAL_37_ASN_XNAP_id_handoverSuccess = 29;
static const long asn_VAL_37_ASN_XNAP_ignore = 1;
static const long asn_VAL_38_ASN_XNAP_id_conditionalHandoverCancel = 30;
static const long asn_VAL_38_ASN_XNAP_ignore = 1;
static const long asn_VAL_39_ASN_XNAP_id_earlyStatusTransfer = 31;
static const long asn_VAL_39_ASN_XNAP_ignore = 1;
static const long asn_VAL_40_ASN_XNAP_id_failureIndication = 32;
static const long asn_VAL_40_ASN_XNAP_ignore = 1;
static const long asn_VAL_41_ASN_XNAP_id_handoverReport = 33;
static const long asn_VAL_41_ASN_XNAP_ignore = 1;
static const long asn_VAL_42_ASN_XNAP_id_resourceStatusReporting = 35;
static const long asn_VAL_42_ASN_XNAP_ignore = 1;
static const long asn_VAL_43_ASN_XNAP_id_accessAndMobilityIndication = 37;
static const long asn_VAL_43_ASN_XNAP_ignore = 1;
static const long asn_VAL_44_ASN_XNAP_id_cellTrafficTrace = 38;
static const long asn_VAL_44_ASN_XNAP_ignore = 1;
static const long asn_VAL_45_ASN_XNAP_id_RANMulticastGroupPaging = 39;
static const long asn_VAL_45_ASN_XNAP_reject = 0;
static const long asn_VAL_46_ASN_XNAP_id_scgFailureInformationReport = 40;
static const long asn_VAL_46_ASN_XNAP_ignore = 1;
static const long asn_VAL_47_ASN_XNAP_id_scgFailureTransfer = 42;
static const long asn_VAL_47_ASN_XNAP_ignore = 1;
static const long asn_VAL_48_ASN_XNAP_id_f1CTrafficTransfer = 43;
static const long asn_VAL_48_ASN_XNAP_reject = 0;
static const long asn_VAL_49_ASN_XNAP_id_retrieveUEContextConfirm = 47;
static const long asn_VAL_49_ASN_XNAP_reject = 0;
static const long asn_VAL_50_ASN_XNAP_id_cPCCancel = 48;
static const long asn_VAL_50_ASN_XNAP_ignore = 1;
static const long asn_VAL_51_ASN_XNAP_id_rachIndication = 50;
static const long asn_VAL_51_ASN_XNAP_ignore = 1;
static const long asn_VAL_52_ASN_XNAP_id_dataCollectionReporting = 52;
static const long asn_VAL_52_ASN_XNAP_ignore = 1;
static const asn_ioc_cell_t asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1_rows[] = {
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_HandoverRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_HandoverRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_HandoverPreparationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_1_ASN_XNAP_id_handoverPreparation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_1_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RetrieveUEContextRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_RetrieveUEContextResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_RetrieveUEContextFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_2_ASN_XNAP_id_retrieveUEContext },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_2_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeAdditionRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeAdditionRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeAdditionRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_3_ASN_XNAP_id_sNGRANnodeAdditionPreparation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_3_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_4_ASN_XNAP_id_mNGRANnodeinitiatedSNGRANnodeModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_4_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationConfirm },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_5_ASN_XNAP_id_sNGRANnodeinitiatedSNGRANnodeModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_5_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_6_ASN_XNAP_id_mNGRANnodeinitiatedSNGRANnodeRelease },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_6_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseConfirm },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_7_ASN_XNAP_id_sNGRANnodeinitiatedSNGRANnodeRelease },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_7_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeChangeRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeChangeConfirm },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeChangeRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_8_ASN_XNAP_id_sNGRANnodeChange },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_8_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_XnRemovalRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_XnRemovalResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_XnRemovalFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_9_ASN_XNAP_id_xnRemoval },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_9_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_XnSetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_XnSetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_XnSetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_10_ASN_XNAP_id_xnSetup },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_10_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_NGRANNodeConfigurationUpdate },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_NGRANNodeConfigurationUpdateAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_NGRANNodeConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_11_ASN_XNAP_id_nGRANnodeConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_11_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_E_UTRA_NR_CellResourceCoordinationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_E_UTRA_NR_CellResourceCoordinationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_12_ASN_XNAP_id_e_UTRA_NR_CellResourceCoordination },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_12_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_CellActivationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_CellActivationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_CellActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_13_ASN_XNAP_id_cellActivation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_13_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ResetRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_ResetResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_14_ASN_XNAP_id_reset },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_14_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ResourceStatusRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_ResourceStatusResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_ResourceStatusFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_15_ASN_XNAP_id_resourceStatusReportingInitiation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_15_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_MobilityChangeRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_MobilityChangeAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_MobilityChangeFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_16_ASN_XNAP_id_mobilitySettingsChange },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_16_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationManagementRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationManagementResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationManagementReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_17_ASN_XNAP_id_iABTransportMigrationManagement },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_17_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationModificationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationModificationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_18_ASN_XNAP_id_iABTransportMigrationModification },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_18_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_IABResourceCoordinationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_IABResourceCoordinationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_19_ASN_XNAP_id_iABResourceCoordination },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_19_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_PartialUEContextTransfer },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_PartialUEContextTransferAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_PartialUEContextTransferFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_20_ASN_XNAP_id_partialUEContextTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_20_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_DataCollectionRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_DataCollectionResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_DataCollectionFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_21_ASN_XNAP_id_dataCollectionReportingInitiation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_21_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNStatusTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_22_ASN_XNAP_id_sNStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_22_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_HandoverCancel },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_23_ASN_XNAP_id_handoverCancel },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_23_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RANPaging },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_24_ASN_XNAP_id_rANPaging },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_24_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_XnUAddressIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_25_ASN_XNAP_id_xnUAddressIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_25_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_UEContextRelease },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_26_ASN_XNAP_id_uEContextRelease },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_26_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeReconfigurationComplete },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_27_ASN_XNAP_id_sNGRANnodeReconfigurationCompletion },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_27_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeCounterCheckRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_28_ASN_XNAP_id_sNGRANnodeCounterCheck },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_28_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RRCTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_29_ASN_XNAP_id_rRCTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_29_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ErrorIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_30_ASN_XNAP_id_errorIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_30_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_PrivateMessage },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_31_ASN_XNAP_id_privateMessage },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_31_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_NotificationControlIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_32_ASN_XNAP_id_notificationControl },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_32_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ActivityNotification },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_33_ASN_XNAP_id_activityNotification },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_33_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SecondaryRATDataUsageReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_34_ASN_XNAP_id_secondaryRATDataUsageReport },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_34_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_DeactivateTrace },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_35_ASN_XNAP_id_deactivateTrace },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_35_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_TraceStart },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_36_ASN_XNAP_id_traceStart },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_36_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_HandoverSuccess },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_37_ASN_XNAP_id_handoverSuccess },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_37_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ConditionalHandoverCancel },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_38_ASN_XNAP_id_conditionalHandoverCancel },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_38_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_EarlyStatusTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_39_ASN_XNAP_id_earlyStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_39_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_FailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_40_ASN_XNAP_id_failureIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_40_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_HandoverReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_41_ASN_XNAP_id_handoverReport },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_41_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ResourceStatusUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_42_ASN_XNAP_id_resourceStatusReporting },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_42_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_AccessAndMobilityIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_43_ASN_XNAP_id_accessAndMobilityIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_43_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_CellTrafficTrace },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_44_ASN_XNAP_id_cellTrafficTrace },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_44_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RANMulticastGroupPaging },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_45_ASN_XNAP_id_RANMulticastGroupPaging },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_45_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ScgFailureInformationReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_46_ASN_XNAP_id_scgFailureInformationReport },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_46_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ScgFailureTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_47_ASN_XNAP_id_scgFailureTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_47_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_F1CTrafficTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_48_ASN_XNAP_id_f1CTrafficTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_48_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RetrieveUEContextConfirm },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_49_ASN_XNAP_id_retrieveUEContextConfirm },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_49_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_CPCCancel },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_50_ASN_XNAP_id_cPCCancel },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_50_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RachIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_51_ASN_XNAP_id_rachIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_51_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_DataCollectionUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_52_ASN_XNAP_id_dataCollectionReporting },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_52_ASN_XNAP_ignore }
};
static const asn_ioc_set_t asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1[] = {
	52, 5, asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1_rows
};
static int
memb_ASN_XNAP_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_ASN_XNAP_InitiatingMessage_ASN_XNAP_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row;
	size_t presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct ASN_XNAP_InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    /*
	     * The CHOICE which carries the open type value only contains the
	     * rows which actually define a type for this column, so count those
	     * rows to derive the CHOICE presence index. A row which selects no
	     * type leaves both result fields cleared, which the decoders treat
	     * as a decode failure.
	     */
	    if(type_cell->type_descriptor) presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        if(type_cell->type_descriptor) {
	            result.type_descriptor = type_cell->type_descriptor;
	            result.presence_index = presence_index;
	        }
	        break;
	    }
	}
	
	return result;
}

static int
memb_ASN_XNAP_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_ASN_XNAP_InitiatingMessage_ASN_XNAP_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 0; /* &InitiatingMessage */
	size_t row;
	size_t presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct ASN_XNAP_InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    /*
	     * The CHOICE which carries the open type value only contains the
	     * rows which actually define a type for this column, so count those
	     * rows to derive the CHOICE presence index. A row which selects no
	     * type leaves both result fields cleared, which the decoders treat
	     * as a decode failure.
	     */
	    if(type_cell->type_descriptor) presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        if(type_cell->type_descriptor) {
	            result.type_descriptor = type_cell->type_descriptor;
	            result.presence_index = presence_index;
	        }
	        break;
	    }
	}
	
	return result;
}

static int
memb_ASN_XNAP_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_per_constraints_t asn_PER_memb_ASN_XNAP_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_XNAP_value_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.HandoverRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_HandoverRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.RetrieveUEContextRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_RetrieveUEContextRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RetrieveUEContextRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNodeAdditionRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeAdditionRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeAdditionRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNodeModificationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeModificationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeModificationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNodeModificationRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeModificationRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeModificationRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNodeReleaseRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeReleaseRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeReleaseRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNodeReleaseRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeReleaseRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeReleaseRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNodeChangeRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeChangeRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeChangeRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.XnRemovalRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_XnRemovalRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"XnRemovalRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.XnSetupRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_XnSetupRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"XnSetupRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.NGRANNodeConfigurationUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_NGRANNodeConfigurationUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"NGRANNodeConfigurationUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.E_UTRA_NR_CellResourceCoordinationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_E_UTRA_NR_CellResourceCoordinationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-UTRA-NR-CellResourceCoordinationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.CellActivationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_CellActivationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CellActivationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.ResetRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ResetRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResetRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.ResourceStatusRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ResourceStatusRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResourceStatusRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.MobilityChangeRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_MobilityChangeRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"MobilityChangeRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.IABTransportMigrationManagementRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_IABTransportMigrationManagementRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IABTransportMigrationManagementRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.IABTransportMigrationModificationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_IABTransportMigrationModificationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IABTransportMigrationModificationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.IABResourceCoordinationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_IABResourceCoordinationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IABResourceCoordinationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.PartialUEContextTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_PartialUEContextTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PartialUEContextTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.DataCollectionRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_DataCollectionRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DataCollectionRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNStatusTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNStatusTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNStatusTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.HandoverCancel),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_HandoverCancel,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverCancel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.RANPaging),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_RANPaging,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RANPaging"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.XnUAddressIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_XnUAddressIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"XnUAddressIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.UEContextRelease),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_UEContextRelease,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextRelease"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNodeReconfigurationComplete),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeReconfigurationComplete,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeReconfigurationComplete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SNodeCounterCheckRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeCounterCheckRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeCounterCheckRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.RRCTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_RRCTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RRCTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.ErrorIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ErrorIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ErrorIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.PrivateMessage),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_PrivateMessage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PrivateMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.NotificationControlIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_NotificationControlIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"NotificationControlIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.ActivityNotification),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ActivityNotification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ActivityNotification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.SecondaryRATDataUsageReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SecondaryRATDataUsageReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SecondaryRATDataUsageReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.DeactivateTrace),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_DeactivateTrace,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DeactivateTrace"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.TraceStart),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_TraceStart,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"TraceStart"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.HandoverSuccess),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_HandoverSuccess,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverSuccess"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.ConditionalHandoverCancel),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ConditionalHandoverCancel,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ConditionalHandoverCancel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.EarlyStatusTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_EarlyStatusTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"EarlyStatusTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.FailureIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_FailureIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"FailureIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.HandoverReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_HandoverReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.ResourceStatusUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ResourceStatusUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResourceStatusUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.AccessAndMobilityIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_AccessAndMobilityIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"AccessAndMobilityIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.CellTrafficTrace),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_CellTrafficTrace,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CellTrafficTrace"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.RANMulticastGroupPaging),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_RANMulticastGroupPaging,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RANMulticastGroupPaging"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.ScgFailureInformationReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ScgFailureInformationReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ScgFailureInformationReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.ScgFailureTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ScgFailureTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ScgFailureTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.F1CTrafficTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_F1CTrafficTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"F1CTrafficTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.RetrieveUEContextConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_RetrieveUEContextConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RetrieveUEContextConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.CPCCancel),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_CPCCancel,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CPCCancel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.RachIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_RachIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RachIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage__value, choice.DataCollectionUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_DataCollectionUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DataCollectionUpdate"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 51 }, /* HandoverRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 50 }, /* RetrieveUEContextRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 49 }, /* SNodeAdditionRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 48 }, /* SNodeModificationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 47 }, /* SNodeModificationRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 46 }, /* SNodeReleaseRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -6, 45 }, /* SNodeReleaseRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -7, 44 }, /* SNodeChangeRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -8, 43 }, /* XnRemovalRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -9, 42 }, /* XnSetupRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -10, 41 }, /* NGRANNodeConfigurationUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -11, 40 }, /* E-UTRA-NR-CellResourceCoordinationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -12, 39 }, /* CellActivationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -13, 38 }, /* ResetRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -14, 37 }, /* ResourceStatusRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -15, 36 }, /* MobilityChangeRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 16, -16, 35 }, /* IABTransportMigrationManagementRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 17, -17, 34 }, /* IABTransportMigrationModificationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 18, -18, 33 }, /* IABResourceCoordinationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 19, -19, 32 }, /* PartialUEContextTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 20, -20, 31 }, /* DataCollectionRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 21, -21, 30 }, /* SNStatusTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 22, -22, 29 }, /* HandoverCancel */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 23, -23, 28 }, /* RANPaging */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 24, -24, 27 }, /* XnUAddressIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 25, -25, 26 }, /* UEContextRelease */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 26, -26, 25 }, /* SNodeReconfigurationComplete */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 27, -27, 24 }, /* SNodeCounterCheckRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 28, -28, 23 }, /* RRCTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 29, -29, 22 }, /* ErrorIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 30, -30, 21 }, /* PrivateMessage */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 31, -31, 20 }, /* NotificationControlIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 32, -32, 19 }, /* ActivityNotification */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 33, -33, 18 }, /* SecondaryRATDataUsageReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 34, -34, 17 }, /* DeactivateTrace */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 35, -35, 16 }, /* TraceStart */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 36, -36, 15 }, /* HandoverSuccess */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 37, -37, 14 }, /* ConditionalHandoverCancel */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 38, -38, 13 }, /* EarlyStatusTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 39, -39, 12 }, /* FailureIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 40, -40, 11 }, /* HandoverReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 41, -41, 10 }, /* ResourceStatusUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 42, -42, 9 }, /* AccessAndMobilityIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 43, -43, 8 }, /* CellTrafficTrace */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 44, -44, 7 }, /* RANMulticastGroupPaging */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 45, -45, 6 }, /* ScgFailureInformationReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 46, -46, 5 }, /* ScgFailureTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 47, -47, 4 }, /* F1CTrafficTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 48, -48, 3 }, /* RetrieveUEContextConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 49, -49, 2 }, /* CPCCancel */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 50, -50, 1 }, /* RachIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 51, -51, 0 } /* DataCollectionUpdate */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_XNAP_value_specs_4 = {
	sizeof(struct ASN_XNAP_InitiatingMessage__value),
	offsetof(struct ASN_XNAP_InitiatingMessage__value, _asn_ctx),
	offsetof(struct ASN_XNAP_InitiatingMessage__value, present),
	sizeof(((struct ASN_XNAP_InitiatingMessage__value *)0)->present),
	asn_MAP_ASN_XNAP_value_tag2el_4,
	52,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_ASN_XNAP_value_4,
	52,	/* Elements count */
	&asn_SPC_ASN_XNAP_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_InitiatingMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProcedureCode,
		0,
		{ 0, &asn_PER_memb_ASN_XNAP_procedureCode_constr_2,  memb_ASN_XNAP_procedureCode_constraint_1 },
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_Criticality,
		select_ASN_XNAP_InitiatingMessage_ASN_XNAP_criticality_type,
		{ 0, &asn_PER_memb_ASN_XNAP_criticality_constr_3,  memb_ASN_XNAP_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_InitiatingMessage, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_value_4,
		select_ASN_XNAP_InitiatingMessage_ASN_XNAP_value_type,
		{ 0, &asn_PER_memb_ASN_XNAP_value_constr_4,  memb_ASN_XNAP_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_InitiatingMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_InitiatingMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_InitiatingMessage_specs_1 = {
	sizeof(struct ASN_XNAP_InitiatingMessage),
	offsetof(struct ASN_XNAP_InitiatingMessage, _asn_ctx),
	asn_MAP_ASN_XNAP_InitiatingMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_InitiatingMessage = {
	"InitiatingMessage",
	"InitiatingMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_InitiatingMessage_tags_1,
	sizeof(asn_DEF_ASN_XNAP_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_InitiatingMessage_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_InitiatingMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_InitiatingMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_InitiatingMessage_1,
	3,	/* Elements count */
	&asn_SPC_ASN_XNAP_InitiatingMessage_specs_1	/* Additional specs */
};

