/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "/home/joe/Downloads/3gpp-rel18/asn1/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -S /home/joe/repos/GT/cs8903/asn1c/skeletons -fprefix=ASN_XNAP_ -D xnap`
 */

#include "ASN_XNAP_SSBAreaRadioResourceStatus-List-Item.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
static int
memb_ASN_XNAP_sSBIndex_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 63)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ASN_XNAP_sSBIndex_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  63 }	/* (0..63) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, sSBIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_ASN_XNAP_sSBIndex_constraint_1,
		&asn_PER_memb_ASN_XNAP_sSBIndex_constr_2,
		0,
		"sSBIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_DL_GBR_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_DL_GBR_PRB_usage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ssb-Area-DL-GBR-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_UL_GBR_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UL_GBR_PRB_usage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ssb-Area-UL-GBR-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_dL_non_GBR_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_DL_non_GBR_PRB_usage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ssb-Area-dL-non-GBR-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_uL_non_GBR_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UL_non_GBR_PRB_usage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ssb-Area-uL-non-GBR-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_dL_Total_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_DL_Total_PRB_usage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ssb-Area-dL-Total-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_uL_Total_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UL_Total_PRB_usage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ssb-Area-uL-Total-PRB-usage"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_14246P0,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"iE-Extensions"
		},
};
static int asn_MAP_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_oms_1[] = { 7 };
static ber_tlv_tag_t asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sSBIndex at 12129 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ssb-Area-DL-GBR-PRB-usage at 12130 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ssb-Area-UL-GBR-PRB-usage at 12131 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ssb-Area-dL-non-GBR-PRB-usage at 12132 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ssb-Area-uL-non-GBR-PRB-usage at 12133 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ssb-Area-dL-Total-PRB-usage at 12134 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ssb-Area-uL-Total-PRB-usage at 12135 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* iE-Extensions at 12136 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_specs_1 = {
	sizeof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item),
	offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, _asn_ctx),
	asn_MAP_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	7,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item = {
	"SSBAreaRadioResourceStatus-List-Item",
	"SSBAreaRadioResourceStatus-List-Item",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	SEQUENCE_compare,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1,
	sizeof(asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_1,
	8,	/* Elements count */
	&asn_SPC_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_specs_1	/* Additional specs */
};

