/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_XNAP_ReportAmountMDT_H_
#define	_ASN_XNAP_ReportAmountMDT_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_ReportAmountMDT {
	ASN_XNAP_ReportAmountMDT_r1	= 0,
	ASN_XNAP_ReportAmountMDT_r2	= 1,
	ASN_XNAP_ReportAmountMDT_r4	= 2,
	ASN_XNAP_ReportAmountMDT_r8	= 3,
	ASN_XNAP_ReportAmountMDT_r16	= 4,
	ASN_XNAP_ReportAmountMDT_r32	= 5,
	ASN_XNAP_ReportAmountMDT_r64	= 6,
	ASN_XNAP_ReportAmountMDT_infinity	= 7
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_ReportAmountMDT;

/* ReportAmountMDT */
typedef long	 ASN_XNAP_ReportAmountMDT_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_ReportAmountMDT_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_ReportAmountMDT;
extern const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_ReportAmountMDT_specs_1;
asn_struct_free_f ASN_XNAP_ReportAmountMDT_free;
asn_struct_print_f ASN_XNAP_ReportAmountMDT_print;
asn_constr_check_f ASN_XNAP_ReportAmountMDT_constraint;
ber_type_decoder_f ASN_XNAP_ReportAmountMDT_decode_ber;
der_type_encoder_f ASN_XNAP_ReportAmountMDT_encode_der;
xer_type_decoder_f ASN_XNAP_ReportAmountMDT_decode_xer;
xer_type_encoder_f ASN_XNAP_ReportAmountMDT_encode_xer;
per_type_decoder_f ASN_XNAP_ReportAmountMDT_decode_uper;
per_type_encoder_f ASN_XNAP_ReportAmountMDT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_ReportAmountMDT_H_ */
#include "../asn1c/asn_internal.h"
