/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "/home/joe/Downloads/3gpp-rel18/asn1/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -S /home/joe/repos/GT/cs8903/asn1c/skeletons -fprefix=ASN_XNAP_ -D xnap`
 */

#ifndef	_ASN_XNAP_NPRACHConfiguration_H_
#define	_ASN_XNAP_NPRACHConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_NPRACHConfiguration__fdd_or_tdd_PR {
	ASN_XNAP_NPRACHConfiguration__fdd_or_tdd_PR_NOTHING,	/* No components present */
	ASN_XNAP_NPRACHConfiguration__fdd_or_tdd_PR_fdd,
	ASN_XNAP_NPRACHConfiguration__fdd_or_tdd_PR_tdd,
	ASN_XNAP_NPRACHConfiguration__fdd_or_tdd_PR_choice_extension
} ASN_XNAP_NPRACHConfiguration__fdd_or_tdd_PR;

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer_14246P0;
struct ASN_XNAP_NPRACHConfiguration_FDD;
struct ASN_XNAP_NPRACHConfiguration_TDD;
struct ASN_XNAP_ProtocolIE_Field_14202P0;

/* NPRACHConfiguration */
typedef struct ASN_XNAP_NPRACHConfiguration {
	struct ASN_XNAP_NPRACHConfiguration__fdd_or_tdd {
		ASN_XNAP_NPRACHConfiguration__fdd_or_tdd_PR present;
		union ASN_XNAP_NPRACHConfiguration__fdd_or_tdd_u {
			struct ASN_XNAP_NPRACHConfiguration_FDD	*fdd;
			struct ASN_XNAP_NPRACHConfiguration_TDD	*tdd;
			struct ASN_XNAP_ProtocolIE_Field_14202P0	*choice_extension;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} fdd_or_tdd;
	struct ASN_XNAP_ProtocolExtensionContainer_14246P0	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_NPRACHConfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NPRACHConfiguration;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_NPRACHConfiguration_H_ */
#include <asn_internal.h>
