/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "/home/joe/Downloads/3gpp-rel18/asn1/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -S /home/joe/repos/GT/cs8903/asn1c/skeletons -fprefix=ASN_XNAP_ -D xnap`
 */

#include "ASN_XNAP_NRDL-ULTransmissionPeriodicity.h"

int
ASN_XNAP_NRDL_ULTransmissionPeriodicity_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	td->compare        = asn_DEF_NativeEnumerated.compare;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
ASN_XNAP_NRDL_ULTransmissionPeriodicity_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
ASN_XNAP_NRDL_ULTransmissionPeriodicity_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
ASN_XNAP_NRDL_ULTransmissionPeriodicity_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
ASN_XNAP_NRDL_ULTransmissionPeriodicity_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
ASN_XNAP_NRDL_ULTransmissionPeriodicity_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
ASN_XNAP_NRDL_ULTransmissionPeriodicity_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_dec_rval_t
ASN_XNAP_NRDL_ULTransmissionPeriodicity_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
ASN_XNAP_NRDL_ULTransmissionPeriodicity_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

asn_enc_rval_t
ASN_XNAP_NRDL_ULTransmissionPeriodicity_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

asn_comp_rval_t * 
ASN_XNAP_NRDL_ULTransmissionPeriodicity_compare(asn_TYPE_descriptor_t *td1,
		const void *structure1,
		asn_TYPE_descriptor_t *td2,
		const void *structure2) {
	asn_comp_rval_t * res  = NULL;
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td1);
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td2);
	res = td1->compare(td1, structure1, td2, structure2);
	return res;
}

asn_dec_rval_t
ASN_XNAP_NRDL_ULTransmissionPeriodicity_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_1_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_per_constraints_t asn_PER_type_ASN_XNAP_NRDL_ULTransmissionPeriodicity_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  5,  5,  0,  17 }	/* (0..17,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_NRDL_ULTransmissionPeriodicity_value2enum_1[] = {
	{ 0,	5,	"ms0p5" },
	{ 1,	7,	"ms0p625" },
	{ 2,	3,	"ms1" },
	{ 3,	6,	"ms1p25" },
	{ 4,	3,	"ms2" },
	{ 5,	5,	"ms2p5" },
	{ 6,	3,	"ms3" },
	{ 7,	3,	"ms4" },
	{ 8,	3,	"ms5" },
	{ 9,	4,	"ms10" },
	{ 10,	4,	"ms20" },
	{ 11,	4,	"ms40" },
	{ 12,	4,	"ms60" },
	{ 13,	4,	"ms80" },
	{ 14,	5,	"ms100" },
	{ 15,	5,	"ms120" },
	{ 16,	5,	"ms140" },
	{ 17,	5,	"ms160" }
	/* This list is extensible */
};
static unsigned int asn_MAP_ASN_XNAP_NRDL_ULTransmissionPeriodicity_enum2value_1[] = {
	0,	/* ms0p5(0) */
	1,	/* ms0p625(1) */
	2,	/* ms1(2) */
	9,	/* ms10(9) */
	14,	/* ms100(14) */
	15,	/* ms120(15) */
	16,	/* ms140(16) */
	17,	/* ms160(17) */
	3,	/* ms1p25(3) */
	4,	/* ms2(4) */
	10,	/* ms20(10) */
	5,	/* ms2p5(5) */
	6,	/* ms3(6) */
	7,	/* ms4(7) */
	11,	/* ms40(11) */
	8,	/* ms5(8) */
	12,	/* ms60(12) */
	13	/* ms80(13) */
	/* This list is extensible */
};
static asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_NRDL_ULTransmissionPeriodicity_specs_1 = {
	asn_MAP_ASN_XNAP_NRDL_ULTransmissionPeriodicity_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_NRDL_ULTransmissionPeriodicity_enum2value_1,	/* N => "tag"; sorted by N */
	18,	/* Number of elements in the maps */
	19,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity = {
	"NRDL-ULTransmissionPeriodicity",
	"NRDL-ULTransmissionPeriodicity",
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_free,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_print,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_constraint,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_decode_ber,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_encode_der,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_decode_xer,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_encode_xer,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_decode_uper,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_encode_uper,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_decode_aper,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_encode_aper,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_compare,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity_tags_1,
	sizeof(asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity_tags_1[0]), /* 1 */
	&asn_PER_type_ASN_XNAP_NRDL_ULTransmissionPeriodicity_constr_1,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_NRDL_ULTransmissionPeriodicity_specs_1	/* Additional specs */
};

