/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "/home/joe/Downloads/3gpp-rel18/asn1/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -S /home/joe/repos/GT/cs8903/asn1c/skeletons -fprefix=ASN_XNAP_ -D xnap`
 */

#include "ASN_XNAP_CellMeasurementResult-Item.h"

#include "ASN_XNAP_RadioResourceStatus.h"
#include "ASN_XNAP_TNLCapacityIndicator.h"
#include "ASN_XNAP_CompositeAvailableCapacityGroup.h"
#include "ASN_XNAP_SliceAvailableCapacity.h"
#include "ASN_XNAP_RRCConnections.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_ASN_XNAP_CellMeasurementResult_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, cell_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_GlobalNG_RANCell_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cell-ID"
		},
	{ ATF_POINTER, 7, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, radioResourceStatus),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_RadioResourceStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"radioResourceStatus"
		},
	{ ATF_POINTER, 6, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, tNLCapacityIndicator),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_TNLCapacityIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tNLCapacityIndicator"
		},
	{ ATF_POINTER, 5, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, compositeAvailableCapacityGroup),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_CompositeAvailableCapacityGroup,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"compositeAvailableCapacityGroup"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, sliceAvailableCapacity),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_SliceAvailableCapacity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sliceAvailableCapacity"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, numberofActiveUEs),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_NumberofActiveUEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"numberofActiveUEs"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, rRCConnections),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_RRCConnections,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rRCConnections"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_14246P0,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"iE-Extensions"
		},
};
static int asn_MAP_ASN_XNAP_CellMeasurementResult_Item_oms_1[] = { 1, 2, 3, 4, 5, 6, 7 };
static ber_tlv_tag_t asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_CellMeasurementResult_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cell-ID at 5378 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* radioResourceStatus at 5379 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* tNLCapacityIndicator at 5380 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* compositeAvailableCapacityGroup at 5381 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sliceAvailableCapacity at 5382 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* numberofActiveUEs at 5383 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* rRCConnections at 5384 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* iE-Extensions at 5385 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_CellMeasurementResult_Item_specs_1 = {
	sizeof(struct ASN_XNAP_CellMeasurementResult_Item),
	offsetof(struct ASN_XNAP_CellMeasurementResult_Item, _asn_ctx),
	asn_MAP_ASN_XNAP_CellMeasurementResult_Item_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_CellMeasurementResult_Item_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	7,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_CellMeasurementResult_Item = {
	"CellMeasurementResult-Item",
	"CellMeasurementResult-Item",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	SEQUENCE_compare,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1,
	sizeof(asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ASN_XNAP_CellMeasurementResult_Item_1,
	8,	/* Elements count */
	&asn_SPC_ASN_XNAP_CellMeasurementResult_Item_specs_1	/* Additional specs */
};

