/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "/home/joe/Downloads/3gpp-rel18/asn1/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -S /home/joe/repos/GT/cs8903/asn1c/skeletons -fprefix=ASN_XNAP_ -D xnap`
 */

#include "ASN_XNAP_NRNRB.h"

int
ASN_XNAP_NRNRB_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	td->compare        = asn_DEF_NativeEnumerated.compare;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
ASN_XNAP_NRNRB_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
ASN_XNAP_NRNRB_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
ASN_XNAP_NRNRB_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
ASN_XNAP_NRNRB_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
ASN_XNAP_NRNRB_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
ASN_XNAP_NRNRB_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_dec_rval_t
ASN_XNAP_NRNRB_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
ASN_XNAP_NRNRB_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

asn_enc_rval_t
ASN_XNAP_NRNRB_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

asn_comp_rval_t * 
ASN_XNAP_NRNRB_compare(asn_TYPE_descriptor_t *td1,
		const void *structure1,
		asn_TYPE_descriptor_t *td2,
		const void *structure2) {
	asn_comp_rval_t * res  = NULL;
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td1);
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td2);
	res = td1->compare(td1, structure1, td2, structure2);
	return res;
}

asn_dec_rval_t
ASN_XNAP_NRNRB_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	ASN_XNAP_NRNRB_1_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_per_constraints_t asn_PER_type_ASN_XNAP_NRNRB_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  5,  5,  0,  28 }	/* (0..28,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_NRNRB_value2enum_1[] = {
	{ 0,	5,	"nrb11" },
	{ 1,	5,	"nrb18" },
	{ 2,	5,	"nrb24" },
	{ 3,	5,	"nrb25" },
	{ 4,	5,	"nrb31" },
	{ 5,	5,	"nrb32" },
	{ 6,	5,	"nrb38" },
	{ 7,	5,	"nrb51" },
	{ 8,	5,	"nrb52" },
	{ 9,	5,	"nrb65" },
	{ 10,	5,	"nrb66" },
	{ 11,	5,	"nrb78" },
	{ 12,	5,	"nrb79" },
	{ 13,	5,	"nrb93" },
	{ 14,	6,	"nrb106" },
	{ 15,	6,	"nrb107" },
	{ 16,	6,	"nrb121" },
	{ 17,	6,	"nrb132" },
	{ 18,	6,	"nrb133" },
	{ 19,	6,	"nrb135" },
	{ 20,	6,	"nrb160" },
	{ 21,	6,	"nrb162" },
	{ 22,	6,	"nrb189" },
	{ 23,	6,	"nrb216" },
	{ 24,	6,	"nrb217" },
	{ 25,	6,	"nrb245" },
	{ 26,	6,	"nrb264" },
	{ 27,	6,	"nrb270" },
	{ 28,	6,	"nrb273" },
	{ 29,	5,	"nrb33" },
	{ 30,	5,	"nrb62" },
	{ 31,	6,	"nrb124" },
	{ 32,	6,	"nrb148" },
	{ 33,	6,	"nrb248" },
	{ 34,	5,	"nrb44" },
	{ 35,	5,	"nrb58" },
	{ 36,	5,	"nrb92" },
	{ 37,	6,	"nrb119" },
	{ 38,	6,	"nrb188" },
	{ 39,	6,	"nrb242" },
	{ 40,	5,	"nrb15" }
	/* This list is extensible */
};
static unsigned int asn_MAP_ASN_XNAP_NRNRB_enum2value_1[] = {
	14,	/* nrb106(14) */
	15,	/* nrb107(15) */
	0,	/* nrb11(0) */
	37,	/* nrb119(37) */
	16,	/* nrb121(16) */
	31,	/* nrb124(31) */
	17,	/* nrb132(17) */
	18,	/* nrb133(18) */
	19,	/* nrb135(19) */
	32,	/* nrb148(32) */
	40,	/* nrb15(40) */
	20,	/* nrb160(20) */
	21,	/* nrb162(21) */
	1,	/* nrb18(1) */
	38,	/* nrb188(38) */
	22,	/* nrb189(22) */
	23,	/* nrb216(23) */
	24,	/* nrb217(24) */
	2,	/* nrb24(2) */
	39,	/* nrb242(39) */
	25,	/* nrb245(25) */
	33,	/* nrb248(33) */
	3,	/* nrb25(3) */
	26,	/* nrb264(26) */
	27,	/* nrb270(27) */
	28,	/* nrb273(28) */
	4,	/* nrb31(4) */
	5,	/* nrb32(5) */
	29,	/* nrb33(29) */
	6,	/* nrb38(6) */
	34,	/* nrb44(34) */
	7,	/* nrb51(7) */
	8,	/* nrb52(8) */
	35,	/* nrb58(35) */
	30,	/* nrb62(30) */
	9,	/* nrb65(9) */
	10,	/* nrb66(10) */
	11,	/* nrb78(11) */
	12,	/* nrb79(12) */
	36,	/* nrb92(36) */
	13	/* nrb93(13) */
	/* This list is extensible */
};
static asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_NRNRB_specs_1 = {
	asn_MAP_ASN_XNAP_NRNRB_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_NRNRB_enum2value_1,	/* N => "tag"; sorted by N */
	41,	/* Number of elements in the maps */
	30,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_ASN_XNAP_NRNRB_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NRNRB = {
	"NRNRB",
	"NRNRB",
	ASN_XNAP_NRNRB_free,
	ASN_XNAP_NRNRB_print,
	ASN_XNAP_NRNRB_constraint,
	ASN_XNAP_NRNRB_decode_ber,
	ASN_XNAP_NRNRB_encode_der,
	ASN_XNAP_NRNRB_decode_xer,
	ASN_XNAP_NRNRB_encode_xer,
	ASN_XNAP_NRNRB_decode_uper,
	ASN_XNAP_NRNRB_encode_uper,
	ASN_XNAP_NRNRB_decode_aper,
	ASN_XNAP_NRNRB_encode_aper,
	ASN_XNAP_NRNRB_compare,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ASN_XNAP_NRNRB_tags_1,
	sizeof(asn_DEF_ASN_XNAP_NRNRB_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_NRNRB_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_NRNRB_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_NRNRB_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_NRNRB_tags_1[0]), /* 1 */
	&asn_PER_type_ASN_XNAP_NRNRB_constr_1,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_NRNRB_specs_1	/* Additional specs */
};

