/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "/home/joe/repos/UERANSIM-Handover/asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D /tmp/claude-1000/-home-joe-repos-UERANSIM-Handover/10b80aa1-9a4a-4ef1-b127-6dd0b1e6f604/scratchpad/gen3/out/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_XNAP_LoggingInterval_H_
#define	_ASN_XNAP_LoggingInterval_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "../asn1c/NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_LoggingInterval {
	ASN_XNAP_LoggingInterval_ms320	= 0,
	ASN_XNAP_LoggingInterval_ms640	= 1,
	ASN_XNAP_LoggingInterval_ms1280	= 2,
	ASN_XNAP_LoggingInterval_ms2560	= 3,
	ASN_XNAP_LoggingInterval_ms5120	= 4,
	ASN_XNAP_LoggingInterval_ms10240	= 5,
	ASN_XNAP_LoggingInterval_ms20480	= 6,
	ASN_XNAP_LoggingInterval_ms30720	= 7,
	ASN_XNAP_LoggingInterval_ms40960	= 8,
	ASN_XNAP_LoggingInterval_ms61440	= 9,
	ASN_XNAP_LoggingInterval_infinity	= 10
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_LoggingInterval;

/* LoggingInterval */
typedef long	 ASN_XNAP_LoggingInterval_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_LoggingInterval_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_LoggingInterval;
extern const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_LoggingInterval_specs_1;
asn_struct_free_f ASN_XNAP_LoggingInterval_free;
asn_struct_print_f ASN_XNAP_LoggingInterval_print;
asn_constr_check_f ASN_XNAP_LoggingInterval_constraint;
ber_type_decoder_f ASN_XNAP_LoggingInterval_decode_ber;
der_type_encoder_f ASN_XNAP_LoggingInterval_encode_der;
xer_type_decoder_f ASN_XNAP_LoggingInterval_decode_xer;
xer_type_encoder_f ASN_XNAP_LoggingInterval_encode_xer;
per_type_decoder_f ASN_XNAP_LoggingInterval_decode_uper;
per_type_encoder_f ASN_XNAP_LoggingInterval_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_LoggingInterval_H_ */
#include "../asn1c/asn_internal.h"
