/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "/home/joe/Downloads/3gpp-rel18/asn1/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -S /home/joe/repos/GT/cs8903/asn1c/skeletons -fprefix=ASN_XNAP_ -D xnap`
 */

#ifndef	_ASN_XNAP_MobilityRestrictionList_H_
#define	_ASN_XNAP_MobilityRestrictionList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_PLMN-Identity.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_RAT_RestrictionsList;
struct ASN_XNAP_ForbiddenAreaList;
struct ASN_XNAP_ServiceAreaList;
struct ASN_XNAP_ProtocolExtensionContainer_14246P0;

/* MobilityRestrictionList */
typedef struct ASN_XNAP_MobilityRestrictionList {
	ASN_XNAP_PLMN_Identity_t	 serving_PLMN;
	struct ASN_XNAP_MobilityRestrictionList__equivalent_PLMNs {
		A_SEQUENCE_OF(ASN_XNAP_PLMN_Identity_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *equivalent_PLMNs;
	struct ASN_XNAP_RAT_RestrictionsList	*rat_Restrictions	/* OPTIONAL */;
	struct ASN_XNAP_ForbiddenAreaList	*forbiddenAreaInformation	/* OPTIONAL */;
	struct ASN_XNAP_ServiceAreaList	*serviceAreaInformation	/* OPTIONAL */;
	struct ASN_XNAP_ProtocolExtensionContainer_14246P0	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_MobilityRestrictionList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_MobilityRestrictionList;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_MobilityRestrictionList_H_ */
#include <asn_internal.h>
