/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_XNAP_IAB_STC_Info_Item_H_
#define	_ASN_XNAP_IAB_STC_Info_Item_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_XNAP_SSB-freqInfo.h"
#include "ASN_XNAP_SSB-subcarrierSpacing.h"
#include "ASN_XNAP_SSB-transmissionPeriodicity.h"
#include "ASN_XNAP_SSB-transmissionTimingOffset.h"
#include "ASN_XNAP_SSB-transmissionBitmap.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer_14246P213;

/* IAB-STC-Info-Item */
typedef struct ASN_XNAP_IAB_STC_Info_Item {
	ASN_XNAP_SSB_freqInfo_t	 sSB_freqInfo;
	ASN_XNAP_SSB_subcarrierSpacing_t	 sSB_subcarrierSpacing;
	ASN_XNAP_SSB_transmissionPeriodicity_t	 sSB_transmissionPeriodicity;
	ASN_XNAP_SSB_transmissionTimingOffset_t	 sSB_transmissionTimingOffset;
	ASN_XNAP_SSB_transmissionBitmap_t	 sSB_transmissionBitmap;
	struct ASN_XNAP_ProtocolExtensionContainer_14246P213	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_IAB_STC_Info_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_IAB_STC_Info_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_IAB_STC_Info_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_XNAP_IAB_STC_Info_Item_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_IAB_STC_Info_Item_H_ */
#include "../asn1c/asn_internal.h"
