/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_XNAP_PDUSetQoSInformation.h"

#include "ASN_XNAP_PacketErrorRate.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_ASN_XNAP_pduSetIntegratedHandlingInformation_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_pduSetIntegratedHandlingInformation_value2enum_4[] = {
	{ 0,	4,	"true" },
	{ 1,	5,	"false" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ASN_XNAP_pduSetIntegratedHandlingInformation_enum2value_4[] = {
	1,	/* false(1) */
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_pduSetIntegratedHandlingInformation_specs_4 = {
	asn_MAP_ASN_XNAP_pduSetIntegratedHandlingInformation_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_pduSetIntegratedHandlingInformation_enum2value_4,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_4 = {
	"pduSetIntegratedHandlingInformation",
	"pduSetIntegratedHandlingInformation",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_tags_4,
	sizeof(asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_tags_4)
		/sizeof(asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_tags_4[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_tags_4,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_tags_4)
		/sizeof(asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_tags_4[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_XNAP_pduSetIntegratedHandlingInformation_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_pduSetIntegratedHandlingInformation_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_PDUSetQoSInformation_1[] = {
	{ ATF_POINTER, 4, offsetof(struct ASN_XNAP_PDUSetQoSInformation, pduSetDelayBudget),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ExtendedPacketDelayBudget,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSetDelayBudget"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_XNAP_PDUSetQoSInformation, pduSetErrorRate),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_PacketErrorRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSetErrorRate"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_PDUSetQoSInformation, pduSetIntegratedHandlingInformation),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_pduSetIntegratedHandlingInformation_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSetIntegratedHandlingInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_PDUSetQoSInformation, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_14246P321,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_PDUSetQoSInformation_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_PDUSetQoSInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_PDUSetQoSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pduSetDelayBudget */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pduSetErrorRate */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* pduSetIntegratedHandlingInformation */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_PDUSetQoSInformation_specs_1 = {
	sizeof(struct ASN_XNAP_PDUSetQoSInformation),
	offsetof(struct ASN_XNAP_PDUSetQoSInformation, _asn_ctx),
	asn_MAP_ASN_XNAP_PDUSetQoSInformation_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_PDUSetQoSInformation_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_PDUSetQoSInformation = {
	"PDUSetQoSInformation",
	"PDUSetQoSInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_PDUSetQoSInformation_tags_1,
	sizeof(asn_DEF_ASN_XNAP_PDUSetQoSInformation_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_PDUSetQoSInformation_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_PDUSetQoSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_PDUSetQoSInformation_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_PDUSetQoSInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_PDUSetQoSInformation_1,
	4,	/* Elements count */
	&asn_SPC_ASN_XNAP_PDUSetQoSInformation_specs_1	/* Additional specs */
};

