/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#ifndef	_ASN_XNAP_IAB_TNL_Address_Request_H_
#define	_ASN_XNAP_IAB_TNL_Address_Request_H_


#include "../asn1c/asn_application.h"

/* Including external dependencies */
#include "ASN_XNAP_IABTNLAddressesRequested.h"
#include "ASN_XNAP_IABIPv6RequestType.h"
#include "ASN_XNAP_IABTNLAddressToRemove-List.h"
#include "../asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer_14246P214;

/* IAB-TNL-Address-Request */
typedef struct ASN_XNAP_IAB_TNL_Address_Request {
	ASN_XNAP_IABTNLAddressesRequested_t	 iABIPv4AddressesRequested;
	ASN_XNAP_IABIPv6RequestType_t	 iABIPv6RequestType;
	ASN_XNAP_IABTNLAddressToRemove_List_t	 iABTNLAddressToRemove_List;
	struct ASN_XNAP_ProtocolExtensionContainer_14246P214	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_IAB_TNL_Address_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_IAB_TNL_Address_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_IAB_TNL_Address_Request_H_ */
#include "../asn1c/asn_internal.h"
