/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "/home/joe/repos/UERANSIM-Handover/asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D /tmp/claude-1000/-home-joe-repos-UERANSIM-Handover/10b80aa1-9a4a-4ef1-b127-6dd0b1e6f604/scratchpad/gen3/out/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_XNAP_TAISliceUnavailableCellItem.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_TAISliceUnavailableCellItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_TAISliceUnavailableCellItem, sNSSAI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_S_NSSAI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sNSSAI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_TAISliceUnavailableCellItem, sliceAvailabilityList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_SliceAvailabilityList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sliceAvailabilityList"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_TAISliceUnavailableCellItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_14246P492,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_TAISliceUnavailableCellItem_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_TAISliceUnavailableCellItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_TAISliceUnavailableCellItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sNSSAI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sliceAvailabilityList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_TAISliceUnavailableCellItem_specs_1 = {
	sizeof(struct ASN_XNAP_TAISliceUnavailableCellItem),
	offsetof(struct ASN_XNAP_TAISliceUnavailableCellItem, _asn_ctx),
	asn_MAP_ASN_XNAP_TAISliceUnavailableCellItem_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_TAISliceUnavailableCellItem_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_TAISliceUnavailableCellItem = {
	"TAISliceUnavailableCellItem",
	"TAISliceUnavailableCellItem",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_TAISliceUnavailableCellItem_tags_1,
	sizeof(asn_DEF_ASN_XNAP_TAISliceUnavailableCellItem_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_TAISliceUnavailableCellItem_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_TAISliceUnavailableCellItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_TAISliceUnavailableCellItem_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_TAISliceUnavailableCellItem_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_TAISliceUnavailableCellItem_1,
	3,	/* Elements count */
	&asn_SPC_ASN_XNAP_TAISliceUnavailableCellItem_specs_1	/* Additional specs */
};

