/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_XNAP_CellToReport.h"

#include "ASN_XNAP_CellToReport-Item.h"
static asn_per_constraints_t asn_PER_type_ASN_XNAP_CellToReport_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_XNAP_CellToReport_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_CellToReport_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_CellToReport_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ASN_XNAP_CellToReport_specs_1 = {
	sizeof(struct ASN_XNAP_CellToReport),
	offsetof(struct ASN_XNAP_CellToReport, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_CellToReport = {
	"CellToReport",
	"CellToReport",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ASN_XNAP_CellToReport_tags_1,
	sizeof(asn_DEF_ASN_XNAP_CellToReport_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_CellToReport_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_CellToReport_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_CellToReport_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_CellToReport_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_ASN_XNAP_CellToReport_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_ASN_XNAP_CellToReport_1,
	1,	/* Single element */
	&asn_SPC_ASN_XNAP_CellToReport_specs_1	/* Additional specs */
};

