/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "asn1-definitions/xnap-rel18-v18_8.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -fhave_native64 -no-gen-example -S /home/joe/repos/asn1c-r18/skeletons -D src/asn/xnap -fprefix=ASN_XNAP_ -fcommon=asn1c -no-gen-OER`
 */

#include "ASN_XNAP_PosPartialUEContextInfo.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_ASN_XNAP_PosPartialUEContextInfo_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_PosPartialUEContextInfo, requestedSRSTransmissionCharacteristics),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_RequestedSRSTransmissionCharacteristics,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requestedSRSTransmissionCharacteristics"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_PosPartialUEContextInfo, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_14246P371,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_PosPartialUEContextInfo_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_PosPartialUEContextInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_PosPartialUEContextInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* requestedSRSTransmissionCharacteristics */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_PosPartialUEContextInfo_specs_1 = {
	sizeof(struct ASN_XNAP_PosPartialUEContextInfo),
	offsetof(struct ASN_XNAP_PosPartialUEContextInfo, _asn_ctx),
	asn_MAP_ASN_XNAP_PosPartialUEContextInfo_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_PosPartialUEContextInfo_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_PosPartialUEContextInfo = {
	"PosPartialUEContextInfo",
	"PosPartialUEContextInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_PosPartialUEContextInfo_tags_1,
	sizeof(asn_DEF_ASN_XNAP_PosPartialUEContextInfo_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_PosPartialUEContextInfo_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_PosPartialUEContextInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_PosPartialUEContextInfo_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_PosPartialUEContextInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_PosPartialUEContextInfo_1,
	2,	/* Elements count */
	&asn_SPC_ASN_XNAP_PosPartialUEContextInfo_specs_1	/* Additional specs */
};

